### ISSUE TITLE
Crear cliente SGA versión angular 7

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#1]
Crear el nuevo cliente para sistema de gestión académica.
- [x] El nuevo sistema esta en la versión angular 7.
- [x] El nuevo sistema tiene autenticación única.
- [x] El nuevo sistema integra el modulo de produccion academica.
- [x] El nuevo sistema integra el modulo de eventos.
- [x] El nuevo sistema integra el modulo de habilitación de periodo.

**Comment by JuanPiedrahita** [comment]
Se crea el cliente.

**Comment by JuanPiedrahita** [comment]
Se crea el primer [commit ](https://github.com/udistrital/sga_cliente/commit/fb24778f08db4c2f01223120a105a107813d25a5)a partir de la rama develop del proyecto configuración_v2_cliente.

**Comment by JuanPiedrahita** [comment]
Se registran producciones academicas.

**Comment by JuanPiedrahita** [comment]
Se agrega desarrollo de eventos.

**Comment by JuanPiedrahita** [comment]
@fabianbarreto02  por favor añadir módulo de habilitación de evento.

**Comment by mafeave** [comment]
Módulos integrados a través del issue #4

**Comment by JuanPiedrahita** [comment]
@mafeave  por favor hacer merge de la rama de habilitación de periodo para cerrar issue.

**Comment by mafeave** [comment]
https://github.com/udistrital/sga_cliente/pull/14
