### ISSUE TITLE
Desarrollar API de proyecto curricular - tener en cuenta API: Oikos, SNIES y SGA (4 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#10]
Se debe desarrolla el API para el modelo de datos desarrollado en la issue #8 y #9, esta issue debe satisfacer los siguiente requerimientos:
 
- [x] La api debe tener todos los lineamientos  dispuestos por OAS.
- [x] El api debe contar con el refactor para respuestas JSON.

Esta tarea depende del desarrollo de las tareas #8 y #9.

Lider técnica : @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se crea un nuevo repositorio [proyecto_academico_crud](https://github.com/udistrital/proyecto_academico_crud) para el desarrollo del api, se realizan todos los ajustes del api para el cumplimiento de los lineaminetos estos se pueden observar en los commins de la rama dev

**Comment by fabianbarreto02** [comment]
Se espera la revisión por parte de la lider técnica @mafeave

**Comment by mafeave** [comment]
Observaciones:
- Eliminar creación de rol test en el script de migración
- Eliminar OWNER TO postgres

**Comment by fabianbarreto02** [comment]
Se realizan lo ajuste definidos por @mafeave , tambien se cambian modelo, controlador y rutas por ajustes del modelo

**Comment by mafeave** [comment]
Se verifica generación del API, se elimina binario subido.
