### ISSUE TITLE
Ajuste de funciones transaccionales para la estabilización del modulo de inscripción en producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1016]
Se debe realizar el  ajuste de funciones transaccionales para la estabilización del modulo de inscripción en producción, la issue debe cumplir con los siguientes requerimientos: 

 
- [x] Ajustar el bloqueo del select de condición de discapacidad en el tag de información básica cuando se selecciona la ciudad de bogota Dc solamente ( funciona con Bogota).
- [x] Revisar por que no se esta guardando el tag de información características 
- [x] Revisar la creación de nuevos terceros en el tag de formación académica y experiencia laboral junto a la posterior consulta del tercero creado ( revisar el controlador experiencia académica sga_mid linea 138 "api de ubicaciones) tarea primero fabian (revisar creación de los tercero en prod con id 242346 y 242345)
- [x] Revisar por que no se puede eliminar un idioma en la tabla de idiomas en el tag de formación académica (posible permiso de no borrar) primero fabian.
- [x]  Revisar el porcentaje que no llega al 100% en el tag de documentos cuando ya se sube a totalidad los documentos.
- [x] Revisar tag de descuento, se carga solo el 100% no se esta cargando ni guardando la información, también se esta mostrando muchas columnas en la tabla 
- [x] Revisar carga de la propuesta de trabajo de grado

**Comment by NeFaWaltPint** [comment]
Se da desarrollo a las tareas planteadas de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
