### ISSUE TITLE
Formulario con funcionalidad y ajuste MID de registro de Información característica, tipo pregrado - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#102]
Se debe realizar la funcionalidad del registro de información característica en el tipo de inscripción pregrado,  se debe tener en cuenta la información establecida en el [documento](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit),  el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en los documentos antes mencionados.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.
- [x] La funcionalidad debe registrar la información característica en el Api de terceros desarrollado por el equipo core.
 
El desarrollo de los ajustes del mid se desarrolla en la [Issue](https://github.com/udistrital/sga_mid/issues/44).

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se termina la tarea, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se despliegan los commits realizados y se verifica funcionalidad del registro de la información característica. Formulario final:
![Captura de pantalla de 2019-12-09 06-47-48](https://user-images.githubusercontent.com/14035745/70434023-24c84800-1a51-11ea-88cd-08049d29c6d5.png)

Tener en cuenta que se está permitiendo el ingreso de valores negativos en el campo de: Puntaje Sisben
