### ISSUE TITLE
Formulario con funcionalidad para "Registro ICFES y colegio"

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#107]
Agregar funcionalidad a los formularios de inscripción de forma que se permita registrar en el sistema la información del ICFES y del colegio del aspirante.
- [x] El sistema almacena la información del ICFES y del colegio del aspirante.

**Comment by JuanPiedrahita** [comment]
Se agrega migrations, se permite el registro de la información del ICFES y del colegio, es importante aclarar que se referencia la inscripción y que esta ya debe existir, esta se recibe como input del componente en la variable (inscripcion_id), se da por terminada la tarea.

**Comment by mafeave** [comment]
No se están verificando la confirmación del Número de registro del Icfes
No carga valores en el campo de Localidad del colegio donde culminó el grado 11, por lo tanto no se pudo verificar la funcionalidad en el despliegue.
![Captura de pantalla de 2019-12-09 07-32-52](https://user-images.githubusercontent.com/14035745/70436004-4841c180-1a56-11ea-86f5-84d8b1fce4ff.png)

**Comment by JuanPiedrahita** [comment]
Se verifica el número de confirmación del Icfes al momento del envio del formulario, por favor validar nuevamente

![imagen](https://user-images.githubusercontent.com/25555966/70457963-26106980-1a7f-11ea-9110-216d05ab9283.png)

**Comment by mafeave** [comment]
Se da por terminada la tarea
