### ISSUE TITLE
Revisión de modelo de datos, ajuste de modelos de apis y función de guardado para la inclusión de campos de genero, sexo y orientación sexual. 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1079]
Se debe realizar la revisión de modelo de datos, ajuste de modelos de apis y función de guardado para la inclusión de campos de genero, sexo y orientación sexual, la issue debe cumplir los siguientes requerimientos:

- [x] Realizar la revisión de los modelos de datos actual para el almacenamiento de la información personal, ajustar el modelo y actualizar la documentación del api (repositorio)
- [x] Realizar la actualización del api si se requiere(migrate)
- [x] Afualizar la función de guardado y consulta   de la información personal con los  campos de genero, sexo y orientación sexual.

**Comment by NeFaWaltPint** [comment]
Se dan por finalizadas las tareas de la issue.

https://github.com/udistrital/sga_mid/pull/452

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
