### ISSUE TITLE
Ajuste de componente para la inclusión de campo de confirmación de documento, y campos de genero, sexo y orientación sexual. 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1080]
Se debe realizar el ajuste de componente para la inclusión de campo de confirmación de documento, y campos de genero, sexo y orientación sexual, la isuue debe cumplir con los siguientes requerimientos:

- [x] Se debe realizar el ajuste del componente de información personal con los campos de verificación de numero de documento, campos de genero, sexo y orientación sexual

![image](https://user-images.githubusercontent.com/43799065/191882104-9666c079-ae31-40d6-b654-9bdd4d5abe08.png)

- [x] Implementar las función de consulta y creación

**Comment by NeFaWaltPint** [comment]
Se dan por finalizadas las tareas de la issue.

https://github.com/udistrital/sga_cliente/pull/1088

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
