### ISSUE TITLE
Ajuste de flujo y verificación de creación de terceros para usuarios con antecedentes en los sistemas de la oficina 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1085]
Se debe realizar el ajuste de flujo y verificación de creación de terceros para usuarios con antecedentes en los sistemas de la oficina, la issue debe cumplir con los siguientes requerimientos:

- [x]  Revisar el flujo de login para aspirantes nuevos y usuarios previamente registrados en los sistemas.
- [x] Implementar una función a nivel de mid para que antes de crear el usuario en terceros, se consulte mediante usuario de wso2 (tabla tercero) y el documento registrado en el formulario si existe ya un tercero registrado, si existe se debe notificar con modal informando al usuario que ya existe un registro y mostrar la información registrada en terceros, en este caso solo se podrá editar estado civil, identidad de genero y orientación sexual, si el aspirante desea actualizar alguna imformación adicional debe realizarla por medio de una  solicitud formal a la oficina.

**Comment by NeFaWaltPint** [comment]
- Se ajusta flujo de login: se consulta por # identificación, usuario y correo, en caso negativo se considera "usuario nuevo"
- Se ajusta funcionalidad para que estando en diligencia de información personal de usuario nuevo, se consulte por # identificación si el usuario ya se encuentra registrado en el sistema, en dado caso se relacionará la información al id del tercero encontrado mediante una actualización de la información. Tales funcionalidades (consulta existencia y actualización) se consumen de sga_mid. 
- https://github.com/udistrital/sga_cliente/pull/1094

**Comment by NeFaWaltPint** [comment]
- Las funcionalidades que se consumen en cliente se desarrollan en sga_mid:

- Se añade función `ConsultarExistenciaPersona()` para verificar la existencia de tercero en base de datos, búsqueda por numero documento.
  - ruta: `persona/existe_persona/:numeroDocumento` método **GET**
- Se añade función `ActualizarPersona()` para relación la información complementaria del tercero como el Id del tercero en existencia.
  - ruta: `persona/actualizar_persona` método **PUT**

- _Las rutas mencionadas son endpoints a habilitar para acceder a mid por auth._
- https://github.com/udistrital/sga_mid/pull/454

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
