### ISSUE TITLE
Actualización de funciones para el borrado y actualización de los formularios en el proceso de inscripción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1086]
Se debe realizar la actualización  de funciones para el borrado y actualización de los formularios en el proceso de inscripción, la issue debe cumplir con los siguientes requerimientos:

- [x]  Actualizar las funciones de eliminado y actualización en todos los tag de inscripción, remplazando la eliminación por un put de desactive el registro (campo activos).
- [x] Actualizar las funciones de consulta de todos los tag de inscripción para solo consultar los registros activos.

**Comment by NeFaWaltPint** [comment]
Se realiza ajuste en mid para desactivar registros en vez de eliminarlos, se hace para lo relacionado respecto a inscripciones.

- https://github.com/udistrital/sga_mid/pull/455

### Deletes encontrados en cliente relacionados a inscripciones

- ngx-list-formacion-academica

Peticion delete cliente: 

```typescript
this.sgaMidService.delete('formacion_academica', event.data)
```

Función a la que apunta en MID: 

```go
func (c *FormacionController) DeleteFormacionAcademica()
// Ya estaba en metodo put, no cambios
```

Consulta relacionada cliente:

```typescript
this.sgaMidService.get('formacion_academica?Id=' + this.persona_id)
```

Función a la que apunta en MID:

```go
func (c *FormacionController) GetFormacionAcademicaByTercero()
// Se añade Activo:true a algunas consultas
```

---

- ngx-list-idiomas

Peticion delete en cliente:

```typescript
this.idiomaService.delete('conocimiento_idioma', event.data)
// Se cambia el metodo a .put() 
```

 Consulta relacionada en cliente:

```typescript
this.idiomaService.get('conocimiento_idioma?query=Activo:true,TercerosId:' + this.persona_id + ...
// se añade Activo:true al query
```

ajuste se hace en cliente

---

- ngx-list-experiencia-laboral

Petición delete en cliente:

```typescript
this.sgaMidService.delete('experiencia_laboral', event.data)
```

Funcion a la que apunta en MID:

```go
func (c *ExperienciaLaboralController) DeleteExperienciaLaboral()
// Ya estaba en metodo put, no cambios
```

Consulta relacionada cliente:

```typescript
this.sgaMidService.get('experiencia_laboral/by_tercero?Id=' + this.persona_id)
```

Función a la que apunta en MID:

```go
func (c *ExperienciaLaboralController) GetExperienciaLaboralByTercero()
// Se añade Activo:true a algunas peticiones
```

---

- ngx-list-produccion-academica

Peticion delete en cliente:

```typescript
this.sgaMidService.delete('produccion_academica', event.data)
```

Función a la que apunta en MID:

```go
func (c *ProduccionAcademicaController) DeleteProduccionAcademica()
// Se ajusta función para usar metodo put mediante: models.SetInactivo()
```

Consulta relacionada cliente:

```typescript
this.sgaMidService.get('produccion_academica/pr_academica/' + this.persona_id)
```

Función a la que apunta en MID:

```go
func (c *ProduccionAcademicaController) GetIdProduccionAcademica()
// No necesita añadir Activo, consulta por Id
```

---

- ngx-list-descuento-academico

Petición delete en cliente:

```typescript
this.mid.delete('descuento_academico', event.data)
```

Función a la que apunta en MID:

```go
func (c *DescuentoController) DeleteDescuentoAcademico()
// La función se encuentra comentada ¿¿¿??? why
// usa delete
```

Consulta relacionada en cliente:

```typescript
this.sgaMidService.get('descuento_academico/descuentopersonaperiododependencia?' + ...
```

Función a la que apunta en MID:

```go
func (c *DescuentoController) GetDescuentoByPersonaPeriodoDependencia()
// Se añade Activo:true a consulta
```

---

### Se ajusta controlador de inscripciones para usar metodo put en vez de delete

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
