### ISSUE TITLE
Revisión correo y almacenamiento de correo en terceros en el tag de información de contacto

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1091]
Se debe realizar la revisión correo y almacenamiento de correo en terceros en el tag de información de contacto, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisión del flujo de almacenamiento del correo del usuario (WSO2) en el api de terceros (información complementaria), buscar el id del grupo e información complementaria para los correos
- [x] Incluir en el tag de información de contacto el correo que tiene actualmente el usuario y un nuevo campo para un correo de contacto alterno que puede ingresar.
- [x] Ajustar la funcionalidad para la inclusión de los correos, guardado, actualización y consulta (incluir el registro de información complementaria para el correo alterno si no existe)
- [x] Realizar prueba de funcionamiento con al menos dos usuarios

**Comment by NeFaWaltPint** [comment]
El grupo de información complementaria `grupo_info_complementaria` al cual pertecene correo es:

```json
{   "Id": 10,
    "Nombre": "Información Contacto",
    "Descripcion": "Información de Contacto de una persona natural o juridica.",
    "CodigoAbreviacion": "Grupo_10",
}
```

Como información complementaria `info_complementaria` para el grupo _Información Contacto_  hay:

```json
{
    "Nombre": "CORREO INSTITUCIONAL",
    "CodigoAbreviacion": "CI",
},
{
    "Nombre": "CORREO",
    "CodigoAbreviacion": "CORREO",
}
```

La información difiere entre los ambientes de prueba y producción por los **Ids** en la información complementaria. **Se maneja entonces por CodigoAbreviación**.



Adicionalmente, revisando MID, hay varias consultas y guardado a la info complementaria usando estos Ids, en pruebas funciona bien, en producción la información que retornarán las consultas será erronea por esa diferencia.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
