### ISSUE TITLE
Revisión de actualización de componentes al crear, modificar o eliminar información en los tag de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1092]
Se debe realizar la revisión de actualización de componentes al crear, modificar o eliminar información en los tag de inscripción, la issue deb cumplir con los siguientes requerimientos:

- [x] Realizar un flujo completo de creación de una inscripción  con toda la información (información de contacto, experiencia laboral, experiencia académica,  producción académica, documentos, descuento y trabajo de grado)
- [x] Revisar que la carga de datos, actualización de tablas, eliminación de registros de todos los tags esten funcionando correctamente.
- [x] Ajustar los errores encontrados

**Comment by NeFaWaltPint** [comment]
- Se encontró que [idiomas_crud](https://github.com/udistrital/idiomas_crud) no cuenta con campo `Activo` en algunas tablas, razon por la cual consultas al api teniendo como parametro el campo mencionado fallaban.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
