### ISSUE TITLE
Funcionalidad para inhabilitar las inscripciones por vencimiento de fechas según calendario académico del programa 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1093]
Se debe realizar la  funcionalidad para inhabilitar las inscripciones por vencimiento de fechas según calendario académico del programa, la issue debe cumplir los siguientes requerimiento:

- [x] Actualizar el flujo de inicio del proceso de inscripción del aspirante, obligando que primero defina el select del  programa al que se escribe y profundización si aplica antes de iniciar el proceso de inscripción, si ya lo realizo permite el proceso de inscripción 
- [x] Crear una directiva o función para que pueda recibir una variable y bloquee la edición de campo o select segun sea el caso.
- [x] Implementar la directiva o función en todos los campos de los formularios del proceso de inscripción (tag en general)
- [x] Crear función para revisar la fecha del proceso de inscripción en el calendario académico que tenga asignado el programa al que se esta inscribiendo. 
- [x] Integrar la funcionalidad para que no permite la edición de campos o select cuando se encuentre por fuera de la fecha de la actividad del programa de inscripción

**Comment by NeFaWaltPint** [comment]
issue finalizada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
