### ISSUE TITLE
Revisión del flujo de aprobación y rechazo de documentos de aspirantes, incluir documentos faltantes como población y condición de discapacidad si aplica

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1097]
Se debe realiza la Revisión del flujo de aprobación y rechazo de documentos de aspirantes, incluir documentos faltantes como población y condición de discapacidad si aplica, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la revisión de documentos en el modulo de admisiones para incluir un botor de rechazo a un documento y aprobación de los documentos.
- [x] Revisar el flujo de almacenamiento de observación y estado del documentó tanto en el modulo de documentación y vista aspirante 
- [x] Incluir los documentos de población y condición de discapacidad cuando existe documento en el componente de revisión de documentación en admisiones

**Comment by NeFaWaltPint** [comment]
Se da inicio a la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
