### ISSUE TITLE
Unificar ramas de los repositorios - producción académica, inscripción, eventos, evaluación inscripción, cliente y MID. (8 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#11]
Se debe unificar las ramas de los repositorios repositorios enmarcadas en el sistema de gestión academica, esta tarea se realizara despues de haber culminado las tareas #8 y #9.

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia la tarea

**Comment by fabianbarreto02** [comment]
Para la unificación de las ramas de los repositorios antes mencionados se establece el siguiente mecanismo:

- Por realiza un clon local de cada unos de los repositorios, los cuales seran almacenados en un pc local y comprimidos y subidos a drive en el estado que se encuentren en el momento de realizar la tarea.
- Se realizara un fork de cada repo a mi cuenta personal en  el estado que se encuentren en el momento de realizar la tarea.

Estas dos cosas se hacen pues se realizara el merge entre la rama mas lejana y dev, posteriormente se eliminaran el resto de las ramas creadas, solo quedaran la ramas definidas en los lineamientos, master, dev y test, en caso de ser requerido alguna rama borrada se contara con el respaldo ya antes mencionado.

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de la lider técnica @mafeave

**Comment by mafeave** [comment]
Se hace verificación de los merge realizados por @fabianbarreto02, se da por finalizada la tarea.
