### ISSUE TITLE
Análisis y ajuste de modelos de datos para el almacenamiento de configuración de tag por programa y periodo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1102]
Se debe realizar el análisis y ajuste de modelos de datos para el almacenamiento de configuración de tag por programa y periodo, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar el modelo de datos del api de evaluacion_inscripcion, analizar si se puede crear una tabla parametrica relacionada o  la creación de una tabla independiente en el esquema
- [x] Ajustar el api con el modelo, controlador y modelo de datos actualizado con los cambios ajustados.
- [ ] Crear la migración con los cambios realizados

**Comment by NeFaWaltPint** [comment]
Desarrollo de la issue:
- https://github.com/udistrital/evaluacion_inscripcion_crud/pull/45

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
