### ISSUE TITLE
Revisar tabla recibos con programa real inscrito y estado de inscripción, ajustar base idiomas tabla conocimeito_idiomas con campo true  revisar tablas transaccionales y bloqueo de botón inscripción, cuanto se cambien el estado del aspirante a inscrito y cambio de programa 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1103]
Se debe revisar tabla recibos con programa real inscrito y estado de inscripción, ajustar base idiomas tabla conocimeito_idiomas con campo true  revisar tablas transaccionales y bloqueo de botón inscripción, cuanto se cambien el estado del aspirante a inscrito y cambio de programa, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la función para que el nombre del programa que aparece en la tabla de recibos generados (Pin) sea el nombre del select registrado en el tag de inscripción general, si no se tiene informacion en el api de inscripcion_crud se debe concolar el nombre del recibo. 

![image](https://user-images.githubusercontent.com/43799065/197073505-8b959ba7-631d-4d2b-9377-585f6104fd64.png)

- [x] Incluir en la tabla  recibos generados (Pin) campo del estado de inscripcion registrado en el api de inscripcion_crud y en el componente de inscripción general y ajustar la consulta de la tabla de idiomas 
- [x] Ajustar en el api de idiomas_crud en la tablas faltantes el campo activo, ajustar modelos, incluir migrations y modelo de datos .
- [x] Hacer funcioanlidad para boquear el select de programa y enfasis una vez se pase a un estado inscrito 

- [x] Cambiar nombre de botón estado inscripción (inscrito) con "Ver inscripción"

**Comment by NeFaWaltPint** [comment]
Desarrollo de tareas en cliente:
- https://github.com/udistrital/sga_cliente/pull/1109

Ajuste de idiomas_crud:
- https://github.com/udistrital/idiomas_crud/pull/26

Ajuste menor en sga_mid para consumo en cliente:
- https://github.com/udistrital/sga_mid/pull/464

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
