### ISSUE TITLE
Creación del componente y funcionalidad (creación, consulta, edición y delete) para el registro de parametos de suite de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1107]
Se debe realizar la Creación del componente y funcionalidad (creación, consulta, edición y delete) para el registro de parametos de suite de inscripción , la issue debe cumplir con los siguientes requerimientos:

- [x] Crear el siguiente componente en el meno de admisiones con el nombre "Definición SUITE para el proceso de inscripción"
![image](https://user-images.githubusercontent.com/43799065/198188478-0a217447-09c8-4163-a2c0-a849dcbb7a2d.png)

![image](https://user-images.githubusercontent.com/43799065/198188642-a3e9b814-873d-4d70-9262-12518f3662d1.png)

![image](https://user-images.githubusercontent.com/43799065/198188945-8cd465fe-9a80-4a5f-b2b9-cde7443e0bfc.png)

- [x] Crear la funcionalidad para la creación, consulta, edición y delete (campo activo false) para el registro de la suite de inscrión

**Comment by NeFaWaltPint** [comment]
MENU:

routing componente: _"Definición de SUITE de inscripción por proyecto curricular"_

**label_i18n:** `admision.definicion_suite_inscripcion_programa`

**path:** `pages/admision/suite-programa`

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
