### ISSUE TITLE
Formulario con funcionalidad y ajuste MID de registro de Información de contacto, tipo pregrado - 12 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#111]
Se debe realizar la funcionalidad del registro de información de contacto en el tipo de inscripción pregrado,  se debe tener en cuenta la información establecida en el [documento](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit),  el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en los documentos antes mencionados.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.
- [x] La funcionalidad debe registrar la información característica en el Api de terceros desarrollado por el equipo core.
 
El desarrollo de los ajustes del mid se desarrolla en la [Issue](https://github.com/udistrital/sga_mid/issues/45).

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, se espera revision por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se despliegan los commits realizados y se verifica funcionalidad del registro de la información de contacto. Formulario final:
![Captura de pantalla de 2019-12-09 07-18-12](https://user-images.githubusercontent.com/14035745/70435169-1b8caa80-1a54-11ea-999f-3235b5a01a70.png)

Tener en cuenta las siguientes observaciones:
- Ajustar longitud de los campos de Estrato de la residencia y Código postal, no permitir valores negativos
- Cambiar el orden del campo de Localidad para que se muestre después del campo de Ciudad.
- ¿Se debería pedir correo, si ya se tiene uno con el usuario creado en WSO2?
- No se está verificando la confirmación del correo electrónico
- Se está cargando el loading antes de confirmar el registro de los datos
- Para ajustes futuros: la dirección debería cargarse a través de un componente que verifique la nomenclatura

**Comment by mafeave** [comment]
Se verifican ajustes solicitados, se da por finalizada la tarea.
