### ISSUE TITLE
Análisis y definición de la librería para la compilación de documentos en go 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1152]
Se debe realizar el Análisis y definición de la librería para la compilación de documentos en go, la issue debe cumplir con los siguientes requerimientos:

- [x]  Analizar como puedo agrupar pdf en formato base 64 para enviar desde el api mid al cliente, desde el cliente debe recibir la petición con los archivos agrupados y poder descargar desde el cliente un archivo comprimido (zip o rar)

**Comment by NeFaWaltPint** [comment]
Hay dos posibilidades:

1. Usar `archive/zip` en Golang MID -> [librería](https://pkg.go.dev/archive/zip)
2. Usar `JSZip` en Angular CLIENTE -> [librería](https://stuk.github.io/jszip/)

# 1. Método 1: todo el proceso recae en MID
1. Recolecta el listado de documentos base64
2. Se decodifican y se organizan
3. Uso de **archive/zip** para comprimir
4. Codifica nuevamente a base64
5. Envío a cliente
6. _Cliente debe decodificar y guardar como zip_

# 2. Método 2: la compresión la realiza Cliente
1. _MID recolecta el listado de documentos base64 y organiza los archivos._
2. _MID los envía a cliente en un JSON_
3. Cliente recibe, decodifica los archivos,
4. convierte a zip mediante **JSZip**
5. guardar

De las dos alternativas presentadas la más opcionada es la No. 2, ya que se evita hacer tanta codificación y decodificación de base64, claro está que realizar la compresión en cliente puede resultar lento si son bastantes documentos; pero, se prevé que la implementación puede ser más rápida.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
