### ISSUE TITLE
Implentación de función general para la compilación de documentos, que reciba los documentos (base64, pdf) y devuelva organizado en una respuesta

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1161]
Se debe realizar la Implantación de función general para la compilación de documentos, que reciba los documentos (base64, pdf) y devuelva organizado en una respuesta, la issue debe cumplir con los siguiente requerimientos:

- [x] La función debe recibir como parámetros el id del tercero, periodo, programa  académico para identificar la búsqueda de los documentos.
- [x] La función debe realizar la busqueda de todos los documentos del aspirante, en la sección de Información básica, Información Académica, Experiencia laboral, Producciones académicas, Descuentos de matrícula, Propuesta de trabajo de grado y Documentos solicitados con la información del tercero a consultar para un periodo partícular y el programa, puede existir varios  documento en una sección y puede existir información para una misma persona con un periodo particular y programa academico.
- [x]  La función debe organizar cada archivo y convertirlo en base 64.
- [x] Crear la respuesta con los documentos organizador en un objeto por sección con cada documento.

**Comment by NeFaWaltPint** [comment]
Se da inicio al desarrollo de las tareas.

**Comment by NeFaWaltPint** [comment]
Se da resolución a la issue propuesta. https://github.com/udistrital/sga_cliente/pull/1171

Sin embargo, no se aborda de la manera planteada.
- Se parte de que ya los archivos están listos para el compilado aprovechando la vista "Detalle de inscripción" _(componente perfil)_ 
De cualquier forma se está evaluando si es demasiada carga para el cliente, si es así se puede desarrollar como se había planteado originalmente.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
