### ISSUE TITLE
Ajuste pdf del recibo para copia del programa 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1187]
Se debe realizar el Ajuste pdf del recibo para copia del programa, teniendo en cuenta  el recibo de ejemplo, la issue debe cumplir con los siguientes requerimiento:

- [x]  Incluir la copia de programa en el recibo actual 
![image](https://user-images.githubusercontent.com/43799065/209568271-84eee829-b24b-4217-8714-230ca681c61c.png)

[ejemplo recibo.pdf](https://github.com/udistrital/sga_cliente/files/10304144/ejemplo.recibo.pdf)

[recibo actual.pdf](https://github.com/udistrital/sga_cliente/files/10304148/recibo.actual.pdf)

- [x] Ajustar para que el campo del nombre del proyecto no se cruce o se salga cuando el nombre es largo 
![image](https://user-images.githubusercontent.com/43799065/209568392-a2fbdcff-8bde-4f78-9c48-98692a4f16f8.png)

**Comment by NeFaWaltPint** [comment]
## Se ajusta generación de recibo para incluir copia a Proyecto curricular:
`POST -> SGA_MID/v1/generar_recibo`
**Info extensa**
```json
{
    "NombreDelAspirante": "Nombre1 Nombre2 Apellido1 Apellido2",
    "DocumentoDelAspirante": "1234567890",
    "Periodo": "2023-1",
    "ProyectoAspirante": "Maestría en Ingeniería Aeroespacial tripulada y autónoma",
    "Comprobante": "1225",
    "Fecha_pago": "10/01/2023",
    "Descripcion": "pago de pin para prueba de ingreso a maestría",
    "ValorDerecho": 133300
}
```
[reciboAsp1.pdf](https://github.com/udistrital/sga_cliente/files/10331978/reciboAsp1.pdf)

**Info corta**
```json
{
    "NombreDelAspirante": "Nombre1 Nombre2 Apellido1 Apellido2",
    "DocumentoDelAspirante": "1234567890",
    "Periodo": "2023-1",
    "ProyectoAspirante": "Maestría en Ingeniería Aeroespacial",
    "Comprobante": "1225",
    "Fecha_pago": "10/01/2023",
    "Descripcion": "Recibo preinscripcion",
    "ValorDerecho": 133300
}
```
[reciboAsp2.pdf](https://github.com/udistrital/sga_cliente/files/10331986/reciboAsp2.pdf)

Existe otro recibo en la siguiente ruta, también se ajusta:
`POST -> SGA_MID/v1/generar_recibo/recibo_estudiante`
**Info extensa**
```json
{
    "NombreDelEstudiante": "Nombre1 Nombre2 Apellido1 Apellido2",
    "DocumentoDelEstudiante": "1234567890",
    "CodigoDelEstudiante": "0123456",
    "Periodo": "2023-1",
    "ProyectoEstudiante": "Maestría en Ingeniería Aeroespacial tripulada y autónoma",
    "Comprobante": "1225",
    "Fecha_pago": "10/01/2023",
    "Descripcion": "pago de pin para prueba de ingreso a maestría",
    "ValorDerecho": 133300,
    "Codigo": "10"
}
```
[reciboEst1.pdf](https://github.com/udistrital/sga_cliente/files/10331994/reciboEst1.pdf)

**Info corta**
```json
{
    "NombreDelEstudiante": "Nombre1 Nombre2 Apellido1 Apellido2",
    "DocumentoDelEstudiante": "1234567890",
    "CodigoDelEstudiante": "0123456",
    "Periodo": "2023-1",
    "ProyectoEstudiante": "Maestría en Ingeniería Aeroespacial",
    "Comprobante": "1225",
    "Fecha_pago": "10/01/2023",
    "Descripcion": "pago prueba de ingreso",
    "ValorDerecho": 133300,
    "Codigo": "10"
}
```
[reciboEst2.pdf](https://github.com/udistrital/sga_cliente/files/10331995/reciboEst2.pdf)
