### ISSUE TITLE
Verificar carga de años y meses en el formulario de "Registro calificado" en el campo "Vigencia del registro" - 2 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#119]
Se debe revisar la carga de años y meses en el formulario de registro calificado, en especial cuando alguno de los campos se ingresa un numero 0.

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de revisión

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue, se espera revisión técnica por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica carga y edición de los meses y años de la vigencia de los registros calificados y de acreditación. 

Tener en cuenta que se está permitiendo el ingreso de valores negativos (del -1 al -9) en los campos de año y meses, número de resolución
