### ISSUE TITLE
Agregar histórico de acreditaciones y botón de guardar, a los mockups de proyecto curricular (3 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#12]
Se debe desarrollar los mockups para observar el historial de registros y correguir el boton "Guardar sin cambios" segun revisión de la issue #7,  la issue debe cumplir con los siguiente requerimiento:

- [x] Los mockups se debe realizar en la herramienta draw.io como esta establecido en los lineamiento de la OAS.
- [x] Los mockups debe contemplar todo lo definido en la historia de usuarios.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
se inicia proceso

**Comment by fabianbarreto02** [comment]
Teniendo en cuenta la issue #7, se realizan los ajuste definidos en la #9  y segun el [documento](https://docs.google.com/document/d/1jysaPoHcG0bv4PWaoFkTuQ2Utfk-dZ26MNaYxA0Wsbo/edit) elaborado por @FaustoPuerto.

**Comment by fabianbarreto02** [comment]
Mockup de registro por primera vez 

![Mockup Registro de proyecto académico](https://user-images.githubusercontent.com/43799065/64440934-8794f680-d092-11e9-80f3-2ee97da62b57.png)

**Comment by fabianbarreto02** [comment]
Mockup Creación registro

![Mockup Registro de proyecto académico(2)](https://user-images.githubusercontent.com/43799065/64441119-d80c5400-d092-11e9-9f22-9ee6733099cf.png)

**Comment by fabianbarreto02** [comment]
Mockup consulta general

![Mockup Consulta, inhabilitar y modificación de proyectos académico](https://user-images.githubusercontent.com/43799065/64441256-1f92e000-d093-11e9-89de-e8a9eaff2d77.png)

**Comment by fabianbarreto02** [comment]
Mockups Consulta  basica

![Mockup Consulta, inhabilitar y modificación de proyectos académico(1)](https://user-images.githubusercontent.com/43799065/64441338-4d782480-d093-11e9-9a12-c9f96ec27c32.png)

**Comment by fabianbarreto02** [comment]
Mockups historico registro

![Mockup Consulta, inhabilitar y modificación de proyectos académico(2)](https://user-images.githubusercontent.com/43799065/64441425-7bf5ff80-d093-11e9-8918-6f793feb06bf.png)

**Comment by fabianbarreto02** [comment]
Mockups Consulta, modificación y crear un proyecto a partir de uno ya existente con propiedades similiares

![Mockup Consulta, inhabilitar y modificación de proyectos académico(3)](https://user-images.githubusercontent.com/43799065/64456462-e1f37e80-d0b5-11e9-82cc-d22d1d67308b.png)

**Comment by fabianbarreto02** [comment]
Mockups Modificación realizada 

![Mockup Consulta, inhabilitar y modificación de proyectos académico(4)](https://user-images.githubusercontent.com/43799065/64456566-1cf5b200-d0b6-11e9-9c00-23c0466d379a.png)

**Comment by fabianbarreto02** [comment]
Mockups para Inhabilitar proyecto

![Mockup Consulta, inhabilitar y modificación de proyectos académico(5)](https://user-images.githubusercontent.com/43799065/64456642-4f071400-d0b6-11e9-9983-22d1e7a8a1af.png)

**Comment by fabianbarreto02** [comment]
Mockups Inhabilitar realizado 

![Mockup Consulta, inhabilitar y modificación de proyectos académico(6)](https://user-images.githubusercontent.com/43799065/64456684-6fcf6980-d0b6-11e9-8b83-4db50257fbd6.png)

**Comment by fabianbarreto02** [comment]
Mockups Proyecto Inhabilitado

![Mockup Consulta, inhabilitar y modificación de proyectos académico(7)](https://user-images.githubusercontent.com/43799065/64456739-92618280-d0b6-11e9-9fad-698bcb6412fc.png)

**Comment by fabianbarreto02** [comment]
Se anexan mockups para la edición [registro](https://www.draw.io/?state=%7B%22ids%22:%5B%221CEakcj2hk_Ao_DKg5LSgM2E4tUjnvS04%22%5D,%22action%22:%22open%22,%22userId%22:%22102492667183582276825%22%7D#G1CEakcj2hk_Ao_DKg5LSgM2E4tUjnvS04) y [modificación](https://www.draw.io/?state=%7B%22ids%22:%5B%221PdvIOst1eF3r61Hft1zVTV9KOZw54FJT%22%5D,%22action%22:%22open%22,%22userId%22:%22102492667183582276825%22%7D#G1PdvIOst1eF3r61Hft1zVTV9KOZw54FJT)

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se hacen observaciones por parte del equipo de trabajo, las cuales se están trabajando en el issue: https://github.com/udistrital/proyecto_academico_crud/issues/1
