### ISSUE TITLE
Definición de reportes

### ISSUE THREAD

**Issue by milo19980525** [udistrital/sga_cliente#1217]
Definir con el cliente:

1. Ubicación de los reportes.
2. Contenido de los reportes (Inscritos y Admitidos)

**Criterios de aceptación**
- [] Documento tipo HU con la información levantada.

**Comment by cearomeroc** [comment]
Se realiza acercamiento con usuarios funcionales de los programas Maestría Ingeniería Industrial (Alison Rubiano) y Maestría Ingeniería Civil (Paola Quintero) quienes indican que es conveniente que se cree un menú denominado REPORTES, y que el documento o documentos generados allí se les presente en formato de EXCEL o *xls.

Para el levantamiento de estos requerimientos se generaron tres documentos:

- Mockup orientativo ([formato draw.io ](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EcdfTZ0kTFFCs78xvzsEQqUBexMOCdKB_-VkL0uAsvyNvg?e=Ht6NC1)y [formato PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EXVjmo1nn4lIhqLimzHzjhIBMpOyKA8jFO2Tgmh01D8i7g?e=fgmfKP)).
- [Formato reportes.](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETlJuARHptFPj3YdqddpwyUBoq_IuFZ3Bd7HUWcQRCi90Q?e=J7yYCs)
- [HU modulo reportes](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EX3SIC2hp2lDoRneZk8ym3ABreke_S_eR_cT6vgZdZ8ZqQ?e=YRF9gK).
