### ISSUE TITLE
Desarrollar la funcionalidad para los formularios de inscripcion - tipo de inscripción transferencia externa

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#123]
Agregar funcionalidad a los formularios de inscripción de forma que se permita registrar en el sistema la información de una transferencia externa.

- [x] El sistema almacena la información de una transferencia externa.

**Comment by JuanPiedrahita** [comment]
Se termina la tarea teniendo en cuenta lo siguiente: 
- El formulario de datos del icfes es el mismo utilizado para la inscripción de pregrado.
- El campo de universidad es de tipo select, pero debido a que aun no se conoce de donde se obtendra el listado de universdidades se deja por el momento como un input.

**Comment by mafeave** [comment]
Se verifica el desarrollo realizado.
