### ISSUE TITLE
Ajustar la funcionalidad para los formularios de inscripcion - tipo de inscripción posgrado

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#124]
Agregar funcionalidad a los formularios de inscripción de forma que se permita registrar en el sistema la información de una inscripción de posgrado.

- [x] El sistema almacena la información básica de la inscripción de posgrado.
- [x] El sistema almacena la información academica de la inscripción de posgrado.
- [x] El sistema almacena la información de idiomas de la inscripción de posgrado.
- [x] El sistema almacena la información de experiencia laboral de la inscripción de posgrado.
- [x] El sistema almacena la información de la prodcción academica de la inscripción de posgrado.
- [x] El sistema almacena la información de los documentos de la inscripción de posgrado.
- [x] El sistema almacena la información de descuentos de la inscripción de posgrado.
- [x] El sistema almacena la información de la propuesta de trabajo de grado de la inscripción de posgrado.
- [x] El sistema almacena la información del perfil de la inscripción de posgrado.

**Comment by JuanPiedrahita** [comment]
https://github.com/udistrital/sga_mid/commit/41fff634dadefee74f799940074c1c1fb40f9971

**Comment by JuanPiedrahita** [comment]
Avance de la tarea hasta el momento: 
- Se hace post de la información básica.
- Se carga información de la universidad y de contaco de la misma desde el api de terceros (con mid).
- Se crea función para registrar inscripción en controlador general en caso de que se necesite.
- Se hace post de conocimiento de idiomas.
- SE hace post de examen idioma posgrado.

**Comment by JuanPiedrahita** [comment]
Avancce de la tarea: Se hace post de la información de lso tags, menos el de perfil que inccluye la consulta de todos lso anteriores.

**Comment by JuanPiedrahita** [comment]
Se termina la tarea se consulta información del perfil del estudiante, falta unicamente la información básica del mismo, integración que se debe realizar con lo realizado por @fabianbarreto02.

**Comment by mafeave** [comment]
Se verifica el desarrollo realizado. 
Tener en cuenta que hace falta la integración del formulario de información básica.
