### ISSUE TITLE
Levantamiento de requerimientos espacios académicos y planes de estudio

### ISSUE THREAD

**Issue by cearomeroc** [udistrital/sga_cliente#1247]
Se requiere el levantamiento de requerimientos para los componentes  * Espacios académicos y * Planes de estudio, para ello se requiere la realización de mesas de trabajo con usuarios, revisión de documentación relacionada, definición de HU y mockups respectivos.

**Especificaciones técnicas**

- Runirse con los usuarios levantar los requerimientos del hito 2.
- Realizar HU asociadas a los querimientos definidos.
- Refinar HU y definir Mockups.

**Sub Tareas**

- [x] Reunirse con los usuarios para levantamiento de requerimientos.
- [x] Definir HU.
- [ ] Refinar HU.
- [x] Creación de Mockups

**Criterios de aceptación**

- [ ] Definición de HU para comenzar desarrollo.
- [ ] Diseño de Mockups.

**Requerimientos**

- [ ] Ninguno.

**Dependencias**

- Ninguna.

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by cearomeroc** [comment]
Se realiza sesion para el levantamiento de requerimientos con programas curriculares
* 28/04/2023 programas: maestria ingenieria industrial  y maestria ingenieria civil ([acta](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EV5kUhuvdL9AnJ2TymH5pEcB07o7zN6njFyBI8GJ_N0sHw?e=GL6s3B))
* 02/05/2023 programa: maestria en educacion en tecnologia (acta)

**Comment by cearomeroc** [comment]
Se crea carpeta contenedora para los documentos generados y soportes de la gestión ([enlace](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EomnTiXLH79Kudsda5R5RRUB18kygVCNGJf99urKTsvpvg?e=nsnBgE))

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
