### ISSUE TITLE
Realizar ajustes a los tags de información de contacto e información característica (Tarea no planeada)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#125]
Tener en cuenta las observaciones: 

- [x] Ajustar longitud de los campos de Estrato de la residencia y Código postal, no permitir valores negativos.

- [x]  Cambiar el orden del campo de Localidad para que se muestre después del campo de Ciudad

- [x]  ¿Se debería pedir correo, si ya se tiene uno con el usuario creado en WSO2?.

- [x]  No se está verificando la confirmación del correo electrónico.

- [x]  Se está cargando el loading antes de confirmar el registro de los datos.

- [x]  Para ajustes futuros: la dirección debería cargarse a través de un componente que verifique la nomenclatura. Se hace solicitud al core mediante el [kanban #34211](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34211)

En el tag de información característica tener en cuenta la observaciones:

- [x]  Tener en cuenta que se está permitiendo el ingreso de valores negativos en el campo de: Puntaje Sisben.

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
el loading se realiza al momento de evaluar los campos en cada formulario se ejecuta mediante una promesa por eso el loading.

**Comment by fabianbarreto02** [comment]
Se finaliza la issue, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Verificados los ajustes, , se da por finalizada la tarea.
