### ISSUE TITLE
Ajuste de funcionalidad edición tag descuentos cliente y mid y producción académica 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1256]
Se requiere realizar el Ajuste de funcionalidad edición tag descuentos cliente y mid y producción académica. 

**Sub Tareas**

- [x] Revisar y ajustar el controlador la edición de los documentos del tag descuentos del proceso de inscripción, se debe ajustar el flujo de actualización de documentos con la actualización de registro (campo Activo).
- [x] Controlar el registro en el cliente para no permitir el registro de dos mismo documentos.
- [x] Revisar y ajustar el controlador la edición de los documentos del tag producción académico del proceso de inscripción, se debe ajustar el flujo de actualización de documentos con la actualización de registro (campo Activo).

**Criterios de aceptación**

- [x] Realizar pruebas del controlador en entorno local
- [x] Realizar pruebas del controlador en entorno de pruebas

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Test local

PUT producción académica Ok, Se corrige la metadata que se enviaba.
![PUT producción acad](https://user-images.githubusercontent.com/31144689/236832008-e34a7588-0ae8-4ee6-a663-7e7fd835e747.png)

PUT descuentos Ok, Se restablece la funcionalidad de editar ya que siempre se estaba creando, y generaba duplicados.
![PUT descuentos](https://user-images.githubusercontent.com/31144689/236832367-bcc2ec2c-6246-4637-90e2-77dd07b7b290.png)

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se por finalizada la actividad
