### ISSUE TITLE
Ajuste de controladores Put para todas las apis crud del sistema SGA

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1257]
Se requiere realizar el ajuste de controladores Put para todas las apis crud del sistema SGA

**Sub Tareas**

- [x] Revisar y ajustar el controlador Put el api de [calificaciones_crud](https://github.com/udistrital/calificaciones_crud) para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de 
[descuento_academico_crud  ](https://github.com/udistrital/descuento_academico_crud) para no actualización de la fecha de creación.

- [x] Revisar y ajustar el controlador Put el api de [espacios_academicos_crud](https://github.com/udistrital/espacios_academicos_crud) para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud) para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de [idiomas_crud](https://github.com/udistrital/idiomas_crud) para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de [inscripcion_crud](https://github.com/udistrital/inscripcion_crud) para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de [produccion_academica_crud](https://github.com/udistrital/produccion_academica_crud)  para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de [proyecto_academico_crud](https://github.com/udistrital/proyecto_academico_crud)  para no actualización de la fecha de creación.
- [x] Revisar y ajustar el controlador Put el api de [solicitudes_crud](https://github.com/udistrital/solicitudes_crud)  para no actualización de la fecha de creación.

**Criterios de aceptación**

- [x] Realizar la solicitud de pull request para cada repositorio 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Se desarrollan los ajuste para evitar cambio en fecha de creación de las siguientes APIs en método PUT.

- [x] calificaciones (En servicio conexión a bd, usando findById() se trae registro actual antes de ser modificado para pasarle la fecha de creación a la data entrante así siempre se asegura que se toma la fecha real ya en bd).
  - **Se actualiza a go1.18 y validan steps: nest_build, publish(DockerFile), update_aws_ecs**

- [x] espacios_academicos (En servicio conexión a bd, usando findById() se trae registro actual antes de ser modificado para pasarle la fecha de creación a la data entrante así siempre se asegura que se toma la fecha real ya en bd)
  - **Se actualiza a go1.18 y validan steps: nest_build, publish(DockerFile), update_aws_ecs**

- [x] descuento_academico (No necesita actualizar PUT ya lo hace desde models evitando pasar el campo FechaCreacion, pero si hacía falta incluir un campo en _descuentos_dependencia_ y había otro duplicado en _validacion_descuento_)
  - El detalle de usar el método de models es que en el put si se pone la fecha mal en la respuesta la mostrará mal también, sin embargo al no pasar este campo a base de datos, no se altera, al hacer get se corrobora que la fecha creación sigue intacta.
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate, beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test

- [x] evaluacion_inscripcion (Solo hacía falta en tags_por_dependencia; siguiendo el método que ya estaba, desde models se pasan todos los campos excepto FechaCreacion así ese campo no cambia su valor ya que nunca lo recibe en base de datos)
  - El detalle de usar el método de models es que en el put si se pone la fecha mal en la respuesta la mostrará mal también, sin embargo al no pasar este campo a base de datos, no se altera, al hacer get se corrobora que la fecha creación sigue intacta.
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate, beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test

- [x] idiomas (Por el versionamiento que se maneja en esta API v1 y v2, para generar el menor conflicto posible en los flujos para las dos versiones, se ajusta desde el lado de modelos, ya que este lo comparten las dos versiones, de igual manera, aquí se evita pasar el campo FechaCreacion para que en base de datos no sea editado)
  - El detalle de usar el método de models es que en el put si se pone la fecha mal en la respuesta la mostrará mal también, sin embargo al no pasar este campo a base de datos, no se altera, al hacer get se corrobora que la fecha creación sigue intacta.
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate, beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test

- [x] inscripcion (En Controller, usando GetById() se trae registro actual antes de ser modificado para pasarle la fecha de creación a la data entrante así siempre se asegura que se toma la fecha real ya en bd y en la respuesta sale la fechaoriginal sin importar se le pasa la fecha modificada)
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate, beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test

- [x] produccion_academica (En Controller, usando GetById() se trae registro actual antes de ser modificado para pasarle la fecha de creación a la data entrante así siempre se asegura que se toma la fecha real ya en bd y en la respuesta sale la fechaoriginal sin importar se le pasa la fecha modificada)
  - Los controladores tr no se alteran
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate, beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test

- [x] proyecto_academico (En Controller, usando GetById() se trae registro actual antes de ser modificado para pasarle la fecha de creación a la data entrante así siempre se asegura que se toma la fecha real ya en bd y en la respuesta sale la fechaoriginal sin importar se le pasa la fecha modificada)
  - en registro_calificado_acreditacion, tambien se evita editar: fecha_acto_admin y vencimiento
  - Los controladores tr no se alteran
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate, beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test


- [x] solicitudes (En Controller, usando GetById() se trae registro actual antes de ser modificado para pasarle la fecha de creación a la data entrante así siempre se asegura que se toma la fecha real ya en bd y en la respuesta sale la fechaoriginal sin importar se le pasa la fecha modificada)
  - en solicitud_evolucion_estado, tambien se evita editar: fecha_limite; y en solicitud: fecha_radicacion
  - Los controladores tr no se alteran
  - **Se actualiza a go1.18 y validan steps: go_build, beego_migrate (funciona pero falla un script, aunque en test y prod no debe fallar ya que se supone se ha ejecutado previamente), beego_rollback, publish(DockerFile), update_aws_ecs**
  - no se probó go_run_test

**Comment by NeFaWaltPint** [comment]
## test local

### calificaciones
![calificaciones put](https://user-images.githubusercontent.com/31144689/236320601-767b40b7-426c-42ff-b199-94428cb54275.png)

### espacios_academicos
![espacios_academicos put](https://user-images.githubusercontent.com/31144689/236320691-015aaead-d7d7-49fa-96f9-f92ea1b0a393.png)

### evaluacion_inscripcion
put muestra fecha erronea, pero.. como ya se comentó antes...
![evaluacion_inscripcion put fechamal](https://user-images.githubusercontent.com/31144689/236321080-cae4027a-0c53-4930-8859-bcc3576661c4.png)
get trae la consulta con fecha correcta
![evaluacion_inscripcion  get fechabien](https://user-images.githubusercontent.com/31144689/236321290-bc84b326-3ef0-4f25-86aa-b224bb574ccb.png)

### idiomas
![idiomas put](https://user-images.githubusercontent.com/31144689/236321384-ab47a813-fb4a-4078-9b03-25e31a84c3af.png)

### inscripcion
![inscripcion put](https://user-images.githubusercontent.com/31144689/236321469-b1ed3cd2-c86e-4642-a3b3-5207613733d2.png)

### produccion_academica
![produccion academica put](https://user-images.githubusercontent.com/31144689/236321580-7a9cf1cd-8d18-4edd-9f7b-a2d2d2202763.png)

### proyecto_academico
![proyecto_academico put](https://user-images.githubusercontent.com/31144689/236321793-1e2405b6-94e7-4a8a-9f9c-2dc0bc994e80.png)

### solicitudes
![solicitud put](https://user-images.githubusercontent.com/31144689/236321898-c7e9f8e1-e6eb-4a03-8113-9eaf0ab3f54d.png)

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue y se realiza el despliegue en el entorno de pruebas y producción
