### ISSUE TITLE
Revisar los datos requeridos para el registro de movilidad académica 

### ISSUE THREAD

**Issue by mafeave** [udistrital/sga_cliente#126]
Teniendo en cuenta los datos solicitados para la movilidad académica en el actual sistema de inscripciones, ver [documento](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit) de la funcionalidad actual, se debe verificar qué información es la que realmente necesita la Oficina de Admisiones para gestionar las inscripciones por movilidad académica.

**Comment by FaustoPuerto** [comment]
El formulario que se diligencia para los estudiantes que vienen en opción de movilidad es el mismo que se utiliza para los estudiantes de pregrado.
Los datos son ingresados por la Coordinación de Admisiones, previo aval del Centro de Relaciones Interinstitucionales (CERI).
