### ISSUE TITLE
Análisis, diseño y creación para el modelo de datos para la gestión plan de trabajo docente, creación del api_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1267]
Se requiere realizar el Análisis, diseño y creación para el modelo de datos para la gestión plan de trabajo docente, creación del api_crud

**Sub Tareas**

- [x] Realizar el análisis de todo el modulo de plan de trabajo docente (mirar [mockup](https://drive.google.com/file/d/15THSeB1hUXLI-WyX0U257wonczMsb7On/view)) para la extracción de los campos necesarios para la creación del modelo de datos.
- [x] Diseño del modelo de datos para el manejo del plan docente ( creación de carga electiva, creación de actividades docentes, estados, relación con espacios académicos, relación persona, distribución de horario, entre otros ).
- [x] Presentación del modelo de datos diseñado con el líder técnico para el análisis de viabilidad. 
- [x]  Creación del api crud para los planes de trabajo docente, bajo la tecnología de nest y mongo, ajustar documentación para despligues (archivos [.drone.yml](https://github.com/udistrital/espacios_academicos_crud/blob/develop/.drone.yml), [.gitignore](https://github.com/udistrital/espacios_academicos_crud/blob/develop/.gitignore), [Dockerfile](https://github.com/udistrital/espacios_academicos_crud/blob/develop/Dockerfile), [entrypoint.sh](https://github.com/udistrital/espacios_academicos_crud/blob/develop/entrypoint.sh), [README.md](https://github.com/udistrital/espacios_academicos_crud/blob/develop/README.md)) con los lineamientos de la oficina 
- [x] Documentar el modelo de datos con la herramienta draw.io y anexarla en la [carpeta ](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Eq5UXdP-uAJNta8C8gOSNG8BNdsqN93lqjkS0-WBNRxJ6w?e=nOL2nq) del proyecto 

**Criterios de aceptación**

- [x] Generación de la documentación del modelo de datos (diagrama de colecciones)
- [x] Generación del repositorio con el api crud (acompañamiento del líder técnico) 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Por favor realizar la documentación de la issue @JQuinteroC

**Comment by JQuinteroC** [comment]
![plan_trabajo_docente_crud](https://github.com/udistrital/sga_cliente/assets/21268124/ba9d226c-508d-46c1-bbdb-435ccc12fb95)

**Comment by JQuinteroC** [comment]
Se creo la API_CRUD en NestJS basado en el siguiente modelo 
![plan_trabajo_docente_crud](https://github.com/udistrital/sga_cliente/assets/21268124/5cdfb405-4a3a-4f43-a376-b69edbd9e1a4)
Como observaciones, se separo la pre-asignación, el plan docente y el consolidado y por parte de la carga asignada se manejaran lass actividades y las cargas lectivas en el mismo origen

**Comment by fabianbarreto02** [comment]
La issue es revisada y finalizada
