### ISSUE TITLE
Consulta de datos de inscripción para pregrado (Tag Informacion Basica), cuando ya exista el usuario en terceros - 24 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#128]
Se debe realizar la consulta de la información registrada en el api de terceros en los diferente tag de información de básica y formación académica, la issue  de cumplir con los siguientes items:

- [x] Verifica con el usuario de wso2 si existe información personal en el api de tercero y cargarla si encuentra.
- [x] Verifica con el usuario de wso2 si existe información caracteristica en el api de tercero y cargarla si encuentra.
- [x] Verifica con el usuario de wso2 si existe información cotacto en el api de tercero y cargarla si encuentra.
- [x] Verifica con el usuario de wso2 si existe información familiar en el api de tercero y cargarla si encuentra.
- [x] Verifica con el usuario de wso2 si existe informacion del registro del icfes en el api de inscripcion y cargarla si encuentra.
- [ ] Verifica con el usuario de wso2 si existe información universidad en el api de tercero y cargarla si encuentra.

Cambios a nivel de mid se desarrollan en la [issue](https://github.com/udistrital/sga_mid/issues/52)

SI DIos quiere termino esta semana, lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, tener en cuenta que la parte de formacion academica no se pudo realizar por que no se integro la parte desarrollada por sebastian con lo que fabian desarrollo, si se integro el tag de informacion familiar con el desarrollo, se espera revision por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica el desarrollo realizado, se da por finalizada la tarea.
