### ISSUE TITLE
Desarrollar registro del modelo de datos de colegios (realizado por el equipo CORE) con el formulario de datos de inscripción para pregrado (Tag Formacion academica) - 20 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#129]
Se debe ajustar el tag de formación académica en la inscripción tipo pregrado, por ajuste en la carga de los colegios provenientes del api tercero del equipo core, la issue debe cumplir con los siguientes requerimiento:

- [x]  Se debe ajustar el form donde se selecione la ubicacion del colegio y dependiendo si el colegio pertenece a Bogotá se debe cargar un select con los colegios registrados en la API de teceros.

- [x] Se debe consultar el tipo de colegio y se carge en un select o input bloqueado en colegios registrados en la API de teceros.

- [x] Cuando el colegio no este en la ciudad de Bogotá, se debe habilitar un campo input para el registro del nombre del colegio, y un selet con el tipo de colegio, Oficial y privado.

- [x] realizar el registro en el grupo de información con su información complementaria dedicado al registro  en formato json.

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Json Con colegio Nuevo
`{
    "Tercero": {
        "TerceroId": {
            "Id": 3725
        }
    },
    "InscripcionPregrado": {
        "Id": 0,
        "InscripcionId": {
            "Id": 1
        },
        "TipoIcfesId": {
            "Id": 1,
            "Nombre": "AC - Normal",
            "Descripcion": "Icfes Normal",
            "CodigoAbreviacion": "AC",
            "Activo": true,
            "NumeroOrden": 1,
            "FechaCreacion": "2019-12-06T13:59:46.413068Z",
            "FechaModificacion": "2019-12-06T13:59:46.413068Z"
        },
        "CodigoIcfes": "2018645hff",
        "TipoDocumentoIcfes": 1,
        "NumeroIdentificacionIcfes": 1,
        "AnoIcfes": 2018,
        "Activo": true,
        "Valido": true
    },
    "InfoComplementariaTercero": {
        "Id": 0,
        "TerceroId": 3725,
        "InfoComplementariaId": {
            "Id": 67,
            "Nombre": "Recién graduado",
            "CodigoAbreviacion": "Recién graduado",
            "Activo": true,
            "TipoDeDato": "",
            "GrupoInfoComplementariaId": {
                "Id": 14,
                "Nombre": "Semestres transcurridos sin estudiar",
                "Descripcion": "Semestres transcurridos sin estudiar",
                "CodigoAbreviacion": "Grupo_14",
                "Activo": true,
                "FechaCreacion": "2019-12-18 09:37:33.721409 +0000 +0000",
                "FechaModificacion": "2019-12-18 09:37:33.721409 +0000 +0000"
            },
            "FechaCreacion": "2019-12-18 09:37:33.72973 +0000 +0000",
            "FechaModificacion": "2019-12-18 09:37:33.72973 +0000 +0000"
        },
        "Dato": "\"Recién graduado\"",
        "Activo": true
    },
    "TerceroColegio": {
        "NombreCompleto": "Braulio",
        "TipoContribuyenteId": {
            "Id": 2
        },
        "Activo": false
    },
    "DireccionColegio": {
        "InfoComplementariaId": {
            "Id": 54
        },
        "Dato": "\"Calle 12 09345 \"",
        "Activo": true
    },
    "UbicacionColegio": {
        "InfoComplementariaId": {
            "Id": 92
        },
        "Dato": "681",
        "Activo": true
    }
}`

**Comment by fabianbarreto02** [comment]
Json colegio existente
{
    "InscripcionPregrado": {
        "Id": 0,
        "InscripcionId": {
            "Id": 1
        },
        "TipoIcfesId": {
            "Id": 1,
            "Nombre": "AC - Normal",
            "Descripcion": "Icfes Normal",
            "CodigoAbreviacion": "AC",
            "Activo": true,
            "NumeroOrden": 1,
            "FechaCreacion": "2019-12-06T13:59:46.413068Z",
            "FechaModificacion": "2019-12-06T13:59:46.413068Z"
        },
        "CodigoIcfes": "2018gdfs",
        "TipoDocumentoIcfes": 1,
        "NumeroIdentificacionIcfes": 1,
        "AnoIcfes": 2018,
        "Activo": true,
        "Valido": false
    },
    "InfoComplementariaTercero": [
        {
            "Id": 0,
            "TerceroId": null,
            "InfoComplementariaId": {
                "Id": 67,
                "Nombre": "Recién graduado",
                "CodigoAbreviacion": "Recién graduado",
                "Activo": true,
                "TipoDeDato": "",
                "GrupoInfoComplementariaId": {
                    "Id": 14,
                    "Nombre": "Semestres transcurridos sin estudiar",
                    "Descripcion": "Semestres transcurridos sin estudiar",
                    "CodigoAbreviacion": "Grupo_14",
                    "Activo": true,
                    "FechaCreacion": "2019-12-18 09:37:33.721409 +0000 +0000",
                    "FechaModificacion": "2019-12-18 09:37:33.721409 +0000 +0000"
                },
                "FechaCreacion": "2019-12-18 09:37:33.72973 +0000 +0000",
                "FechaModificacion": "2019-12-18 09:37:33.72973 +0000 +0000"
            },
            "Dato": "\"Recién graduado\"",
            "Activo": true
        }
    ],
    "dataColegio": {
        "Id": 182,
        "NombreCompleto": "COLEGIO AQUILEO PARRA (IED)",
        "PrimerNombre": "",
        "SegundoNombre": "",
        "PrimerApellido": "",
        "SegundoApellido": "",
        "LugarOrigen": 0,
        "FechaNacimiento": null,
        "Activo": true,
        "TipoContribuyenteId": {
            "Id": 2,
            "Nombre": "PERSONA JURIDICA",
            "Descripcion": "",
            "CodigoAbreviacion": "P_JURIDICA",
            "Activo": true,
            "FechaCreacion": "2019-12-18 09:37:30.610878 +0000 +0000",
            "FechaModificacion": "2019-12-18 09:37:30.610878 +0000 +0000"
        },
        "FechaCreacion": "2019-12-18 09:37:34.147907 +0000 +0000",
        "FechaModificacion": "2019-12-18 09:37:34.147907 +0000 +0000",
        "UsuarioWSO2": ""
    }
}

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue las configuraciones del mid se realizaron en el [commit](https://github.com/udistrital/sga_mid/commit/239a86557144b09914657fe122a16a3df1e5afe6), esta tarea tardo mas de lo planeado pues, no se habia definido el manejo de colegios afuera de bogota, y en reunion con el core y arquitecto se definio el lineamiento, lo que significo realizar tareas adicionales no calculadas, como el manejo diferente de colegios existentes y colegios no creados en terceros, se espera revision por parte de @mafeave

**Comment by mafeave** [comment]
Revisar que cuando se carga el select de colegios para Bogotá, y luego se cambia la ubicación a un municipio que no tenga colegios, se sigue mostrando el select: 
![Captura de pantalla de 2019-12-23 09-11-03](https://user-images.githubusercontent.com/14035745/71362633-a09fb580-2564-11ea-8fe7-208ca8e918ec.png)

Para ajustes futuros: 
- agregar filtro para búsqueda del colegio, tener en cuenta que un colegio puede tener varias sedes para Bogotá, lo cual afecta la localidad relacionada
- agregar una opción de agregar un nuevo Colegio cuando no se encuentre en el select, se habilitarían los campos de Nombre, Tipo, Dirección y Localidad (para Bogotá).
- crear formulario en el que se verifique la información de un nuevo colegio registrado, lo cual se haría desde Admisiones.

**Comment by fabianbarreto02** [comment]
Se realiza ajuste sugerido por @mafeave

**Comment by mafeave** [comment]
Se verifica ajuste para habilitar que se muestre el select, se da por finalizada la tarea.
