### ISSUE TITLE
Incluir el reporte "Listado de aspirantes a un proyecto", en el Cliente del SGA.

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#13]
Incluir en el cliente del SGA el reporte "Listado de aspirantes a un proyecto" creado en https://github.com/udistrital/inscripcion_crud/issues/16.

**Comment by JuanPiedrahita** [comment]
El inicio del desarrollo de este issue esta sujeto a la creación del reporte, para hacer seguimiento del mismo por favor ir a https://github.com/udistrital/inscripcion_crud/issues/16.

**Comment by JuanPiedrahita** [comment]
Se finaliza el issue https://github.com/udistrital/inscripcion_crud/issues/16, por lo que se dará continuidad a este, se espera información de consumo de sdk de spago de parte de @mafeave .

**Comment by mafeave** [comment]
Tener en cuenta el siguiente componente: https://github.com/rajeevmc77/KnowageReportComponent, con el cual se incluye el SDK de Knowage

**Comment by JuanPiedrahita** [comment]
Se agrega evidencia de ejecución de la tarea y se da por temrinada, falta la plantilla par ael reporte.
![imagen](https://user-images.githubusercontent.com/25555966/64433550-51507a80-d084-11e9-8a77-fa5d53e48324.png)

**Comment by mafeave** [comment]
Se verifica carga del reporte en el cliente. Se da por finalizada la tarea.
