### ISSUE TITLE
Ajuste de reporte de planeación evaluación por contingencia 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1342]
Se requiere realizar el Ajuste de reporte de planeación evaluación por contingencia 

**Sub Tareas**

- [x] Se debe ajustar el el controlador de generación del reporte de evaluación debe poder capturar y permitir la generación con campos vacíos como indicador, numerador, denominador 
- [x] Ajustar tipo de dato en el campo brecha si es numerito o porcentaje 
- [x] Ajustar la combinación de celdas para la brechas de forma individual y celda Cumplimiento por actividad combinar según la actividad 

**Criterios de aceptación**

- [x] Pruebas de forma local 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Test local
![Captura desde 2023-07-10 12-09-05](https://github.com/udistrital/sga_cliente/assets/31144689/501bb8c9-e068-4060-8f79-8e26409d3acc)

**Comment by fabianbarreto02** [comment]
Se da por revisado la issue y se realiza el proceso de despligue en producción
