### ISSUE TITLE
Revisar funcionalidad y ajustar (si es necesario) registro de eventos por proyecto - 14 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#135]
Se debe realizar el análisis sobre el modulo de eventos del cliente, por cambios en el modelo de eventos efectuados por el core, la siguiente figura expone el modelo nuevo de eventos:
![2019-12-23](https://user-images.githubusercontent.com/43799065/71455602-ba5b1b80-2763-11ea-98c4-3c9ceb8bcc9f.jpg)

La issue debe cumplir con los siguientes requerimiento:

- [x]  Se debe revisar si es necesario realizar ajuste a nivel cliente para el nuevo modelo.
- [x] Se debe revisar si es necesario realizar ajuste a nivel API MID para el nuevo modelo.
- [x] Verificar el funcionamiento de los ajustes.

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de análisis y ajuste

**Comment by fabianbarreto02** [comment]
Se tiene en cuenta la ultima versión del modelo de eventos para el análisis

![eventoV8](https://user-images.githubusercontent.com/43799065/71455877-0195dc00-2765-11ea-9949-6b17cd610fa2.png)

**Comment by fabianbarreto02** [comment]
Ajuste a nivel de mid en el [Commit](https://github.com/udistrital/sga_mid/commit/b3ec60080a4e166e744c92614e0bbb194e9d0a43)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea tener en cuenta los siguientes observaciones 

- Cambiar variables de entorno en el ambiente de test del api de eventos tener en cuenta que es "v2".

- En el api de eventos se encontraron dos anomalias que se solicitad estudiar, la primera al momento de crear un tipo de evento la relación a la tabla tipo_recurrencia_id tienen la propiedad uq, lo que implica crear un tipo de recurrencia unica para cada tipo de evento, la segunda observación se que se tienen que crear un tipo_evento como "Inscripción" por cada proyecto ps en cada registro de tipo_evento relaciona el id de la dependencia y tiene que existir con antelación para poder registrar el evento.

- Tener en cuenta que el registro y la consulta de los evento se atan al id del tercero que lo realiza, para consulta se consulta con el id registrado en terceros.

Se espera revisión por parte de lider técnico @mafeave

**Comment by mafeave** [comment]
Ajustar la función GetEvento() del mid para que se verifique que lo retornado por la petición tr_evento, ya que solo se verifica que el resultado sea distinto de null, pero no se verifica el caso de que el resultado sea un JSON vacio, ver: https://github.com/udistrital/sga_mid/blob/dev/controllers/evento.go#L191

**Comment by mafeave** [comment]
Se hace solicitud a @AlaskaRising para eliminar la restricción unique del tipo_recurrencia en la tabla de tipo_evento

**Comment by mafeave** [comment]
Se verifica la carga de eventos relacionados al tercero que ingresa al sistema
![Captura de pantalla de 2019-12-30 20-14-08](https://user-images.githubusercontent.com/14035745/71606675-07166c00-2b41-11ea-908c-2f58d716f5df.png)

Sin embargo se sugiere evaluar con el equipo de trabajo lo que implicaría en caso de que el usuario encargado ya no esté vinculado a la universidad,¿cómo se haría la gestión de eventos en ese caso?

**Comment by mariaalejandra9404** [comment]
> 
> 
> Se hace solicitud a @AlaskaRising para eliminar la restricción unique del tipo_recurrencia en la tabla de tipo_evento

Buenas, ya se eliminó la uq y se realizó despliegue, por favor verificar. :)

**Comment by fabianbarreto02** [comment]
Se revisa api, se espera revisión por parte de @mafeave

**Comment by fabianbarreto02** [comment]
se realiza ajuste sugerido por @mafeave  revisar [commit](https://github.com/udistrital/sga_mid/commit/8ae4a29df41bc23bd36aa0a83b0cfb4c09d976e9)

**Comment by mafeave** [comment]
Se verifica funcionalidad, sin embargo se propone a futuro modificar la forma del registro de eventos, para que en el formulario se cargue el nivel de formación (pregrado/posgrado) y se pueda hacer un check con las carreras a las cuales se les va a habilitar el evento seleccionado para el periodo académico.
