### ISSUE TITLE
Creación de informe de pruebas piloto por solicitud de proyecto académico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1356]
Se requiere realizar la Creación de informe de pruebas piloto por solicitud de proyecto académico

**Sub Tareas**

- [x] Se debe crear el documento con la información de las pruebas piloto desarrollado durante la ejecución del sistema de gestión académico en el entorno de producción 

**Criterios de aceptación**

- [x] Incluir responsables del proyecto
- [x] Incluir las actas de soporte de las pruebas piloto
- [x] Incluir Proyectos académicos en la prueba piloto
- [x] Incluir el reporte por periodo del uso del sistema 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
Se crea documento con la información respectiva a las pruebas piloto con programas de posgrado
- [Document](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EVijmEEHVGRGigBP4NPKApEBidb_xUTqsmJxwNPBxoPqfQ?e=i6PXDO)o

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
