### ISSUE TITLE
Desarrollar select de la carrera - 7 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#136]
Teniendo en cuenta los ajustes realizados en #135, se debe desarrollar la carga del select de proyecto en el componente de inscripción con los proyectos que cuenten con el evento de inscripcion activo, la issue debe cumplir con los siguientes requerimientos:

- [x]  Cargar el select con proyectos activos con el evento de inscripcion.

- [x] Bloquear funciones de tags hasta que se seleccione el proyecto.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se da Inicio a la issue

**Comment by fabianbarreto02** [comment]
Ajustes a nivel de mid se realizan en el [commit](https://github.com/udistrital/sga_mid/commit/63f0c347d7fbf7a8bdbebe127e2b6c7afdb58237)

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue, se realiza la carga del select de los proyectos académicos que tiene relacionado el evento padre de inscripción en la facultad de ingeniera para pruebas para el caso el id 5 en el endpoint calendario_evento en el api de eventos, se realizo un metodo en el API MID para organizar la data para el select, se espera revisión técnica por parte de @mafeave

**Comment by mafeave** [comment]
Se realiza el despliegue y se verifica la carga de carreras para las que el evento de inscripción esté habilitado
![Captura de pantalla de 2019-12-30 20-39-28](https://user-images.githubusercontent.com/14035745/71607088-89ecf600-2b44-11ea-91d1-864251e7d4b2.png)

Evaluar con el equipo de trabajo: ¿el evento principal debería estar relacionado al tipo de dependencia (pregrado/posgrado)?. Por otra parte, las carreras se deberían cargar de acuerdo al select del tipo de inscripción
