### ISSUE TITLE
Diseñar el mockup de gestionar horario para el modulo de horarios con los requerimientos levantados

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1361]
Se requiere realizar el Diseñar el mockup de gestionar horario para el modulo de horarios con los requerimientos levantados

**Sub Tareas**

- [x] Creación del mockup con la herramienta draw.io con los avances realizado en la issue #1340  para el sub modulo de gestión de horarios con los requerimientos levantados 

**Criterios de aceptación**

- [x] Documentación con la herramienta draw.io

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
De acuerdo a la revisión documental, del sistema actual en producción (condor) y de sesiones realizadas con usuarios funcionales, se plantea el siguiente diseño: 
- [Mockup gestión de horarios](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EabLBnMWs_ZPtOR2zy9iDroBdBoBwH3XhrYML_fsLM9l4w?e=Dkp8xu) diagrama en DRAW.IO y [PDF](https://udistritaleduco-my.sharepoint.com/:b:/g/personal/computo_udistrital_edu_co/EX6eJqZ2efJGt9MjDAtQiEcBouk3O-ky02Nw6xTUbr2UBQ?e=pO4mPO)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
