### ISSUE TITLE
Proceso de validación del mockups para el modulo de  gestión de horarios 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1368]
Se requiere realizar el Proceso de validación del mockups para el modulo de  gestión de horarios  desarrollado en la issue #1361 

**Sub Tareas**

- [x] Realizar reunión con usuario para la validación del mockup

**Criterios de aceptación**

- [x] Acta de reunión con observaciones o aprobación del mockup 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
Se realiza sesión virtual con usuarios para buscar la validación de mockups para la gestión de horarios:
- [Documento soporte de la sesión](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EoTgm6lF6xFOqQumiE7CdUQBZ1Nmk1p0JJLGhI3Sj8VM6A?e=yfZZaV)

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
