### ISSUE TITLE
Prueba de concepto para API CRUD con Python y MongoDB

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1370]
Se requiere realizar la prueba de concepto para API CRUD con Python y MongoDB

**Sub Tareas**

- [x] Documentar y consultar para creación de api crud mediante tecnologias serveless, python, SAM y mongo Db, tener como guia la siguiente documentación.

- https://medium.com/hackernoon/building-a-serverless-microservice-crud-restful-api-with-mongodb-6e0316efe280
- https://www.youtube.com/watch?v=Xl2ex9EA6s4
- https://www.mongodb.com/developer/products/atlas/serverless-development-lambda-atlas/
- https://stackoverflow.com/questions/75591618/connect-mongodb-from-aws-lambda-python-using-iam

- [x] Crear api Crud de pruebas en entorno local para la consulta de la siguiente colección 

`{
    "espacio_academico_id": 123456,
    "justificacion": "Justificación del espacio académico",
    "objetivo_general": "Objetivo de la asignatura",
    "objetivos_especificos": [ "obj 1", "obj 2", "obj 3" ],
    "resultados_aprendizaje": [ "res 1", "res 2", "res 2" ],
    "articulacion_resultados_aprendizaje": "text",
    "contenido": {
        "descripcion": "text",
        "temas": [
            { "nombre": "Algebra de matrices", "subtemas": [ { "nombre": "Multiplicacion" } ] },
            { "nombre": "Fusión de imagenes.", "subtemas": [ { "nombre": "Transformacion" } ] }
        ]
    },
    "estrategias": [
        { "nombre": "metodologia", "descripcion": "text", "pertinencia": "text", "articulacion_ra": "text" }
    ],
    "evaluacion": {
        "descripcion": "text",
        "evaluaciones": [
            { "nombre": "text", "estrategia": "text", "momento": "text", "porcentaje": 10 }
        ]
    },
    "bibliografia": [ { "tipo": "básicas", "referencias": [ "text", "text" ] } ],
    "seguimiento": [ { "elaboracion": "nombre", "revision": "nombre", "fecha": "12/05/2022" } ]
}

`

- [x] Realizar reunión con equipo de desarrollo para compartir los conocimientos adquiridos 

**Criterios de aceptación**

- [x] Creación de api en entorno local
- [x] Realización de reunión 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Material útil:

### Dependencias / librerías
- https://diegooo.com/windows-paquetes-python-en-lambda/#:~:text=Navegue%20a%20la%20funci%C3%B3n%20en,que%20desea%20adjunte%20esta%20capa

### Manejo de flujo de llamado a funciones
- https://docs.aws.amazon.com/es_es/step-functions/latest/dg/welcome.html

**Comment by edwargl7** [comment]
## Test en la nube

### Get All
![image](https://github.com/udistrital/sga_cliente/assets/50187485/405db802-33c5-410e-bd3b-b615f8c1050d)

### Get one
![image](https://github.com/udistrital/sga_cliente/assets/50187485/89f952a5-1268-4ab8-a126-b37f3fe87929)

### Post
![image](https://github.com/udistrital/sga_cliente/assets/50187485/0c39488b-2b42-4dce-bbb3-01e22ef755ae)

### Put
![image](https://github.com/udistrital/sga_cliente/assets/50187485/3a6b376b-8c2c-42f2-960f-f7df9151f57a)

### Delete (logic)

**Comment by fabianbarreto02** [comment]
Se realiza el despliegue en un entorno de pruebas y se realizan las pruebas de la funciones lambdas y del api gateway, se presenta al equipo los avances y se espera a la realización de reunión con el equipo de condor y seguridad para continuar con el desarrollo del componente.
