### ISSUE TITLE
Generación del Premockup para la creación de syllabus y la consulta de syllabus para estudiantes, programa y coordinación 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1375]
Se requiere realizar la Generación del Premockup para la creación de syllabus y la consulta de syllabus para estudiantes, programa y coordinación 

**Sub Tareas**

- [x] Creación del mockup con la herramienta draw.io para la creación de syllabus y la consulta de syllabus para estudiantes, programa y coordinación 

**Criterios de aceptación**

- [x]  Documentación con la herramienta draw.io

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
Actualización mockup en el formato requerido:

- [Mockup v5](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYG-D3kpbhpGlQQyjn_XSyIBD-d8f42xPumQ-C5EQClU2Q?e=ndYpy3)
- [Acta sesión virtual realizada](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/Elo-M5E8cXNMua4z45go_kQBMcCoyYJPT3dstrVH84XYmA?e=AT6akv)

**Comment by fabianbarreto02** [comment]
Se da  por finalizada la issue
