### ISSUE TITLE
Creación de componente principal de syllabus y nuevo syllabus según mockups establecidos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1394]
Se requiere realizar la Creación de componente principal de syllabus y nuevo syllabus según mockups establecidos 

**Sub Tareas**

- [x] Creación del componente principal según mockups 

![image](https://github.com/udistrital/sga_cliente/assets/43799065/1c36b139-4275-4478-965a-8f5db5ca02e7)

![image](https://github.com/udistrital/sga_cliente/assets/43799065/7227da6d-bafa-4e70-ae70-23e290a1b3e1)

- [x] Creación del componente nuevo syllabus según mockups 

![image](https://github.com/udistrital/sga_cliente/assets/43799065/dd02e51f-810e-4804-a02f-a7e2c8118496)

![image](https://github.com/udistrital/sga_cliente/assets/43799065/a6d85ae6-5fea-44d8-857a-dbdcb0a57d52)
![image](https://github.com/udistrital/sga_cliente/assets/43799065/d1f4bf5f-a199-4af3-bbaa-8f40c3e3363b)

Mocukp disponible (herramiento draw.io) en https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/ETtJddQzB2tLuA-vZhk9hi4BY5JTcFSZ7evnzYCIy1xVaQ?e=4hnEVO  

**Criterios de aceptación**

- [x] Implementación de componentes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
[utestsecdecanatura](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EYG-D3kpbhpGlQQyjn_XSyIBD-d8f42xPumQ-C5EQClU2Q?e=sILSTP)

**Comment by JuanCamiloMartinezLopez** [comment]
Se realiza el maquetado inicial 
![image](https://github.com/udistrital/sga_cliente/assets/42418412/db6d1f3d-35d8-439a-97b5-11aeb4bef3a8)
![image](https://github.com/udistrital/sga_cliente/assets/42418412/cee998d2-54c3-49c1-9a89-233e86f64bba)
![image](https://github.com/udistrital/sga_cliente/assets/42418412/54ab2577-9c3e-4cdc-9920-b4b1e700057c)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue.
