### ISSUE TITLE
Levantamiento de requerimientos para el modulo de preinscripción de espacios academicos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1404]
Se requiere realizar el Levantamiento de requerimientos para el modulo de preinscripción de espacios académicos

**Sub Tareas**

- [x] Realizar el levantamiento para el modulo de preinscripción de espacios académicos
- [x] Establecer un pre mockup para el modulo de preinscripción de espacios académicos

**Criterios de aceptación**

- [x] Levantamiento de requerimientos
- [x] Pre mockup

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by cearomeroc01** [comment]
Se realiza el levantamiento de información, normativa y sesiones con usurarios, se presenta el diseño inicial para confirmar el flujo del proceso; se crea el diseño correspondiente relacionado a continuación:
— [Mockup inicial](https://udistritaleduco-my.sharepoint.com/:u:/g/personal/computo_udistrital_edu_co/EUkVxEFyYbZHig4ahCiz2uwB26w20DfFSWWlPl3aznGQbA?e=Th8L4e)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la isusse
