### ISSUE TITLE
Registro inscripción de pregrado (20 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#141]
Se debe desarrollar toda la funcionalidad para formalizar el registro de inscripción de un aspirante para poder realizar el reporte de icfes, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar la funcionalidad en el cliente para el registro de la información a las APIS de terceros.

- [x] Realizar funcionalidad para el registro de la información necesaria en la API de inscripción para el tipo de inscripcion de pregrado.

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Ajsutes a nivel de MID en el [Commit](https://github.com/udistrital/sga_mid/commit/412d4e8f633057b58e5b1ffdbd3c259239809319)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue se espera revisión por parte de lider técnica @mafeave

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 7 de enero de 2020, se realizan las siguientes observaciones:

- [ ] Revisar el tipo de inscripción y el programa, ya que es necesario diligenciarlo doble vez para que lo tome.
- [ ] Se está demorando en cargar todos los campos, revisar los reducers del former, revisar sentencias hidden por ng*if.
- [ ] Ajustar los mensajes de los errores.

**Comment by mafeave** [comment]
Observaciones ajustadas en los issues relacionados, se da por finalizada la tarea.
