### ISSUE TITLE
Funcionalidad para consulta, creación y edición a syllabus con modelo de datos propio

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1416]
Se requiere realizar la Funcionalidad para consulta, creación y edición a syllabus con modelo de datos propio

**Sub Tareas**

- [x] Crear funcinalidad a nivel cliente para el la carga de la información del componente Nuevo Syllabus
![image](https://github.com/udistrital/sga_cliente/assets/43799065/d3491333-7035-4db0-9d28-fbfb3ac073b9)

- [x] Crear funcionalidad para la carga de información del componente Identificación  del espacio académico
![image](https://github.com/udistrital/sga_cliente/assets/43799065/ce2994c5-97db-4ccd-83b7-701cb3156da4)

con el servicio 

http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/academica_pruebas/espacios_academicos_proyecto/{pensum}/{cra_cod}/{asi_cod}

- [x] Crear funcinalidad para el almacenamiento de la información del syllabus Sugerencias de saberes y conocimientos previos, Justificación del espacio académico, Objetivos del espacio académico (general y específicos), Propositos de formación y de aprendizaje (PFA) del espacio académico, Contenidos temáticos, Estrategias de enseñanza que favorecen el aprendizaje, Evaluación, Medios y recursos educativos, Practicas académicas - salidas de campo y Bibliografía con el servicio definido tener presente el modelo definido 

`{
    "espacio_academico_id": 123456,
    "justificacion": "Justificación del espacio académico",
    "objetivo_general": "Objetivo de la asignatura",
    "objetivos_especificos": [ "obj 1", "obj 2", "obj 3" ],
    "resultados_aprendizaje": [ "res 1", "res 2", "res 2" ],
    "articulacion_resultados_aprendizaje": "text",
    "contenido": {
        "descripcion": "text",
        "temas": [
            { "nombre": "Algebra de matrices", "subtemas": [ { "nombre": "Multiplicacion" } ] },
            { "nombre": "Fusión de imagenes.", "subtemas": [ { "nombre": "Transformacion" } ] }
        ]
    },
    "estrategias": [
        { "nombre": "metodologia", "descripcion": "text", "pertinencia": "text", "articulacion_ra": "text" }
    ],
    "evaluacion": {
        "descripcion": "text",
        "evaluaciones": [
            { "nombre": "text", "estrategia": "text", "momento": "text", "porcentaje": 10 }
        ]
    },
    "bibliografia": [ { "tipo": "básicas", "referencias": [ "text", "text" ] } ],
    "seguimiento": [ { "elaboracion": "nombre", "revision": "nombre", "fecha": "12/05/2022" } ]
}
`

- [x] Crear funcionalidad de consulta del componente de syllabus 

- [x] Crear funcionalidad para la edición de syllabus 

**Criterios de aceptación**

- [x] Implementación de funcionalidad de tabla
- [x] Implementación de funcionalidad de creación 
- [x] Implementación de funcionalidad de syllabus
- [x] Implementación de funcionalidad de edición

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
GET ONE

http://qy23a0p1xc.execute-api.us-east-1.amazonaws.com/Prod/syllabus/64c809c6d93d54c877a202d7

**Comment by fabianbarreto02** [comment]
GET ALL

http://qy23a0p1xc.execute-api.us-east-1.amazonaws.com/Prod/syllabus?query...

**Comment by fabianbarreto02** [comment]
PUT

curl --location --request PUT '[http://qy23a0p1xc.execute-api.us-east-1.amazonaws.com/Prod/syllabus/64c809c6d93d54c877a202d7'](http://qy23a0p1xc.execute-api.us-east-1.amazonaws.com/Prod/syllabus/64c809c6d93d54c877a202d7%27) \
--header 'Content-Type: application/json' \
--data-raw '{
   "espacio_academico_id":9875464,
   "justificacion":"Justificación del espacio académico",
   "objetivo_general":"Objetivo de la asignatura",
   "objetivos_especificos":[
      "obj 1",
      "obj 2",
      "obj 3"
   ],
   "resultados_aprendizaje":[
      "res 1",
      "res 2",
      "res 2"
   ],
   "articulacion_resultados_aprendizaje":"text",
   "contenido":{
      "descripcion":"text",
      "temas":[
         {
            "nombre":"Algebra de matrices",
            "subtemas":[
               {
                  "nombre":"Multiplicacion"
               }
            ]
         },
         {
            "nombre":"Fusión de imagenes.",
            "subtemas":[
               {
                  "nombre":"Transformacion"
               }
            ]
         }
      ]
   },
   "estrategias":[
      {
         "nombre":"metodologia",
         "descripcion":"text",
         "pertinencia":"text",
         "articulacion_ra":"text"
      }
   ],
   "evaluacion":{
      "descripcion":"text",
      "evaluaciones":[
         {
            "nombre":"text",
            "estrategia":"text",
            "momento":"text",
            "porcentaje":10
         }
      ]
   },
   "bibliografia":[
      {
         "tipo":"básicas",
         "referencias":[
            "text",
            "text"
         ]
      }
   ],
   "seguimiento":[
      {
         "elaboracion":"nombre",
         "revision":"nombre",
         "fecha":"12/05/2022"
      }
   ]
}'

**Comment by fabianbarreto02** [comment]
POST

curl --location --request PUT '[http://qy23a0p1xc.execute-api.us-east-1.amazonaws.com/Prod/syllabus'](http://qy23a0p1xc.execute-api.us-east-1.amazonaws.com/Prod/syllabus%27) \
--header 'Content-Type: application/json' \
--data-raw '{
   "espacio_academico_id":9875464,
   "justificacion":"Justificación del espacio académico",
   "objetivo_general":"Objetivo de la asignatura",
   "objetivos_especificos":[
      "obj 1",
      "obj 2",
      "obj 3"
   ],
   "resultados_aprendizaje":[
      "res 1",
      "res 2",
      "res 2"
   ],
   "articulacion_resultados_aprendizaje":"text",
   "contenido":{
      "descripcion":"text",
      "temas":[
         {
            "nombre":"Algebra de matrices",
            "subtemas":[
               {
                  "nombre":"Multiplicacion"
               }
            ]
         },
         {
            "nombre":"Fusión de imagenes.",
            "subtemas":[
               {
                  "nombre":"Transformacion"
               }
            ]
         }
      ]
   },
   "estrategias":[
      {
         "nombre":"metodologia",
         "descripcion":"text",
         "pertinencia":"text",
         "articulacion_ra":"text"
      }
   ],
   "evaluacion":{
      "descripcion":"text",
      "evaluaciones":[
         {
            "nombre":"text",
            "estrategia":"text",
            "momento":"text",
            "porcentaje":10
         }
      ]
   },
   "bibliografia":[
      {
         "tipo":"básicas",
         "referencias":[
            "text",
            "text"
         ]
      }
   ],
   "seguimiento":[
      {
         "elaboracion":"nombre",
         "revision":"nombre",
         "fecha":"12/05/2022"
      }
   ]
}'

**Comment by fabianbarreto02** [comment]
http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/academica_pruebas/detalle_espacio_academico/307/375/1

**Comment by edwargl7** [comment]
Actualizados endpoints CRUD Syllabus, se adjunta JSON con la colección de Postman con el body y query params necesarios para cada petición, junto con ejemplos de respuesta de cada petición.

![image](https://github.com/udistrital/sga_cliente/assets/50187485/d4b6eac3-4c0d-46f1-b5f3-83a39774ea90)

**Comment by edwargl7** [comment]
Desplegados los cambios
![image](https://github.com/udistrital/sga_cliente/assets/50187485/8deb9c55-928a-4077-917d-4a2ffb0a5717)

**Comment by fabianbarreto02** [comment]
https://autenticacion.portaloas.udistrital.edu.co/apioas/syllabus_crud/v1

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue.
