### ISSUE TITLE
Funcionalidad creación consulta y generación reporte syllabus formato pdf mediante función lambda 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1417]
Se requiere realizar la Funcionalidad creación consulta y generación reporte syllabus formato pdf mediante función lambda 

**Sub Tareas**

- [x] Realizar consulta para la información de proyecto académico son el servicio definido 

![image](https://github.com/udistrital/sga_cliente/assets/43799065/f70d3a10-3530-446a-bc2f-4ec60f4781b2)

[http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/academica_pruebas/espacios_academicos_proyecto/{pensum}/{cra_cod}/{asi_cod}](http://busservicios.intranetoas.udistrital.edu.co:8282/wso2eiserver/services/academica_pruebas/espacios_academicos_proyecto/%7Bpensum%7D/%7Bcra_cod%7D/%7Basi_cod%7D)

- [x] Traer consulta de la información del pensum del proyecto académico particular 
- [x] Crear formato definido en el pdf  para la creación del reporte 
[Formato Syllabus para institucionalizar VF 12 DE JULIO.pdf](https://github.com/udistrital/sga_cliente/files/12449101/Formato.Syllabus.para.institucionalizar.VF.12.DE.JULIO.pdf)

- [x] La función debe recibir como parámetros el espacio académico especifico para las consultas 
- [x] La función lambda debe devolver en el response el reporte pdf con el formato defino en formato base 64 para ser visto desde el cliente 

**Criterios de aceptación**

- [x] Implementación función lambda en lenguaje Python para la generación del reporte 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
[Formato Syllabus para institucionalizar VF 12 DE JULIO.xlsx](https://github.com/udistrital/sga_cliente/files/12456284/Formato.Syllabus.para.institucionalizar.VF.12.DE.JULIO.xlsx)

**Comment by edwargl7** [comment]
Creada plantilla del documento.
[out_2.pdf](https://github.com/udistrital/sga_cliente/files/12556090/out_2.pdf)

**Comment by edwargl7** [comment]
Renderizado del html con valores de prueba (se dejan algunos booleanos para observar el comportamiento).
[out_2.pdf](https://github.com/udistrital/sga_cliente/files/12570897/out_2.pdf)

**Comment by edwargl7** [comment]
Resultado luego de la instalación de las dependencias requeridas en la lambda.
[Prueba_plantilla_syllabus_weasyprint54.pdf](https://github.com/udistrital/sga_cliente/files/12696695/Prueba_plantilla_syllabus_weasyprint54.pdf)

**Comment by edwargl7** [comment]
Resultado usando el sga_mid.
[descarga (1).pdf](https://github.com/udistrital/sga_cliente/files/12707705/descarga.1.pdf)

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se despliega en entorno de pruebas y se da por finalizada la issue
