### ISSUE TITLE
Reporte ICFES (12 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#142]
Se debe desarrollar el reporte de los de los registros SPN con los aspirantes por carrera, la issue debe cumplir con los siguientes requerimientos:

- [x] El reporte se desarrollara apartir del desarrollos anteriores y debera tener la siguiente informacion: tipo de documento, documento, nombre completo y SNP.

- [x] Debera ser integrado el reporte al cliente

Lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se anexan lo archivos fuentes del reporte realizado con la Herramienta SpagoBI
[Carpeta](https://drive.google.com/open?id=1Dko8M0aPS0P7pdGkPKFM7sofkWsWv79N)

**Comment by fabianbarreto02** [comment]
Se finaliza la tarea de reportes del registro SNP Icfes por proyecto curricular y periodo, tener en cuenta que solo existen datos de prueba con la siguiente consulta:

- Proyecto: Ingeniera Electronica
-Periodo: 2019-2

Se anexa imagen de referencia 

![Captura de Pantalla 2020-01-04 a la(s) 6 51 36 p  m](https://user-images.githubusercontent.com/43799065/71772998-479c2e00-2f23-11ea-8618-cc293022a249.png)

Pendiente de revisión por parte de lider técnica: @mafeave

**Comment by mafeave** [comment]
Se hace despliegue de los commits y se verifica la funcionalidad del reporte.
Se da por finalizada la tarea.
