### ISSUE TITLE
Funcionalidad para la creación de versión syllabus, consulta y edición a syllabus 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1422]
Se requiere realizar la Funcionalidad para la creación de versión syllabus, consulta y edición a syllabus 

**Sub Tareas**

- [x] Ajustar colección del syllabus para la relación de syllabus padre (nombre campo: syllabus_padre_id, no obligatorio) para la relación de syllabus entre si ( padre versión anterior si el campo esta vacío no tiene versión)

- [x] Crear función lambda para la creación de syllabus hijo, para esto la función debe recibir el id del syllabus padre de donde se parte  (registro campo syllabus_padre_id) y el body con todos los parámetros del syllabus hijo, también esta misma función debe inactivar el registro (campo activo) del syllabus padre.
- [x]   Crear función lambda de consulta general de syllabus hijos mediante el parámetro del id del syllabus padre, la consulta debe traer todas las versiones de los syllabus, debe organizar el arbol de id entre syllabus, el response solo respondería la relación de id con el orden entre syllabus. 

**Criterios de aceptación**

- [ ] Implementación función de creación 
- [ ] Implementación función de consulta

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Test

Despliegue de versionado correctamente:
![image](https://github.com/udistrital/sga_cliente/assets/50187485/48007f99-99d8-4287-84af-d25f2717e339)
![image](https://github.com/udistrital/sga_cliente/assets/50187485/73785323-d1fa-4e1e-ba87-298d297c750c)

### Endpoints actualizados.

- Body para crear versión de syllabus

`{
        "espacio_academico_id": 123456,
        "syllabus_code": "1fe44814-2525-4f34-bdaa-0a5092c33f14",
        "proyecto_curricular_id": 1,
        "plan_estudios_id": 1,
        "justificacion": "Justificación del espacio académico",
        "objetivo_general": "Objetivo de la asignatura",
        "objetivos_especificos": [
            "obj 1",
            "obj 2",
            "obj 3",
            "obj 4"
        ],
        "resultados_aprendizaje": [
            "res 1",
            "res 2",
            "res 2"
        ],
        "articulacion_resultados_aprendizaje": "text",
        "contenido": {
            "descripcion": "text",
            "temas": [
                {
                    "nombre": "Algebra de matrices",
                    "subtemas": [
                        {
                            "nombre": "Multiplicacion"
                        }
                    ]
                },
                {
                    "nombre": "Fusión de imagenes.",
                    "subtemas": [
                        {
                            "nombre": "Transformacion"
                        }
                    ]
                }
            ]
        },
        "estrategias": [
            {
                "nombre": "metodologia",
                "descripcion": "text",
                "pertinencia": "text",
                "articulacion_ra": "text"
            }
        ],
        "evaluacion": {
            "descripcion": "text",
            "evaluaciones": [
                {
                    "nombre": "text",
                    "estrategia": "text",
                    "momento": "text",
                    "porcentaje": 10
                }
            ]
        },
        "bibliografia": [
            {
                "tipo": "básicas",
                "referencias": [
                    "text",
                    "text"
                ]
            }
        ],
        "seguimiento": [
            {
                "elaboracion": "nombre",
                "revision": "nombre",
                "fecha": "12/05/2022"
            }
        ],
        "activo": true
    }`

-  El endpoint de get one debe pasarse como parámetro el syllabus code

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
