### ISSUE TITLE
Funcionalidad de almacenamiento de documentos soportes para syllabus padres y versiones 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1425]
Se requiere realizar la Funcionalidad de almacenamiento de documentos soportes para syllabus padres y versiones 

**Sub Tareas**

- [x] Crear funcionamiento y servicio para el consumo del gestor documentar para el almacenacimiento de los documentos soportes del componente de Seguimiento y actualización del Syllabus

![image](https://github.com/udistrital/sga_cliente/assets/43799065/35e81af4-1b86-4766-9e19-47969ef910da)

Tener presente el flujo implementado en el cliente de SGA

- [x] Implementar funcionalidad para el almacenamiento, consulta y edición  de la información del documento (id documento_id), fechas, numero de actas y vigencia, esta información se debe almacenar en el campo seguimiento en formato json cada información se almacena como un campo en el json

![image](https://github.com/udistrital/sga_cliente/assets/43799065/ec59abf9-a337-42fd-b4c1-6c3d0004c6d9)
 

**Criterios de aceptación**

- [x] Funcionalidad de flujo documental 
- [x] Funcionalidad CRUD para el seguimiento del syllabus 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
###  Acta de  seguimiento
se implementa el input para el archivo del acta del consejo, se limita a formato pdf
![image](https://github.com/udistrital/sga_cliente/assets/42418412/a644bd36-c2bc-42b9-99c3-342b14b7cca5)
![image](https://github.com/udistrital/sga_cliente/assets/42418412/3d37d555-20c8-4602-9d51-a0ccee7bef4e)
![image](https://github.com/udistrital/sga_cliente/assets/42418412/1b16fb8c-056c-4bee-b7d6-89e4d0e538e1)

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la issue, se despliega en entorno de pruebas y se da por finalizada la issue
