### ISSUE TITLE
Implementación funcionalidad de carga de infomación versiones syllabus y carga principal con syllabus activo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1438]
Se requiere realizar la Implementación funcionalidad de carga de información versiones syllabus y carga principal con syllabus activo

**Sub Tareas**

- [x] Se debe desarrollar la funcionalidad de carga de las versiones de los syllabus para esto se debe tener presenta la relación nueva de los syllabus y tener presente el campo activo para saber cual es el versión y cual el actual, organizar la tabla según el versiónamiento (campo version) 
![image](https://github.com/udistrital/sga_cliente/assets/43799065/1d247d9f-fcaf-4949-82c5-9ada68d6d8cb)

- [x] Desarrollar la funcionalidad para la carga y visualización del documento según versión 
- [x] Para la tabla principal solo se debe cargar la versión actual del syllabus 
- [x] Crear botón para versionar el plan en el componente de versión al realizar esta acción debe utilizar tener presenta implementar el flujo de inactivar el registro anterior de syllabus y crear una versión de syllabus 
![image](https://github.com/udistrital/sga_cliente/assets/43799065/d07b6757-baaa-4aa1-a482-36503e32e946)

Tener presente el modelo 

syllabus_code: Optional[str] = None
version: Optional[int] = 0
syllabus_actual: Optional[bool] = False
espacio_academico_id: int
proyecto_curricular_id: int
plan_estudios_id: int
justificacion: Optional[str] = None
objetivo_general: Optional[str] = None
objetivos_especificos: Optional[List] = None
resultados_aprendizaje: Optional[List] = None
articulacion_resultados_aprendizaje: Optional[str] = None
contenido: Optional[Dict] = None
estrategias: Optional[List] = None
evaluacion: Optional[Dict] = None
bibliografia: Optional[Dict] = None
seguimiento: Optional[List] = None
sugerencias: Optional[str] = None
recursos_educativos: Optional[str] = None
practicas_academicas: Optional[str] = None
activo: bool = Field(default=True)
fecha_creacion: datetime = Field(default=local_now())
fecha_modificacion: Optional[datetime] = None

**Criterios de aceptación**

- [x] Desarrollo de funcionalidad de carga versionamiento
- [x] Desarrollo flujo de versionamiento 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
### componente de visualizacion de versiones de syllabus
![image](https://github.com/udistrital/sga_cliente/assets/42418412/ad9875da-2497-4b88-b01a-2c23b7a754d0)
