### ISSUE TITLE
Revisión del flujo de identificación por error de direccionamiento y autenticación en el cliente de syllabus entorno de pruebas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1439]
Se requiere realizar la Revisión del flujo de identificación por error de direccionamiento y autenticación en el cliente de syllabus entorno de pruebas 

**Sub Tareas**

- [ ] Revisión del flujo de autenticación  por error de direccionamiento tener presente la documentación de https://angular.io/api/common/LocationStrategy, 
- [ ] Revisar el error de direccionamiento directo a los componentes 
![image](https://github.com/udistrital/sga_cliente/assets/43799065/a29aff7f-0a71-4a6d-804b-0b32be51f5eb)

**Criterios de aceptación**

- [ ] Ajuste de flujo de autenticación cliente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
La imposibilidad de pasar del login al dashboard cuando se usa _LocationStrategy_ es que no da espera a **web-component** de tomar la url que pasa el _access_token_ y por ende no imite la información del usuario que da fin a esa transición del login, es decir este observador no estaba siendo activado [addEventListener(user)](https://github.com/udistrital/syllabus_cliente/blob/develop/src/app/app.component.ts#L73C19-L73C19); situación extraña porque en cumplidos_dve_cliente y resoluciones_cliente_v2 consumen web-component y no es necesario realizar parches, por versión tampoco parece ser lío estos dos clientes tienen una versión de anguar superior a web-component, pero inferior a la del cliente actual, de hecho se prueba ajustando syllabus y también creando un proyecto con versión anterior y el problema se seguía presentando.

La "solución" es capturar el evento del router cuando pase por la ruta `/access_token` y simular el proceso que debía realizar _web-component_ cuando va a emitir por user.

``` typescript
this.router.events.subscribe((event: any) => {
      // ...
      const urltk: string = event.url ? event.url : ""
      if (urltk.includes('/access_token')) {
        var params: any = {}, queryString = location.hash.substring(1), regex = /([^&=]+)=([^&]*)/g;
        let m;
        while (m = regex.exec(queryString)) {
          params[decodeURIComponent(m[1])] = decodeURIComponent(m[2]);
        }
        const req = new XMLHttpRequest();
        const query = 'https://' + window.location.host + '?' + queryString;
        req.open('GET', query, true);
        if (!!params['id_token']) {
          const id_token_array = (params['id_token']).split('.');
          const payload = JSON.parse(atob(id_token_array[1]));
          window.localStorage.setItem('access_token', params['access_token']);
          window.localStorage.setItem('expires_in', params['expires_in']);
          window.localStorage.setItem('state', params['state']);
          window.localStorage.setItem('id_token', params['id_token']);
        }
      }
      // ...
    });
  }
```

**Comment by NeFaWaltPint** [comment]
### Test

![Peek 25-09-2023 15-42](https://github.com/udistrital/sga_cliente/assets/31144689/ad24b342-95b5-4fe6-b984-74c0cff35ab8)
