### ISSUE TITLE
Crear documentación tecnica de funciones CRUD syllabus con información relevante 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1447]
Se requiere realizar la Creación documentación técnica de funciones CRUD syllabus con información relevante 

**Sub Tareas**

- [x] Crear documento con las funciones CRUD donde se mencione las librerías, flujo de la función, variables y descripción básica de las funciones CRUD con tecnologías servirles

**Criterios de aceptación**

- [x] Documento técnico 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
Documento final
[INFORME TÉCNICO LAMBDAS SGA.pdf](https://github.com/udistrital/sga_cliente/files/12888972/INFORME.TECNICO.LAMBDAS.SGA.pdf)

**Comment by edwargl7** [comment]
Se agrega enlace del documento
https://udistritaleduco-my.sharepoint.com/:w:/g/personal/hegranadosl_udistrital_edu_co/EYnKUCqfThNMl_J4QjJ4FecBWHS4BKR22BEhw6fZX0X-og?e=kEZh1w

**Comment by fabianbarreto02** [comment]
Se migra informe a la carpeta del proyecto, Se revisa la issue y se da por finalizada la issue
