### ISSUE TITLE
Ajuste y revisión reporte plan de accion de funcionamiento unidades particulares SISGPLAN para la armonización del PED y PUI

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1449]
Se requiere realizar el Ajuste y revisión reporte plan de acción de funcionamiento unidades particulares SISGPLAN para la armonización del PED y PUI

**Sub Tareas**

- [x] Realizar la revisión de la generación de reporte individual por unidad para la correcta armonización del PED y PUI, se debe tener en cuenta la combinación de las cedas según la cantidad de niveles armonizados en el sistema 

**Criterios de aceptación**

- [x] Ajuste de reporte 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
### Test

![Captura](https://github.com/udistrital/sga_cliente/assets/31144689/b73789d2-ab94-4fcc-b548-67be29592c39)

Tiempo de respuesta: 30 seg de media
![Captura de pantalla de 2023-10-10 07-24-29](https://github.com/udistrital/sga_cliente/assets/31144689/6fba18c2-4423-4c94-a8e9-81f864135060)
