### ISSUE TITLE
Prueba de concepto para la creación de microcliente e implementación de Editor de texto enriquecido para la creación de template para correos personalizados 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1454]
Se requiere realizar la Prueba de concepto para la creación de micro cliente e implementación de Editor de texto enriquecido para la creación de template para correos personalizados 

**Sub Tareas**

- [x] Realizar la investigación de componentes de editor de texto enriquecido 
- [x] Implementación de prueba de concepto para modulo de creación de template con tecnologia de micro cliente

**Criterios de aceptación**

- [x] Prueba de concepto 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
# Prueba de concepto Micro cliente

Se realiza una investigación sobre la posible implementación de micro clientes, como lo pueden ser mediante module federation de webpack, piral, openComponents y otros.

De los cuales se toma para la prueba a [single-spa](https://single-spa.js.org/), puesto que es de los frameworks más estables y soportados actualmente, dentro de las características principales de single-spa tenemos:

- Permite el uso de múltiples frameworks como React, angular, vue , etc.
- Despliegue de micro clientes de forma independiente.
- Herramientas de migración de spa para trabajar como micro cliente.
- lazy load para mejor desempeño.

## Estructura de single-spa

- Root-config:
Se encarga de cargar y administrar los diferentes micro clientes como aplicaciones registradas, controlando cuando se montan o desmontan estos, así como administrar dependencias compartidas, comunicación entre micro clientes y el layout de estos.
- Applications:
Aplicaciones desarrolladas en cualquiera de los frameworks soportados, los cuales de construyen como un módulo standalone, el cual define los estados de su ciclo de vida (bootstrap, mount, unmount)

## Prueba de concepto

Para la prueba de concepto se tiene la siguiente estructura de carpetas:
![image](https://github.com/udistrital/sga_cliente/assets/42418412/faa3d8f2-6698-490c-a4ab-ce5d881ba377)
donde tenemos el root, y tres micro clientes que funcionan con diferentes versiones de angular.

- root
Se crea mediante el cli de single-spa con el comando:
`npx create-single-spa --moduleType root-config`
después de indicar la información requerida se crea la siguiente estructura:
![image](https://github.com/udistrital/sga_cliente/assets/42418412/1dffcef1-82aa-4bca-a7f8-f01cf285945b)
en el archivo testud-root-config registraremos las aplicaciones que usaremos y  definiremos su ciclo de vida según el manejo de rutas:
![image](https://github.com/udistrital/sga_cliente/assets/42418412/11eea0cf-0538-494f-a59e-f7923cf25202)
de igual forma se define el importmap  en el index, indicando las url donde se sirven los módulos de los micro clientes, para su uso in-browser.
![image](https://github.com/udistrital/sga_cliente/assets/42418412/8845352f-a6ad-4189-bea5-a32dca37531d)
de igual forma se define el layout de los microclientes en el body
![image](https://github.com/udistrital/sga_cliente/assets/42418412/85a94f4d-32b9-4fa3-b820-f11cb1afafa4)

- mf-application
Para los micro clientes estos pueden ser creados mediante el cli de single-spa con el siguiente comando:
`npx create-single-spa --moduleType app-parcel`
o se puede crear un proyecto de la forma convencional y ajustar, para el caso de angular es necesario agregar singel-spa-angular:
`ng add single-spa-angular`
y configurar segun la [documentacion ](https://single-spa.js.org/docs/ecosystem-angular).
Cada micro cliente crea un archivo de main.single-spa.ts en el cual se define una interface de comunicación entre este y el root, exponiendo así su funcionalidad y administración de ciclo de vida. 
![image](https://github.com/udistrital/sga_cliente/assets/42418412/94ed79b9-3680-4199-bf87-90c34818c7a7)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue.
