### ISSUE TITLE
Ajuste componente syllabus y generador pdf modulo syllabus según solicitudes del usuario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1455]
Se requiere realizar el Ajuste componente syllabus y generador pdf modulo syllabus según solicitudes del usuario 

**Sub Tareas**

- [x] Limitar la consulta del select de idioma a los siguientes idiomas: ingles, francés, alemán, italiano, portugués, mandarín y español
- [x] En la sección V. PROPÓSITOS DE FORMACIÓN Y DE APRENDIZAJE (PFA) DEL ESPACIO ACADEMICO, la columna Competencias debe ser opcional en el componente 
- [x] En la sección V. PROPÓSITOS DE FORMACIÓN Y DE APRENDIZAJE (PFA) DEL ESPACIO ACADEMICO, la columna Competencias puede llegar vacio ajustar el reporte de pdf
- [x] Agregar boton en el componente de versionamiento para consumir el generador de pdf y visualización de syllabus a una versión anterior 
- [x] Ajustar tamaño de columna del pdf sección V. PROPÓSITOS DE FORMACIÓN Y DE APRENDIZAJE (PFA) DEL ESPACIO ACADEMICO columna #
![image](https://github.com/udistrital/sga_cliente/assets/43799065/c316b418-5699-4da1-a1a7-b2f32dc355e8)

- [x] Ajustar label de la tabla de historial de syllabus fecha fin 
![image](https://github.com/udistrital/sga_cliente/assets/43799065/f9b23b7d-cb62-49b3-ad0b-b14b20d9920c)

- [x] En la sección 6 Estrategias de enseñanza que favorecen el aprendizaje solo dejar un campo descrpción para el resgistro, se mantiene el boton + para incluir mas estrategias 
![image](https://github.com/udistrital/sga_cliente/assets/43799065/123b596f-08ea-4dde-8afa-6474b9cd517e)

- [x] Ajustar pdf para la sección Estrategias de enseñanza que favorecen el aprendizaje solo dejar un campo descrpción  y mantener viñetas para las n estrategias 
![image](https://github.com/udistrital/sga_cliente/assets/43799065/55c007f7-8bad-4e58-b52a-43cf09b78d81)

- [x] Ajustar flujo de roles JEFE_DEPENDENCIA y COORDINADOR  estos roles solo podrán observar el visualizador, no podran generar una versión o editar un syllabus, solo podra observar las versiones y la versión actual 

**Criterios de aceptación**

- [x] Realizar los ajustes solicitados 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Prueba Local

Se realizan los ajustes requeridos en el template.

[descarga.pdf](https://github.com/udistrital/sga_cliente/files/12826738/descarga.pdf)

**Comment by JuanCamiloMartinezLopez** [comment]
### Cambios en el cliente

- Limitación de idiomas:
![image](https://github.com/udistrital/sga_cliente/assets/42418412/525a711a-6be4-4f03-bf82-e83d88cfbcbf)
- Input de competencias de la tabla PFA opcional
![image](https://github.com/udistrital/sga_cliente/assets/42418412/83f29d5b-9644-40a0-b184-57f48a92a0d1)
- Ver versión anterior de un syllabus
![image](https://github.com/udistrital/sga_cliente/assets/42418412/dd207f5f-7a72-4887-88de-59997442147c)
- Ajuste fecha inicio tabla de versiones
![image](https://github.com/udistrital/sga_cliente/assets/42418412/e241d5d7-7799-497b-99d1-b8f7787e6349)
- Ajuste form de estrategias
![image](https://github.com/udistrital/sga_cliente/assets/42418412/e37db991-ff30-4a4c-af93-f112b025b5a1)
- Restricción de creación y edición para los roles de JEFE_DEPENDENCIA y COORDINADOR
Se crea en el servicio de syllabus una variable que permite validar si el usuario puede crear/editar los syllabus
![image](https://github.com/udistrital/sga_cliente/assets/42418412/c0c81d9c-3465-4cd2-a2c9-6e3a1ac10510)

**Comment by edwargl7** [comment]
### Pruebas SGA MID

Pruebas de dos versiones.
[descarga (1).pdf](https://github.com/udistrital/sga_cliente/files/12833301/descarga.1.pdf)
[descarga.pdf](https://github.com/udistrital/sga_cliente/files/12833302/descarga.pdf)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue.
