### ISSUE TITLE
Ajustes a nivel cliente para armonización de planes PET y PUI en el sistema SISGPLAN

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1459]
Se requiere realizar el Ajustes a nivel cliente para armonización de planes PET y PUE en el sistema SISGPLAN

**Sub Tareas**

- [x] Realizar el ajustes para los componentes de armonización PET y PUI para realizar la armonización completa de los hijos con sus respectivos padres, para evitar tener información faltante 
- [x] Realizar ajuste para el manejo a nivel cliente de la armonización PET y PUI cuando no aplica la armonización y no poder seleccionar algún nivel previa selección de la opción no aplica 

**Criterios de aceptación**

- [x] Realizar los ajustes 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
## Test
![Peek 16-10-2023 15-47](https://github.com/udistrital/sga_cliente/assets/31144689/b5f7a0ec-f4f5-4dbf-b970-f1dcb8643ffa)

**Comment by NeFaWaltPint** [comment]
**Nota:** Tener en cuenta que el componente `app-arbol` se modificó y por ende una de sus salidas `@Output() grupo = new EventEmitter<any>();` se comporta de manera diferente.

El componente `formulacion` que usa "app-arbol" maneja ahora el evento de `(grupo)="receiveMessage($event)"` de la siguiente manera:
```typescript
receiveMessage(event) {
    if (event.bandera === 'armonizar') {
      /* var uid_n = event.fila.level;
      var uid = event.fila.id; // id del nivel a editar
      if (uid != this.dataArmonizacionPED.find(id => id === uid)) {
        this.dataArmonizacionPED.push(uid)
      } else {
        const index = this.dataArmonizacionPED.indexOf(uid, 0);
        if (index > -1) {
          this.dataArmonizacionPED.splice(index, 1);
        }
      } */
      this.dataArmonizacionPED = event.armonizacionIds;
    }
  }
```

Tener presente los componentes cuando se vayan a usar, revisar y ajustar sus funciones de la misma manera:
- `formulacion-plan-inversion` _(ahí hay tres usos de "app-arbol")_
https://github.com/udistrital/planeacion_cliente/blob/fcc283d18ce663ac28a7a1b2206fb25ac72786cd/src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formulacion-plan-inversion/formulacion-plan-inversion.component.html#L67
- `formular-proyecto-inversion` _(ahí hay tres usos de "app-arbol")_
https://github.com/udistrital/planeacion_cliente/blob/e09c8b8e0457d291e2251828a3c71c46a046db5d/src/app/pages/banco-de-proyectos/proyectos-inversion-macro/formular-proyecto-inversion/formular-proyecto-inversion.component.html#L123

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en el entorno de pruebas y en el entorno de producción
