### ISSUE TITLE
Ajustes flujo documentos inscritos en pruebas identificación de duplicados replicar ajustes de prod a pruebas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1477]
Se requiere realizar el Ajustes flujo documentos inscritos en pruebas identificación de duplicados replicar ajustes de prod a pruebas

**Sub Tareas**

- [x] Ajustes flujo documentos inscritos en pruebas identificación de duplicados replicar ajustes de prod a pruebas

**Criterios de aceptación**

- [ ] Sincronizar los ajustes de producción a pruebas 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by NeFaWaltPint** [comment]
Replicado en dev de este hotfix: https://github.com/udistrital/sga_cliente/issues/1444#issuecomment-1743077359

![docs](https://user-images.githubusercontent.com/31144689/271990396-980f94fe-3541-4ac2-a63a-6b5112f604b9.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue, se despliega en entorno de pruebas
