### ISSUE TITLE
Unificación de funciones lambda CRUD para la creación de syllabus en una sola función lambda

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1486]
Se requiere realizar la Unificación de funciones lambda CRUD para la creación de syllabus en una sola función lambda

**Sub Tareas**

- [x] Se debe realizar la Unificación de funciones lambda CRUD para la creación de syllabus en una sola función lambda
- [x] Crear documentación básica de como funciona la nueva arquitectura 

**Criterios de aceptación**

- [ ]Unificación de las funciones lambda  

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Pruebas Locales

Resultado prueba en local, endpoints generados
![image](https://github.com/udistrital/sga_cliente/assets/50187485/51dfda62-672a-4001-8542-2fb3de579095)

### Validación de resultado
Get All
![image](https://github.com/udistrital/sga_cliente/assets/50187485/fa0d95c3-0263-40f0-b1ff-9d701ebdb9b6)

Get One
![image](https://github.com/udistrital/sga_cliente/assets/50187485/214b460c-40ac-45fe-8b2f-b9c5a15317b9)

![image](https://github.com/udistrital/sga_cliente/assets/50187485/a88e5bbe-9b66-4d59-a0a8-0eb19ae556e1)

Put
![image](https://github.com/udistrital/sga_cliente/assets/50187485/b40ba867-8720-4d3b-b9df-290df2d9207d)

Post
![image](https://github.com/udistrital/sga_cliente/assets/50187485/124dd0a0-d2c4-498d-a928-5f725607e95e)

**Comment by edwargl7** [comment]
### Despliegue realizado con éxito
![image](https://github.com/udistrital/sga_cliente/assets/50187485/cb151fb4-9518-4b6d-a4a0-fceac1332489)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
