### ISSUE TITLE
Revisar resultado de las pruebas funcionales realizadas por el Centro de Servicios https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34209 y realizar los ajustes pertinentes. 6 Horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#149]
Se debe realizar las correcciones sugeridas por el centro de servicios, en el pdf:
[Resultado pruebas.pdf](https://github.com/udistrital/sga_cliente/files/4032974/Resultado.pruebas.pdf)

La issue debe cumplir con los siguientes requisitos:

- [x] Ser especifico en los errores.
- [x] Revisar el error al INHABILITAR un proyecto.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de corrección de errores

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del error al crear un proyecto y error al inhabilitar  un proyecto por revisión del centro de servicios, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se revisan los ajustes realizados, se hace el despliegue y se verifica corrección de las incidencias presentadas en las pruebas.
