### ISSUE TITLE
Revisión del flujo de consulta del servicio de generación de pdf de syllabus, optimizar el tiempo de respuesta del generador en ambiente de pruebas.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1495]
Se requiere realizar la Revisión del flujo de consulta del servicio de generación de pdf de syllabus, optimizar el tiempo de respuesta del generador en ambiente de pruebas.

**Sub Tareas**

- [x] Analizar la forma de optimizar la generación del PDF, si manteniendo la arquitectura de la generación por función lambda mediante la precarga de módulos necesarios o cambiando la arquitectura del flujo de generación
- [x] Implementar la forma definida para la optimización de tiempo de generación de pdf

**Criterios de aceptación**

- [x] Analizar la posible solución 
- [x] Implementación de la optimización 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@edwargl7 por favor comentar avances y tareas realizadas.

**Comment by edwargl7** [comment]
## Pruebas Locales

Se toma como segunda opción la realización de la plantilla y su el llenado de cada campo empleando el lenguaje Go, por medio de las librerías [excelize](https://pkg.go.dev/github.com/xuri/excelize/v2) para el uso y generación de un archivo XLSX y la conversión de este a PDF usando la librería [gofpdf](https://pkg.go.dev/github.com/jung-kurt/gofpdf).
Estas librerías ya fueron usadas en el proyecto de SGA para realizar reportes tanto en XLSX como en PDF, obteniendo buenos tiempos de respuesta.

Se realizan diferentes pruebas para generar el PDF. 

###

**Comment by edwargl7** [comment]
## Resultado final :x: 
Se realizaron diferentes pruebas con tamaños de contenido variados para revisar el comportamiento en el diseño. Pero los resultados obtenidos pasando del XLSX a PDF no fueron los esperados, se trataron de realizar la mayor cantidad de ajustes para tener un buen resultado pero se encontraron varios fallos en el diseño que no podían ser mejorados.

### Observaciones

- El texto no toma el estilo justificado.
- Posibilidad de dividir el texto en palabras que al no ser justificado pueden quedar en una línea nueva.
![image](https://github.com/udistrital/sga_cliente/assets/50187485/2d0e00e8-ac8f-4c85-bcd1-061396e46cdb)
- En las tablas al no ser justificado puede quedar caracteres sobre la margen del recuadro.
![image](https://github.com/udistrital/sga_cliente/assets/50187485/9cd4c868-5eed-4365-8263-296129c31336)
- :watch:  Adicionalmente, el tiempo de respuesta era sobre los 10 segundos, aunque disminuye el tiempo vs la lambda que tiene el docker, sigue siendo un tiempo alto.

**Comment by edwargl7** [comment]
### Código fuente
Código fuente del experimento realizado.
[Código_prueba_XLSX_2_PDF.zip](https://github.com/udistrital/sga_cliente/files/13911097/Codigo_prueba_XLSX_2_PDF.zip)
