### ISSUE TITLE
 Creación del componente base con arquitectura de micro cliente para el sistema SGA Primera Parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1496]
Se requiere realizar la  Creación del componente base con arquitectura de micro cliente para el sistema SGA

**Sub Tareas**

- [x] Teniendo la prueba de concepto desarrollado en la issue #1454 realizar la creación del cliente base con los componente de footer, header y consumo del servicio de configuración_mid para la creación de menu del sistema.
- [x] Analizar la implementación del flujo de autenticación para el cliente base del sistema de sga 

**Criterios de aceptación**

- [ ] Implementación del cliente base con arquitectura single-spa
- [x] Analizar el flujo de autenticación 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
Documentar issue @JuanCamiloMartinezLopez

**Comment by JuanCamiloMartinezLopez** [comment]
# Creación del cliente base para sga

Se crea la [aplicacion ](https://github.com/udistrital/sga_cliente_root)root, encargado de administrar los diferentes mf de sga, esta tambien contiene los datos del token de las variables de entorno, las que son requeridas en el proceso de logeo e identificacion de permisos con wso2 para este cliente.

de igual forma se desarrolla el mf de [core](https://github.com/udistrital/core_mf_cliente), encargado de manejar lo transversal a todos los mf, como es el header, footer, sidebar, etc. esto tomando como ejemplo el antiguo web-components. encargado de esto mismo.

**Comment by fabianbarreto02** [comment]
Se da por fibalizada la issue
