### ISSUE TITLE
Desarrollo del cliente de registro proyecto académico (24 Horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#15]
Se debe desarrollar el cliente para el registro del proyecto academico, se tendra en cuenta el [mockup](https://www.draw.io/?state=%7B%22ids%22:%5B%221CEakcj2hk_Ao_DKg5LSgM2E4tUjnvS04%22%5D,%22action%22:%22open%22,%22userId%22:%22102492667183582276825%22%7D#G1CEakcj2hk_Ao_DKg5LSgM2E4tUjnvS04), se desarrollara como un componente del cliente, para el desarrollo de esta issue ira de la mano con las [issue del MID](https://github.com/udistrital/sga_mid/issues/6) y de la [issue CRUD](https://github.com/udistrital/proyecto_academico_crud/issues/2), el cliente debe cumplir con los siguientes requerimientos:

- [x] El cliente debe tener toda la información definida en el mockup.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se Inicia el desarrollo del cliente

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea, se desarrolla en la [rama Registro_proyecto](https://github.com/udistrital/sga_cliente/tree/Registro_proyecto), la justificación de la demora de la issue, es la curva de aprendizaje del desarrollador, se espera revision por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
De la revisión realizada, se tiene la siguiente observación: 
- No permite seleccionar la fecha de registro mediante DatePicker, con lo cual se genera error al hacer el registro del proyecto por el formato de la fecha:
![image](https://user-images.githubusercontent.com/14035745/65876292-86cc4900-e34e-11e9-9bb3-d05842b52023.png)

**Comment by mafeave** [comment]
Se dan las siguientes observaciones de la revisión realizada por el equipo de trabajo:
- Enfasis agregar opción para agregar uno nuevo y poder agregar varios a la carrera
- Fechas (registro y vencimiento) - revisar formato y calculo de fecha de finalización
- Quitar unique tabla titulacion
- Tipos de registro del proyecto en el cliente
- Ajustar el Mid para consultar los registros del proyecto con la información de OIKOS

Las observaciones dadas se están trabajando en los siguientes issues: https://github.com/udistrital/sga_cliente/issues/19,  https://github.com/udistrital/sga_cliente/issues/18, https://github.com/udistrital/sga_cliente/issues/20#event-2655447929 y https://github.com/udistrital/sga_mid/issues/10
