### ISSUE TITLE
Desarrollar tab de inscripciones, definir con arquitecto y analista la línea a seguir (secuencia del tab dependiendo tipo de inscripción) - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#150]
Se debe desarrollar el modulo de preinscripcion para los distintos tipo de inscripcion, esta issue debe cumplir con los siguientes requerimientos:

- [x] Se debe ajustar el Api de inscripciones para agregar un campo de nivel (pregrado y posgrado) en los tipos de inscripción, realizar el migrations, el id se debe referenciar con el tipo de dependecia del Api Oikos.

- [x] Crear componente para el manejo de las pre inscripciones.

- [x] En el componte se debe en listar el periodo, el nivel y tipo de inscripcion.

- [x] Se debe registrar a información de basica del tercero y crear el tercero.

- [x] Se debe permitir el registro de una o varias inscripciones al tercero aspirante.

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza ajuste de api inscripciones para el manejo de niveles, se puede apreciar en el [commit](https://github.com/udistrital/inscripcion_crud/commit/902e71ad98bbb6339e8e642dab5e38b9d2e0da8a)

**Comment by mafeave** [comment]
Se verifica el registro de los tipos de inscripción con el nivel relacionado (Pregrado/Posgrado)

**Comment by fabianbarreto02** [comment]
Se realizan ajustes a nivel de mid en el siguiente [commit](https://github.com/udistrital/sga_mid/commit/ea8923ad9f678197f5a2691ec7acbecd6dd94568)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea, se realiza el componente de preinscripcion a una o varios proyectos, se espera revision por parte de @mafeave

**Comment by mafeave** [comment]
Tener en cuenta las siguientes observaciones:
- Agregar un tipo de inscripción: nuevo/primer semestre
- Ajustar listado de carreras para cuando los tipos de inscripción de pregrado sean ciclos propedeúticos y profesionalización tecnólogos

Pendiente actualización de swagger del mid en WSO2 para verificar funcionalidad en entorno de pruebas.

**Comment by mafeave** [comment]
![image](https://user-images.githubusercontent.com/14035745/72848910-9c55dd80-3c73-11ea-9b1e-dbe19557068e.png)

Tener en cuenta que máximo son 4 inscripciones por aspirante y que se deben generar alertas de acuerdo a los casos descritos en la Historia de Usuario
