### ISSUE TITLE
Se está demorando en cargar todos los campos, revisar los reducers del former, revisar sentencias hidden por ng*if

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#151]
Se está demorando en cargar todos los campos, revisar los reducers del former, revisar sentencias hidden por ng*if
- [x] Se reduce el tiemp ode carga de los formularios

**Comment by JuanPiedrahita** [comment]
https://github.com/udistrital/sga_cliente/commit/6bdfc2e194f71686fec59d0c5e656cac5bf1d36f cargando data solo hasta que es necesario, prueba para verificar retardo en componente.

**Comment by JuanPiedrahita** [comment]
Se realiza revisión de porque se demora tanto la carga de los componente del formualario principal de inscripcion y además de porque este es tan lento una vez se carga, encontrando lo siguiente.

**Motivo de la demora en la carga inicial del componente:**
Se revisaron los reducers de los componentes, encontrando que estos hacen consultas simples de los valores de las tablas parametricas, razón por la cual no estan mal, el problema es que cuando se inicia el componente se cargan todos los datos de todos los formularios disponibles (más o menos 28) razón por lo cual estas consultas por pequeñas que sean retrasan la carga del componente. Además, cada componente carga la información que tiene registrada (para cada formulario, incluyendo no solo datos sino que también archivos) con el fn de mostrar al usuario lo que lleva del proceso razón por la cual el proceso total de carga es aún mayor.
Para solucionar este problema se realizo la prueba desplegada en este commit https://github.com/udistrital/sga_cliente/commit/6bdfc2e194f71686fec59d0c5e656cac5bf1d36f que actualmente se encuentra en ambiente de pruebas y se puede verificar que no se carga la información de un tab hsata que este esta activo. Esto se hizo cambiando la etiqueta hidden por un *ngIf que evita que se renderice el componente (el cambio se puede ver en las siguientes lineas):

**Motivo de formularios lentos:**

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea teniendo en cuenta que se termina la revisión y además se implementa la opción del *ngIf.

**Comment by mafeave** [comment]
De acuerdo a observación por parte de @fabianLeon, otra opción para mejorar la carga en el cliente sería cargar mediante un servicio del mid todos los datos paramétricos y cargarlos en cache en los formularios.
