### ISSUE TITLE
Construcción de cliente con arquitectura micro frontend para el modulo de actualización de datos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1510]
Se requiere realizar la Construcción de cliente con arquitectura micro frontend para el modulo de actualización de datos 

**Sub Tareas**

- [ ] Construir el cliente para el modulo de actualización de datos 
- [ ] Migrar los componente del modulo [pages/solicitudes/list-solicitudes-estudiante, 
](https://github.com/udistrital/sga_cliente/tree/develop/src/app/pages/solicitudes) en el nuevo cliente
![image](https://github.com/udistrital/sga_cliente/assets/43799065/3498d96a-5d58-4d58-ad11-3b177d5e2605)

- [ ] Ajustar los componentes para su funcionamiento con la nueva versión de framework 

**Criterios de aceptación**

- [ ] Migración de componentes con la nueva arquitectura 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
@JuanCamiloMartinezLopez por favor comentar estado de la tarea.

**Comment by JuanCamiloMartinezLopez** [comment]
# Creación del micro cliente de actualización de datos 
Se siguen los pasos base para la creación de un micro cliente creando un cliente base con un router interno que responde a las rutas generales del core_mf_cliente desde el sidebar, esto se deja en evidencia en los commit de [cliente ](https://github.com/udistrital/sga_cliente_datos_mf/commits/develop/).

a partir de ahí se migran los componentes, servicios y más usados por este módulo del cliente antiguo de sga, esto sin hacer refactorización del código, y se integra con en el app root de sga, junto con el core_mf.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
