### ISSUE TITLE
Creación de micro cliente para el componente dinámico dinamicforms con arquitectura de micro frontend primera parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1517]
Se requiere realizar la Creación de micro cliente para el componente dinámico dinamicforms con arquitectura de micro frontend

**Sub Tareas**

- [ ] Analizar el componente actual del cliente SGA  dinamicform para entender su funcionamiento y replicar su funcionalidad en el componente nuevo https://github.com/udistrital/sga_cliente/tree/develop/src/app/%40theme/components
- [ ] Replicar el componente de dinamic form con arquitectura micro clientes y con la funcionalidad de ser consumido desde otros cliente primera parte.

**Criterios de aceptación**

- [ ] Analizar el componente
- [ ] Replicar el componente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by milo19980525** [comment]
@JuanCamiloMartinezLopez para el viernes 15 se debe tener en funcionamiento el dinamic form desde un microcliente en local.

**Comment by milo19980525** [comment]
@JuanCamiloMartinezLopez por favor comentar estado de la tarea.

**Comment by JuanCamiloMartinezLopez** [comment]
# Creación de mf de utilidad de componentes general 

Se intenta crear un mf de tipo utilidad, segun la [definicion de single-spa](https://single-spa.js.org/docs/module-types) , esto con el objetivo de mediante systemjs poder compartir estos componentes y ser reutilizados en otros mf. Siendo el primero de estos el dynamic-form de sga ( componente encargado de crear formularios mediante un json de entrada).

Se realizó la prueba creando un proyecto base de angular, y exportando los componentes indicados en la definición del componente base, pero esto no funcionó.
