### ISSUE TITLE
Creación de micro MID para el proceso de Calendario Académico y Proyecto curricular

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1518]
Se requiere realizar la Creación de micro MID para el proceso de Calendario Académico y Proyecto curricular

**Sub Tareas**

- [x] Crear el api mid para el proceso proceso de Calendario Académico
- [x] Crear el api mid para el proceso proceso de Proyecto curricular
- [x] Identificar el consumo de la rutas actuales para la actualización del consumo del servicio nuevo

**Criterios de aceptación**

- [x] Documentación de los servicios para su futuro migración
- [x]  Creación del api mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Mapeo de endpoints revisado para el módulo de Calendario Académico

### Endpoints calendario académico
[revision_modulo_CalendarioAcadémico_endpointsCalendarioAcademico.ods](https://github.com/udistrital/sga_cliente/files/13547947/revision_modulo_CalendarioAcademico_endpointsCalendarioAcademico.ods)

**Comment by edwargl7** [comment]
![SGA_micromid-Mod_Calendario_academico drawio](https://github.com/udistrital/sga_cliente/assets/50187485/e2986118-cf7b-4084-aa2c-5fd39918586d)

**Comment by edwargl7** [comment]
## Pruebas Locales

### Prueba microservicio calendario
Respuesta nuevo microservicio
![image](https://github.com/udistrital/sga_cliente/assets/50187485/a893926e-0a54-4d7c-9c2d-5c619e0a3745)

Respuesta servicio SGA_MID
![image](https://github.com/udistrital/sga_cliente/assets/50187485/4ec4b74a-b1dc-4b57-951b-f341aa8b040f)

**Comment by edwargl7** [comment]
![SGA_micromid-Mod_Proyecto_curricular drawio](https://github.com/udistrital/sga_cliente/assets/50187485/9f66293e-6f37-4640-915b-4cbaf9e526b4)
