### ISSUE TITLE
Creación de micro cliente para el componente dinámico dinamicforms con arquitectura de micro frontend tercera parte

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1523]
Se requiere realizar la Creación de micro cliente para el componente dinámico dinamicforms con arquitectura de micro frontend

**Sub Tareas**

- [x] Replicar el componente de dinamic form con arquitectura micro clientes y con la funcionalidad de ser consumido desde otros cliente tercera parte.

**Criterios de aceptación**

- [x] Replicar el componente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by fabianbarreto02** [comment]
@JuanCamiloMartinezLopez por favor comentar estado de la tarea.

**Comment by JuanCamiloMartinezLopez** [comment]
Conforme a lo investigado en los pasados Issues #1517  y #1522. se opta por la opción de replicar provisionalmente los componentes como el dynamic-form mientras se logra encontrar una forma de compartir estos componentes.

dentro de las opciones que se plantean investigar estan:
- **Desarollo de [parcels](https://single-spa.js.org/docs/module-types#parcels) en React**
- **Seguir con la [investigación ](https://medium.com/@joeldenning/an-esm-bundle-for-any-npm-package-5f850db0e04d)para el uso de las librerías de angular**

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
