### ISSUE TITLE
Creación de micro MID para el proceso de Admisiones

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1526]
Se requiere realizar la Creación de micro MID para el proceso de Admisiones

**Sub Tareas**

- [x] Crear el api mid para el proceso proceso de Admisiones
- [x]  Identificar el consumo de la rutas actuales para la actualización del consumo del servicio nuevo

**Criterios de aceptación**

- [x]  Documentación de los servicios para su futuro migración
- [x] Creación del api mid

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
![SGA_micromid-Mod_Admisiones drawio](https://github.com/udistrital/sga_cliente/assets/50187485/e71d05fe-5c50-4502-b705-3ea8d656824d)

**Comment by edwargl7** [comment]
### Pruebas

Se realizan varias pruebas para encontrar valores que permitan tener un resultado del endpoint exitoso pero no es posible encontrar los casos necesarios.
![image](https://github.com/udistrital/sga_cliente/assets/50187485/f1dfb362-cb57-435c-aa46-ba362bac5b1a)

Resultado del microservicio
![image](https://github.com/udistrital/sga_cliente/assets/50187485/213c2efc-049c-4e02-b08d-e1653b37d1c6)

**Comment by edwargl7** [comment]
Lista endpoints y rutas en las que se usa en el cliente.
https://docs.google.com/spreadsheets/d/1OhDT1mE9zKMkkPU4ZdNePg8eYEO3_hofzCU9o8kamNE/edit?usp=sharing
