### ISSUE TITLE
Creación de micro MID para el proceso de plan de estudios y proceso de espacios académicos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1528]
Se requiere realizar la Creación de micro MID para el proceso de plan de estudios y proceso de espacios académicos

**Sub Tareas**

- [x]  Crear el api mid para el proceso proceso de plan de estudios 
- [x] Crear el api mid para el proceso proceso de  espacios académicos
- [x]  Identificar el consumo de la rutas actuales para la actualización del consumo del servicio nuevo

**Criterios de aceptación**

- [x] Documentación de los servicios para su futuro migración
- [x] Creación del api mid por proceso

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
![image](https://github.com/udistrital/sga_cliente/assets/50187485/d0caed96-8760-4ebc-81fd-ecac360178e0)

**Comment by edwargl7** [comment]
![image](https://github.com/udistrital/sga_cliente/assets/50187485/3dd36700-6e65-4880-88b8-bc87243b2cb7)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
