### ISSUE TITLE
Creación de capacitación general equipo SGA para la creación e implementación de Clientes con Arquitectura Micro cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1531]
Se requiere realizar la Creación de capacitación general equipo SGA para la creación e implementación de Clientes con Arquitectura Micro cliente 

**Sub Tareas**

- [x] Establecer la capacitación para la creación e implementación de Clientes con Arquitectura Micro cliente 
- [x] Crear materia de guía para la capacitación para la creación e implementación de Clientes con Arquitectura Micro cliente 
- [x] Documentar la capitación para la creación e implementación de Clientes con Arquitectura Micro cliente 

**Criterios de aceptación**

- [x] Establecer la capacitación para la creación e implementación de Clientes con Arquitectura Micro cliente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Desarrollo en local.
- [ ] Push en Feature.
- [ ] Pruebas locales (funcionales).
- [ ] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by JuanCamiloMartinezLopez** [comment]
#Capacitacion basica sobre micro clientes con single-spa

Se realiza la capacitación en la cual se indican los principios básicos de los micro clientes y de se indica las características básicas de single-spa, junto con un ejercicio básico dejando la [capacitación ](https://udistritaleduco-my.sharepoint.com/:v:/g/personal/fdbarretos_udistrital_edu_co/EUvvZeDgSQpBnNIBYaYftJwBrH2GAAxChWcdb-Kb4SJtUg?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)grabada

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
