### ISSUE TITLE
Sincronización y despliegue de funciones lambda para la creación de archivo xml y pdf para el reporte de syllabus 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1532]
Se requiere realizar la Sincronización y despliegue de funciones lambda para la creación de archivo xml y pdf para el reporte de syllabus  

**Sub Tareas**

- [x] Sincronizar el formato definido entre el archivo  xml y pdf para el reporte de syllabus  
- [x] Realizar el despliegue en entorno de pruebas de las dos funciones lambda para la generación de los archivos  xml y pdf para el reporte de syllabus  

**Criterios de aceptación**

- [x] Sincronización de archivos 
- [x] Despliegue de funciones lambda

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
## Pruebas Locales

Desplegada función de generación de pdf
![image](https://github.com/udistrital/sga_cliente/assets/50187485/39bc94c6-f77d-476f-aac2-482b885e4cc4)

**Comment by edwargl7** [comment]
## Pruebas Locales
Función generadora del archivo XLSX con estructura similar al PDF.

### Resultado archivo
![image](https://github.com/udistrital/sga_cliente/assets/50187485/a5c8f8ad-9950-47b5-8cda-2eea503a1976)
![image](https://github.com/udistrital/sga_cliente/assets/50187485/2c96a75e-28ab-4d3b-a345-7999e8f9c23d)
[Base64ToXLSX.xlsx](https://github.com/udistrital/sga_cliente/files/13953670/Base64ToXLSX.xlsx)

### Resultado endpoint
![image](https://github.com/udistrital/sga_cliente/assets/50187485/f433565b-6950-489a-9a22-ce42d634e26f)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
