### ISSUE TITLE
Crear controlador generador xml e implementar funcionalidad cliente consumo generador xml 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1533]
Se requiere realizar la creación controlador generador xml e implementar funcionalidad cliente consumo generador xml 

**Sub Tareas**

- [x] Creación del controlador para generar la consulta y el archivo xml con el syllabus consultado
- [x] Creación e implementación de boton para descargar el archivo xml en el cliente actual

**Criterios de aceptación**

- [x] Creación del controlador
- [x] Ajuste del cliente 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
![image](https://github.com/udistrital/sga_cliente/assets/50187485/854bc49c-b9fc-4b4b-9f00-63f8b7b52a02)

**Comment by fabianbarreto02** [comment]
Se da por finalizad la issue
