### ISSUE TITLE
Análisis y ajuste de nombre de controladores en la nueva arquitectura de micro mid para el cumplimento de lineamientos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#1534]
Se requiere realizar el Análisis y ajuste de nombre de controladores en la nueva arquitectura de micro mid para el cumplimento de lineamientos 

**Sub Tareas**

- [x] Analizar el nombre de los controladores que cumplen con los lineamientos definidos 
- [x] Documentar el cambio de nombre de controlador con el actual y el pasado
- [x] Actualizar el nombre de los controladores que no cumple con los lineamientos   

**Criterios de aceptación**

- [x] Actualizar los controladores que no cumplen con los lineamientos definidos 
- [x] Documentar los cambios realizados 

**Requerimientos**

No aplica

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by edwargl7** [comment]
# Pruebas Locales

## Microservicio MID - Terceros
![image](https://github.com/udistrital/sga_cliente/assets/50187485/647ab34b-780e-4c28-b603-aa6f37ead01f)

**Comment by edwargl7** [comment]
[Rutas SGA MID migración.xlsx](https://github.com/udistrital/sga_cliente/files/14070641/Rutas.SGA.MID.migracion.xlsx)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
