### ISSUE TITLE
Definir los criterios de admisión para un proyecto curricular, desarrollar registro de tipos de criterios para proyectos - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#161]
Se debe definir el componente principal para la asignación de los criterios de admisión de uno o varios proyectos curriculares, este componente debe cumplir con los siguientes requerimientos:

- [x]  Debe visualizar el periodo en el cual se esta creando el criterio de admisión.

- [x] Debe visualizar el nivel en el cual se esta creando el criterio de admisión.

- [x] Debe visualizar el proyecto o los proyectos en el cual se estan creando el criterio de admisión.

- [x] Se debe crear por un migrations la creación de los distintos requisitos.

- [x] Se debe ajustar el modelo de evaluación inscripcion para poder manejar los porcentajes a los subcriterios y manejo de notas parciales de los criterios.

- [x] Se debe ajustar el api de de evaluacion_inscripcion por los ajustes en los modelos.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Los ajustes realizados a nivel del api de evaluacion_inscripcion se relacionan en los siguientes commits:

- [Se ajusta modelos, controladores y rutas con los ajustes del modelo](https://github.com/udistrital/evaluacion_inscripcion_crud/commit/96ec698fe30463e0a8aadbe32b4e1f2fb0bfeae5)

- [Se ajusta modelos, controladores y rutas con los ajustes del modelo con campo formato que faltaba](https://github.com/udistrital/evaluacion_inscripcion_crud/commit/6868b0b5a2056c0e828a5173009c494bd1d3d8ca)

- [Se ajusta los migrations necesarios por cambio de modelo](https://github.com/udistrital/evaluacion_inscripcion_crud/commit/1e943af4977daed78ca699f6010414e89cc43f21)

- [Se ajusta el migration de insert para realizar pruebas](https://github.com/udistrital/evaluacion_inscripcion_crud/commit/6261d14c7d3d65ae1230aa80af797f3ece2c2744)

**Comment by fabianbarreto02** [comment]
Los archivos fuente de los ajustes realizados en los modelos se agregan en [drive](https://drive.google.com/drive/folders/13vYsTRMkAX5iM1OX2lo3CrxQBwMqDOmF)

**Comment by fabianbarreto02** [comment]
Se ajusta el cliente para poder seleccionar los criterios de admisión a una o varias proyectos y uno o varios proyectos solo tiene el enmaquetado falta funcionalidad la cual se desarrollara solo para el criterio icfes en otra issue

**Comment by fabianbarreto02** [comment]
Se aclara que la tarea tomo mucho mas tiempo de lo planeado, en total se gasto 30 horas de trabajo, las siguientes fueron las razones numero de horas trabajadas:

1. No se contemplo que era necesario revisar el modelo de datos de evaluación inscripción para el manejo de criterios y subcriterios.
2. Se tuvo problemas para ajustar el modelo de datos pensando en los futuros registros de las notas y  los subcriterios que pueda tener un criterio, esto requirió acompañamiento de la lider técnica @mafeave.
3. Se tuvo que realizar los ajustes adicionales de la api evaluacion_inscripción por cambio en modelo de datos.
4. A parte de realizar el migrations para la insertsion de los datos de pruebas se tuvo que desarrollar el migrations que ajustaba la base de datos en el entorno de pruebas.

Se da por finalizada la issue, Se espera revisión tecnica por parte de @mafeave

**Comment by mafeave** [comment]
Se despliegan los commits realizados
Falta asociar el API de evaluacion_inscripcion al cliente de SGA

Revisar: por qué al seleccionar un programa académico, se hace la petición a la consulta de requisito: v1/requisito/?query=Activo:true&limit=0, se sugiere hacer esa consulta antes de la selección de los programas

**Comment by DianaPatriciaRamirez** [comment]
Pendiente: Revisión y aprobación con arquitectos y DBAs, del modelo de datos [evaluacion_inscripcion_v3](https://drive.google.com/drive/folders/13vYsTRMkAX5iM1OX2lo3CrxQBwMqDOmF?usp=sharing)

**Comment by mafeave** [comment]
Se verifica ajuste realizado a través del commit https://github.com/udistrital/sga_cliente/commit/4808bb60835dbc078c59c8975a3321ac0dcebd28

Se da por finalzada la tarea.
