### ISSUE TITLE
Definir los criterios de admisión para un proyecto curricular, desarrollar del registro del criterio ICFES - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#162]
Se debe desarrollar el registro del criterio ICFES para la evaluación de la admisión, esta issue debe cumplir con los siguientes requerimientos:

- [x] Se debe desarrollar el componente que maneje los porcentajes del criterio principal de evaluación.

- [x] Se debe desarrollar el componente que maneje los porcentajes de los subcriterios de evaluación.

- [x] Realizar el metodo a nivel Api_MID para realizar el registro de los criterios a varios proyectos cuando lo es necesario, https://github.com/udistrital/sga_mid/issues/70

- [x] Configurar el cliente para realizar los registros de los criterios a los proyectos.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se da inicio a la issue

**Comment by fabianbarreto02** [comment]
Se da por termina la issue, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se verifica correcto funcionamiento del formulario de registro del criterio de ICFES
![Captura de pantalla de 2020-01-21 19-09-10](https://user-images.githubusercontent.com/14035745/72854388-3ae93b00-3c82-11ea-90a8-96bb27f30ece.png)

**Comment by mafeave** [comment]
Verificar en caso de que se presente algún error en el registro de los criterios, ya que al registrar un criterio ya registrado para un proyecto académico, se genera error en el API de evaluacion_inscripcion_crud, ṕero desde el cliente se muestra el mensaje de alerta de registro exitoso.

**Comment by fabianbarreto02** [comment]
Se realiza ajuste del error al momento de presenta a nivel de MID, se espera revision por parte de lider técnica

**Comment by mafeave** [comment]
Se verifica ajuste de la observación realizada.
