### ISSUE TITLE
Desarrollo de cliente para consulta general de proyectos académicos, incluye sólo el listado de los proyectos académicos (8 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#17]
Se debe desarrollar un componente que se visualización de los proyectos académicos registrados en el sistema,el cliente debe cumplir con los siguientes requerimientos:

- [x] El cliente debe tener toda la información definida en el mockup.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se desarrolla la consulta general de los proyectos como lo establecido en los mockups, desarrollando la issue, pude detectar que hace falta agregar a mid del sistema un controlado que traiga el nombre de la dependencia con el id registrado pues la consulta muestra el id de la facultad registrada, de manera similar, se requiere de un controlador que logre diferenciar las fechas de vencimiento de los posible registros, pues no se puede diferenciar en el json que tipo de registro es, en pocas palabras se sugiere realizar un Get con la información requerida para la consulta general, se espera revisión por parte de la lider técnica: @mafeave

**Comment by mafeave** [comment]
Se verifica formulario de consulta de los proyectos académicos:
![image](https://user-images.githubusercontent.com/14035745/65876013-0d345b00-e34e-11e9-839a-efded3cf5e7d.png)

Se da por finalizada la tarea.
