### ISSUE TITLE
Para carga masiva ICFES del módulo de admisiones, se debe incluir el periodo, guardar los puntajes por área, ajuste migrate y eliminar la opción de "Nombre" - 6 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#172]
Se debe realizar los siguientes ajustes a nivel cliente definidos por lider técnica:

- [x] se debe incluir un select donde se escoja el periodo para la carga del archivo.

- [x] Eliminar el campo del nombre del archivo por que no es necesario.

**Comment by fabianbarreto02** [comment]
Se realiza justes definidos por la lider técnica, la issue consumió mas tiempo de lo planeado por problemas al enviar el archivo por autenticación, revisar si al pasar por wso2 puede volver a presentar problema con el envio del archivo desde el cliente al API MID.

Se espera revisión técnica

**Comment by mafeave** [comment]
Se verifica ajuste en el formulario de carga masiva de ICFES
![imagen](https://user-images.githubusercontent.com/14035745/93109544-d1d38f00-f679-11ea-9875-929766dc21fc.png)
