### ISSUE TITLE
Formulario para definición de cupos por carrera - 24 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#173]
Se debe realizar un formulario que solicite el ingreso el numero de cupos por carrera habiliatados para un periodo particular, y realizar el calculo de los cupos especiales de acuerdo al [documento](https://docs.google.com/document/d/1NXcV_99vpYpeYFhMyDpmi2OXpO4bnRGMQnvs5_7Y2bg/edit), finalmente se debe realizar el registro de esta información en el api de evaluacion_inscripcion, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe escoger el proyecto y el periodo al cual se va a realizar la asignación de cupos.

- [x] Se debe solicitar el numero de cupos para el proyecto y periodo seleccionado.

- [x] Calcular los cupos especiales dependiendo del numero de cupos ingresados y mostrarlos en el componente.

- [x] Realizar el registro de los cupos definidos en el api evaluacion_inscripcion

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza el registro de cupos y calculo de cupos especiales segun historia de usuario, se configura que si ya existe un cupo para el proyecto y el mismo periodo se actualice el registros con los cambios, para esto se realizo una funcion a nivel que mid que realiza esa funcion y reegistra los cupos a un  proyecto o varios proyectos, eso se aprecia en el [commit](https://github.com/udistrital/sga_mid/commit/8feaed4bf37d6a92dab64883a88f71c7de4179eb).

Se da por finalizada la issue, se espera revisión por parte de lider técnico.

**Comment by mafeave** [comment]
Se revisa el formulario creado:
<img width="941" alt="asignación de cupos" src="https://user-images.githubusercontent.com/14035745/93032099-15d08080-f5f5-11ea-8212-867e79344e0e.png">

Se verifica el registro de los cupos habilitados, cupos para opcionados y cupos especiales de acuerdo a los valores calculados en el sistema.
![imagen](https://user-images.githubusercontent.com/14035745/93032133-4adcd300-f5f5-11ea-963b-deafd131a8ef.png)
