### ISSUE TITLE
Formulario que liste las inscripciones por proyecto - 12 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#174]
Se debe desarrollar un formulario donde se pueda actualizar el estado de los aspirante seleccionando los proyectos y los periodos a realizar el cambio, tambien se debe realizar un formulario para en listar las inscripciones por proyecto y periodo con el estado del cada aspirante para posteriormente realizar un reporte de inscritos, la issue debe cumplir con los suguientes requerimientos:

- [x] Desarrollar un componente que realice la actualización del estado de inscripcion de cada inscrito pasando el o los proyectos y el periodo, utilizando la funcion desarrollado en la [issue](https://github.com/udistrital/sga_mid/issues/80).

- [x] Desarrollar un componte en el cual se en liste los aspirante con su respectivo estado de inscripcion solicitando el proyecto y periodo a consultar

**Comment by fabianbarreto02** [comment]
Se inicio el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se crea funcion a nivel de api MID para la consulta de la informacion, del periodo y el proyecto, el metodo devuelve:

- tipo documento
- numero documento
- nombre completo
- tipo inscripcion
- estado inscripcion 
 
El metodo se puede ver en el siguiente [commit](https://github.com/udistrital/sga_mid/commit/eb30f27ca16e43179f72aacf47fd4a535668a1dc).

**Comment by fabianbarreto02** [comment]
Se ajusta función Mid para cargar y organizar el listado de aspirantes de mayor a menor con el campo puntaje total obtenido por cada aspirante, se realiza en el siguiente [commit](https://github.com/udistrital/sga_mid/commit/7d7ea336260fc75cc3d11a6bad6a89740f9b24ac).

**Comment by fabianbarreto02** [comment]
Se realiza el listado de aspirantes por carrera y periodo, el listado se organiza de mayor a menor puntaje total obtenido por cada aspirante, se da por finaliza la issue, se espera revisión por parte de lider técnico.

**Comment by mafeave** [comment]
Se revisa funcionalidad que lista las inscripciones por proyecto académico:
![imagen](https://user-images.githubusercontent.com/14035745/93090775-dfc9e580-f662-11ea-8fa1-1e9981590ecd.png)

Observaciones:
- Ajustar texto de botón 'Enlistar aspirantes' por 'Listar aspirantes'
- Ajustar servicio en el mid, 'consulta_aspirantes', no debería ser 'POST', cambiarlo a 'GET' con los parámetros de entrada: id_proyecto, id_periodo
- Ajustar servicio ya que cuando no hay inscripciones para el proyecto en el periodo académico habilitado, se retorna un 404

**NOTA:** los ajustes propuestos se realizarán en un issue nuevo.
