### ISSUE TITLE
Ajustar en componente Producción Académica  / Lista producción académica tilde en la palabra académico en el módulo y submódulo.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#189]
Se debe ajustar los siguiente requerimientos

- [x] tilde en la palabra académico en el módulo y submódulo.

**Comment by jupmorenor** [comment]
Se da inicio a la realización de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by fabianbarreto02** [comment]
Se revisa el ajuste solicitado
