### ISSUE TITLE
Ajuste en componente creación de tipo periodo/ listar los tipos periodo, tilde en la palabra creación del modulo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#190]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] tilde en la palabra creación del modulo

**Comment by ricardoavendano** [comment]
Comienzo de tarea

**Comment by ricardoavendano** [comment]
merge con dev 
commit 21bc300bce1321ab169c56ea243f3eda21c763c4

**Comment by fabianbarreto02** [comment]
Se revisa el ajuste solicitado
