### ISSUE TITLE
Ajustar en componente Habilitar perido / Habilitar/Deshabilitar un periodo, tamaño de letras, color botones y  Placeholder “Año de publicación” por solo “Año”

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#191]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] Tamaño de letra en el componente

- [x] Color de los botones de acuerdo a la paleta establecida

- [x] Placeholder  “Año de publicación” por solo “Año”

**Comment by ricardoavendano** [comment]
Inicio tareas

**Comment by ricardoavendano** [comment]
ajuste año de publicación por año 
commit 1419e682644bba1f9bfc2c3753ddd5ca2074fd52

**Comment by ricardoavendano** [comment]
fix: ajuste color botones y placeholder año de publicacion por año #200
https://github.com/udistrital/sga_cliente/pull/200/commits/1e76810a03b9a5151ddf7d7c49b6216c709988e2

**Comment by fabianbarreto02** [comment]
No se observa ajuste del tamaño de la letra, si se realizo el ajuste en otro commit o otra issue se debe poder la trazabilidad

**Comment by ricardoavendano** [comment]
Ajuste tamaño de letras
https://github.com/udistrital/sga_cliente/commit/4536ff50047f9ec5ba77a61a071f2c6da8398291

**Comment by fabianbarreto02** [comment]
Se revisa los ajustes correspondiente
