### ISSUE TITLE
Ajustar en componente Habilitar perido / Crear un periodo, tamaño de letras,   Placeholder “Año de publicación” por solo “Año”

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#192]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] Tamaño de letra del componete

- [x]  Placeholder “Año de publicación” por solo “Año”

**Comment by ricardoavendano** [comment]
fix: ajuste color botones y placeholder año de publicacion por año #200
1e76810

**Comment by fabianbarreto02** [comment]
No se observa ajuste del tamaño de la letra, si se realizo el ajuste en otro commit o otra issue se debe poder la trazabilidad

**Comment by ricardoavendano** [comment]
Ajuste tamaño de letras
4536ff5

**Comment by fabianbarreto02** [comment]
Se revisa los ajuste solicitados
