### ISSUE TITLE
Ajustar en componete oferta academica/ listar la oferta academica  color verde del botón “Consulta Oferta” por paleta establecida.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#193]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] Ajustar color botón "Consultar Oferta" por paleta establecida

**Comment by jupmorenor** [comment]
Se da inicio a la realización de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by fabianbarreto02** [comment]
Se revisa el ajuste solicitado
