### ISSUE TITLE
Ajustar en componente Proyecto académico/ Lista proyecto académico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#194]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] tamaño letra

- [x]  nombre submódulo se corta

- [x]  filtro tabla solo filtra por nombre debe filtrar por los otros campos

- [x]  color verde del reponsive del botón "Crear nuevo registro al proyecto académico" en la opción consulta/histórico registros/ agregar nuevo registro calificado y  registro de alta calidad por color establecidos en paleta

- [x] tilde en palabra Historico en la opción de la paleta

- [x] ordenar tabla por nombres, tamaño de tabla con cabe.

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea.

**Comment by jupmorenor** [comment]
Algunas consideraciones:

1. La corrección de la palabra `Histórico` quedó en el commit 4536ff5 ya que se estaba modificando el mismo archivo en el que se encontraba, igualmente la corrección del los nombres que se cortaban.
2. Se deja el filtro solamente sobre el nombre del proyecto curricular, pero si se mejora su función.
3. Se puede ordenar la tabla con algunas columnas: [Facultad, Activo, Vencimientos], la columna del nombre del proyecto tiene dificultad para aplicarle el ordenamiento.

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by jupmorenor** [comment]
Se agrega commit f694e90 con el ajuste que faltaba para poder ordenar la tabla por nombre de proyecto.

**Comment by fabianbarreto02** [comment]
Se revisa ajustes solicitados
