### ISSUE TITLE
Ajustar en componente Proyecto académico/ Registro de un proyecto académico, tamaño letras y nombre del sumódulo por que se corta 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#195]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] Ajustar tamaño de letra en el componente

- [x] nombre del sumódulo por que se corta

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Ajuste nombre del sumódulo por que se corta
https://github.com/udistrital/sga_cliente/commit/4536ff50047f9ec5ba77a61a071f2c6da8398291

**Comment by fabianbarreto02** [comment]
Se revisan los ajustes solicitados
