### ISSUE TITLE
Ajustar en componente Inscripcion/ preinscripción a proyectos académicos, Tamaño de letra y nombre del submódulo por que se corta.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#196]
Se debe ajustar el componente con los siguientes requerimiento:

- [x] Ajustar tamaño de letra en el componente

- [x] nombre del submódulo por que se corta.

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se revisa los ajustes solicitados
