### ISSUE TITLE
Ajustar en componente Inscripcion/ Inscripción a proyectos académicos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#197]
Se debe ajustar el componente con los siguientes requerimiento:

- [x]  Tamaño de letra del componente

- [x]  nombre del submódulo por que se corta

- [ ] revisar select de programa no carga nombre al seleccionar la primera vez.

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
tarea: nombre del submódulo por que se corta
https://github.com/udistrital/sga_cliente/commit/4536ff50047f9ec5ba77a61a071f2c6da8398291

**Comment by ricardoavendano** [comment]
fix: ajuste inscripcion proyectos academicos
commit 950ff86a1b50bb464cbb2ec8b4def6c8f3a294ee

**Comment by ricardoavendano** [comment]
El ajuste del select no se pudo completar en este sprint debido a que no solo hay problemas con el select del programa ya que el primer select del tipo de inscripción en algunos casos cuando se selecciona un ítem la lista de programas no se muestra, se debe mover esta tarea para un próximo issue

**Comment by fabianbarreto02** [comment]
Se deja incompleta la tarea, pues el análisis del problema del select no se ha podido establecer, se sugiere crear una tarea para arreglar este problema  y posiblemente cambiar el tipo select utilizado, se da por finalizada la issue
