### ISSUE TITLE
Fechas (registro y vencimiento) - revisar formato y calculo de fecha de finalización

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#20]
Crear función que permita agregar meses y años a una fecha con el fin de calcular el tiempo de vigencia de un registro y agregar la.
- [x] Se crea función que permite agregar meses y años a una fecha.
- [x] Agregar función al cliente para calcular vigencia de un registro.

**Comment by JuanPiedrahita** [comment]
Se crea función en golang para agregar años meses y dias a una fecha:

```go
package main

import (
	"fmt"
	"time"
)


func calculateEndDate (date time.Time, years int, months int, days int) time.Time {
	return date.AddDate(years, months, days)
}


func main() {
	startDate := time.Date(2009, 1, 1, 0, 0, 0, 0, time.UTC)
	endDate := calculateEndDate(startDate, 1, 1, 1)
	fmt.Println("Start date", startDate)
	fmt.Println("End date", endDate )
}
```

**Comment by JuanPiedrahita** [comment]
probar la funcipon de golang en https://play.golang.org/

**Comment by JuanPiedrahita** [comment]
Se crea función para javascrip, en el controlador de angular se debe importar primero moment

```typescript
import * as moment from 'moment';
```

La función es la siguiente:
```typescript
calculateEndDate (date: Date, years: number, months: number, days: number): Date {
    const convertDate = moment(date).add(years, 'year').add(months, 'month').add(days, 'day').format("YYYY-MM-DD HH:mm:ss");
    return new Date(convertDate);
  }
```

para validar el funcionamiento de la función:
```typescript
const initDate = new Date();
const endDate = this.calculateEndDate(initDate, 1, 1, 1)
console.log("init date", initDate);
console.log("end date", endDate);
```

**Comment by JuanPiedrahita** [comment]
Se tiene ocmo respuesta de la función. 
![imagen](https://user-images.githubusercontent.com/25555966/65620068-d396d500-df86-11e9-9092-bd8ca2621715.png)

**Comment by JuanPiedrahita** [comment]
Se da por terminada la creación de la función, @fabianbarreto02 por favor proceder con el resto de la tera.

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste de la función dada por @juancsr, se revisa el registro, se espera revisión por parte de @mafeave

**Comment by JuanPiedrahita** [comment]
> 
> 
> Se realiza el ajuste de la función dada por @juancsr, se revisa el registro, se espera revisión por parte de @mafeave

Mi nombre es @JuanPiedrahita jaja

**Comment by mafeave** [comment]
Se hace la revisión y la fecha carga en el navegador chrome.
