### ISSUE TITLE
Creación del componente para la construcción del calendario académico, agregar periodo académico, procesos y actividades.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#203]
Se debe realizar la creación del componte para el manejo del calendario académico siguiendo  el [mockup](https://docs.google.com/document/d/1wBdNMvz1v1ETFzHFIf3b1Ou-RK79AuXTCEYeonpr_H0/edit) desarrollado por nuestra analista, la issue debe cumplir con los siguiente requerimientos:

- [x] Se debe realizar el mockup o enmaquetados de los procesos definidos.

- [x] Crear el componente el cual lista los calendarios (Información quemada)

- [x] Crear componente para el registro del calendario, select de caledaria para, periodo academico,  botón agregar periodo y botones cargar los procesos y actividades de un cronograma anterior, boton definir los proceso y actividades.

- [x] Enlazar al botón agregar periodo al componete existente.

- [x] Componente, definición de proceso y actividades 

- [x] Componente registro de proceso

- [x] Componente del registro actividad

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea.

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se revisa creación de los mockup para creación de calendario, creación proceso y creación actividad
