### ISSUE TITLE
Ajustar en proyecto académico  problema del tipo de duración en la función de observar y modificar 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#207]
Se debe desarrollar realizar el ajuste en el componente proyecto académico, la issue debe cumplir con los siguiente requerimientos:

- [x] Revisar al momento de registro del proyecto académico en el select de tipo duración, que efectivamente se registra el id que tienen el registro "Semestral"

- [x] Revisar al momento de consultar el proyecto que tiene registrado tipo duración "semestral", que id se trae de consulta, revisar función que realiza la consulta del proyecto si realiza la correcta consulta.

- [x] Realizar los ajustes necesario para que funciones la consulta y la modificación.

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Se revisa consumo de servicioCORE_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/core_crud/v1/',

Se evidencia que este endpoint estaba apuntando a un servicio del proyecto planes tic, se modifica apuntamiento en WS02 y se cambia por el siguiente CORE_SERVICE: 'https://autenticacion.portaloas.udistrital.edu.co/apioas/core_crud/v2/',

Se realiza commit de ajuste en environments 
caca28059a82e8375b17d980a2558943f627ad95

**Comment by fabianbarreto02** [comment]
Se realiza el proceso de revisión de la isusue y se verifica el ajuste solicitado, se da por finalizado la issue
