### ISSUE TITLE
Ajustar el footer del cliente por la nueva formato 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#208]
Se debe ajusta el footer del cliente de sga, para posteriormente despliegue en ambiente de producción, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el componete footer guiándose del compotene del aplicativo [ARKA](https://pruebasarka.portaloas.udistrital.edu.co/#/pages/dashboard)

- [x] Realizar los ajustes correspondientes

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Se realiza el ajuste del footer con el formato de ARKA: https://pruebasarka.portaloas.udistrital.edu.co/#/pages/dashboard
Commit: fddf1ddd2ba4fb25ee5635928a1157623d09d42a

**Comment by fabianbarreto02** [comment]
Se realiza el proceso de ajuste del footer, se da por finaliza la issue
