### ISSUE TITLE
Ajustar funcionalidad en el cliente Crear calendario, crear proceso y crear actividad

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#209]
Se debe realizar la funcionalidad de los distintos componentes creados, se debe cumplir con los siguientes requerimientos:

- [x] Desarrollar el registro del calendario académico, con el api de eventos, junto al registro del documento, revisar los componente que tiene ese desarrollo implementado.

- [x] Desarrollar el registro de un proceso atado a su respectivo calendario académico  

- [x] Desarrollar el registro de un actividad atado a su respectivo calendario académico

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se realiza la revisión del funcionamiento en ambiente de pruebas, se da por finalizado la issue
