### ISSUE TITLE
Desarrollo cliente de consulta del tab de información básica de proyecto académico (8 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#21]
Se debe desarrollar un tab que se visualizace la informacion basica de los proyectos académicos registrados en el sistema,el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en el mockup.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea, se aclara que al momento de la consulta de un proyecto, el cliente esta programado para la consulta de un solo énfasis, se propone establecer una tarea adicional para desarrollar la parte de énfasis multiples.

falta revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica el funcionamiento del tab de consulta de información básica de un proyecto académico: 
![image](https://user-images.githubusercontent.com/14035745/65874338-36072100-e34b-11e9-8410-bc0d09ce1e7b.png)

Se recomienda ajustar el formulario para mostrar la información en 2 columnas, y hacer el ajuste para que se puedan consultar todos los énfasis relacionados.
