### ISSUE TITLE
Ajustar funcionalidad de la tabla de consulta 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#215]
Se debe realizar el desarrollo de la funcionalidad para el componente de consulta de calendario academico, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la consulta de información  por medio de un select que se carga los calendarios registrados y usar el endpoint determinado en la [issue](https://github.com/udistrital/sga_mid/issues/92)

- [x] Cargar la tabla con la infomación consultada

**Comment by ricardoavendano** [comment]
Realizar la consulta de información por medio de un select que se carga los calendarios registrados y usar el endpoint
commit: https://github.com/udistrital/sga_mid/pull/104/commits/1a33584303a1af772c838a4a68b568b1eeca81e4
commit: https://github.com/udistrital/sga_mid/pull/104/commits/b98a2c788d915fa4721392d0d387faff4d0c05ba

Cargar la tabla con la infomación consultada
commit: https://github.com/udistrital/sga_cliente/pull/244/commits/ddb95ce9bcb777b0690f6b0faa669249e12e3799

**Comment by fabianbarreto02** [comment]
Se revisa funcionalidad y se realiza el despliegue en pruebas
