### ISSUE TITLE
Crear componente para consulta de calendario académico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#216]
Se debe realizar el desarrollo  el componente de consulta de calendario academico, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el desarrollo del componente de acuerdo al [mockup](https://docs.google.com/document/d/1wBdNMvz1v1ETFzHFIf3b1Ou-RK79AuXTCEYeonpr_H0/edit)

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
se crea el componente para consultar el calendario academico
commit: https://github.com/udistrital/sga_cliente/pull/244/commits/ddb95ce9bcb777b0690f6b0faa669249e12e3799

**Comment by fabianbarreto02** [comment]
se revisa el desarrollo solicitado y se realiza en pruebas, falta ajustar el botón de visualizar el documento y realizar los ajuste visuales de la card
