### ISSUE TITLE
Ajustar función para inactivar un calendario academico 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#217]
Se debe realizar la funcionalidad en el cliente con el boton de inactivar un calendario academico, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear función para cambiar el estado del campo activo en el calendario seleccionado 

- [x] Mostrar mensaje de advertencia al realizar esta acción.

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Crear función para cambiar el estado del campo activo en el calendario seleccionado. OK
commit: https://github.com/udistrital/sga_mid/pull/126/commits/2fd62583d3fb7d659c1bfe20ad0d6b5569f64005

**Comment by ricardoavendano** [comment]
Mostrar mensaje de advertencia al realizar esta acción. Ok
https://github.com/udistrital/sga_cliente/commit/d44c3c005a0a0b76b964f39edc4b63edd8b1681a

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
