### ISSUE TITLE
Crear funcionalidad para cargar la información de los calendarios creados, procesos creados y las actividades creadas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#218]
Se debe crear la funcionalidad para que las tablas desarrolladas en los componetes se carguen con lo registrado en el api, la issue debe cumplir con los siguientes requerimientos:

- [x] Cargar la tabla de calendarios, con la información del api

- [x] Carga la tabla de proceso con la información relacionada a ese calendario registrada en api

- [x] Carga la tabla de actividades con la información relacionada a ese calendario registrada en api

- [x] Crear componente de tabla para registrar multiples publicos a una actividad

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se realiza revisión y al momento de crear un proceso se encuentra el siguiente erro 
![image](https://user-images.githubusercontent.com/43799065/99909239-43047380-2cb5-11eb-85cf-fc51e5e21dbe.png)

**Comment by fabianbarreto02** [comment]
Se revisa el ajuste del error, se da por finalizada y desplegada en test
