### ISSUE TITLE
Desarrollo cliente de edición del tab de información básica de proyecto académico (2 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#23]
Se debe desarrollar el tab de edición para la información básica de un proyecto académico.

lider técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
esta tarea hace parte del desarrollo de la #24, se debe desarrollar las dos tareas simultaneas para el correcto funcionamiento.

**Comment by mafeave** [comment]
Se verifica creación de tabs para la modificación de los datos de un proyecto académico:
![image](https://user-images.githubusercontent.com/14035745/65875651-4e783b00-e34d-11e9-9494-4c3b20e9d2ba.png)

La tarea continuará desde el issue #24
