### ISSUE TITLE
Ajustar función de crear actividad con nueva tabla en tipo publico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#230]
Se debe ajustar la funcionalidad de crear actividad con el nuevo modelo de eventos para almacenar varios tipo de publico a una actividad especificar, la issue debe cumplir con los siguientes requerimientos:
 

- [x] Ajustar el select de tipo publico con los datos del api

- [x] Realizar la función post para la nueva tabla

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by fabianbarreto02** [comment]
se da por termina el issue
