### ISSUE TITLE
Ajustar función para clonar calendario academico 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#231]
Se debe realizar la funcionalidad de la clonación de un calendario existente para ahorra tiempo al momento de construir los mismos procesos y actividades, sin fechas de inicio y fin, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar funcionalidad respecto al analisis hecho en la [issue ](https://github.com/udistrital/sga_mid/issues/93) para realizar el clon de un calendario particular.

- [x] Tener control en los campos fechas pues se genera vacías, mostrando un modal al generar el clonaje donde se le explique al usuario que se debe ingresar las fechas

- [x] Usar la función crear calendario establecido para dar finalización al proceso

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Desarrollar funcionalidad respecto al analisis hecho en la issue para realizar el clon de un calendario particular. OK

 Tener control en los campos fechas pues se genera vacías, mostrando un modal al generar el clonaje donde se le explique al usuario que se debe ingresar las fechas. OK

 Usar la función crear calendario establecido para dar finalización al proceso. OK

commit sga_cliente: 8d7bcc4fa812c5411d9debd775c109acd3a46604
commit sga_mid: https://github.com/udistrital/sga_mid/pull/126/commits/a5bbba4a64885b02538e7bb7f5990ba9fc234b12

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
