### ISSUE TITLE
Crear componente para habilitar los proyectos academicos al calendario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#232]
Se debe crear el componente para realizar la habilitación del calendario a los proyectos académicos siguiendo el [mockups](https://docs.google.com/document/d/1QYd6fWEp2u4cSCdRzFLEKHxgsm3w2-ex4Su2FMOADaI/edit), la issue debe cumplir los siguientes requerimientos:

- [x] Se debe desarrollar un componente nuevo que reusé  el componente de consulta de todos los calendarios académicos y después despliegue lo indicado en el mockups

- [x] La tabla de consulta debe cargar información cargada del api 

- [x] Ajustar la función put para registro

**Comment by jupmorenor** [comment]
Se da inicio con al solución de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se revisa la carga de datos en las tablas del componente, se despliega en pruebas y se da por finalizada la issue
