### ISSUE TITLE
Ajustar función para modificación en calendario academico existente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#234]
Se debe realizar una función que cuando se modifique un calendario el nuevo calendario revisa un documento nuevo donde se evidencie el documento e internamente se relacione con el calendario de donde se partio (calendario padre), finalmente se debe inactivar el calendario de donde se partio, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe partir de un calendario establecido

- [x] Se debe solicitar un documento nuevo donde se sustente el cambio del calendario 

- [x] se debe relacionar en el registro del nuevo calendario, el calendario anterior o calendario padre

- [x] Al realizar el registro del nuevo calendario se debe inactivar el calendario padre

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de la tarea

**Comment by gabrielablanco** [comment]
Se creo una función en el mid (feature/234) que agrega el calendario hijo y posteriormente desactiva el calendario padre que tiene asociado

**Comment by gabrielablanco** [comment]
Se crea un nuevo botón para añadir una nueva resolución (para crear un calendario hijo) partiendo de un calendario establecido; queda pendiente la actualización de la variable con el id del calendario hijo mientras se arreglan algunos conflictos en el cliente

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
