### ISSUE TITLE
Desarrollo de cliente, para modificación de proyectos académicos (16 horas) (2 semanas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#24]
Se debe desarrollar el cliente para realizar actualizacioón o modificación de un proyecto académico previamente registrado, el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en el mockup.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se implementa la modificacion para todas los tag del proyecto, por el momento se puede crear un creditacion de alta calidad, falta el manejo para traer la informacion cuando ya el proyecto ya cuenta con un registro actual, igual falta el manejo desde el mid para el manejo del ultimo registro de acreditacion y alta calidad, se espera revisión por parte @mafeave

**Comment by mafeave** [comment]
Se hace la prueba modificando el nombre de un proyecto, pero no se muestra alerta con el resultado:
![image](https://user-images.githubusercontent.com/14035745/66399929-194f9680-e9a6-11e9-9b78-ac27e4749353.png)

Respuesta en el mid:
![image](https://user-images.githubusercontent.com/14035745/66400048-5ddb3200-e9a6-11e9-992b-ad4d089db733.png)

**Comment by mafeave** [comment]
Se bloquean los campos de nombre y el código de SNIES en el formulario de modificación

**Comment by mafeave** [comment]
Se verifica restricción para modificar los campos de nombre y el código de SNIES en el formulario de edición. Se verifica modificación con cada uno de los campos disponibles para editar.

Se da por finalizada la tarea.
