### ISSUE TITLE
Crear o ajustar el componente para realizar la consulta del calendario por proyecto académico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#249]
Con ayuda de la función realiza en la [issue](https://github.com/udistrital/sga_mid/issues/95) se debe ajustar o crear un componente donde se pueda consultar el calendario academico que este relacionado a un proyecto, la issue debe cumplir con los siguientes requerimientos:

 

- [x] Realizar o ajustar un componente individual donde se pueda seleccionar el proyecto y se mire el calendario que tiene relacionado.

- [x] Realizar la funcionalidad para consultar y cargar el componente con la información requerida

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada issue
