### ISSUE TITLE
Agregar campo de "Se ofrece" para aspirantes, en el modelo de datos - 1 hora

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#25]
Teniendo en cuenta el manejo de un campo para el registro de la oferta del proyecto académico, se debe agregar un campo en el modelo de datos, se parte de la [issue](https://github.com/udistrital/sga_cliente/issues/9), el cual fue el ultimo modelo aprobado.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
Se agrega el campo oferta, de tipo bolean para el registro de la oferta del proyecto académico, de igual manera se quita el constraint  unique de la tabla titulación del campo nombre por sugerencias pasadas, finalmente se dejan todas las relaciones fk nn por sugerencia de @mafeave, los [archivos bases](https://drive.google.com/drive/folders/1ZDEI3Jfgv81DIRzCe8uOjW_o0uqg7Xuf)  estan en el drive referenciado.

**Comment by fabianbarreto02** [comment]
Se anexa imagen de modelo ajustado

![Proyecto_curricular_OKOS_V8](https://user-images.githubusercontent.com/43799065/65913380-6d9abb00-e395-11e9-8a4c-7bfeb8edfe20.png)

**Comment by fabianbarreto02** [comment]
Se anexa archivos base.

[Proyecto_academico_OIKOS_V8.zip](https://github.com/udistrital/sga_cliente/files/3673186/Proyecto_academico_OIKOS_V8.zip)

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se verifican los ajustes solicitados en el modelo de datos, se verifica ajuste en el script de migración del API proyecto_academico_crud. Se da por finalizada la tarea.
