### ISSUE TITLE
Ajustas funcionalidad para el registro de la actividad especifica asignada y establecer los limites de fechas para asignar dependiendo de la actividad padre

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#250]
Con la función creada en la [issue](https://github.com/udistrital/sga_mid/issues/113), se debe desarrollar la funcionalidad para la creación de una actividad hija, para esto se debe agregar un nuevo botón para asignar la actividad, debe tener las fechas que tiene asignada la actividad original pues las actividades hijas no pueden superar las fechas de la actividad padre, la issue debe cumplir con los siguientes requerimiento:

- [x] Debe establecer un rango de fechas en las que se puede asignar la actividad hija 

- [x] Debe realizar el registro de la actividad, tener en cuenta como se define el objeto en la   [issue](https://github.com/udistrital/sga_mid/issues/113)

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Se ajusta sga_cliente el componente actividad_calendario_academico para que cuando una actividad que es hija de otra actividad el rango de fechas este entre los rangos de la actividad padre
commit: https://github.com/udistrital/sga_cliente/commit/3ef73257cef8dc618e06be131ec4d73cae26fe3a

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
