### ISSUE TITLE
Crear componente para la gestión de los conceptos pecuniarios

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#252]
Se debe realizar los componentes definidos en el [mockups](https://docs.google.com/document/d/1s41Jqd06-I4hfOJR-lWTZ2NoRBnrf_IVaD_6w_4t8TA/edit) sin funcionalidad , copiar conceptos, definir conceptos, modal de información, agregar un nuevo /edición derecho pecuniario y consulta de asignación del valor, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar el mockups de copiar conceptos

- [x]  Desarrollar el mockups de modal de información

- [x] Desarrollar el mockups de agregar un nuevo /edición derecho pecuniario 

- [x] Desarrollar el mockups de consulta de asignación del valor

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
