### ISSUE TITLE
Agregar campo de "Se ofrece" para aspirantes, en el API - 4 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#26]
Por ajustes de #25  se debe ajustar el [api proyecto_academico_crud](https://github.com/udistrital/proyecto_academico_crud/tree/feature/transacciones_registro), se debe realizar los siguientes ajustes:

- [x] Ajustar el modelo del controlador Proyecto_academico_institucion por cambio en el modelo de datos.
- [x] Ajustar el script de migrations por cambio del modelo de datos.

- [x] Correguir el campo donde se registra a nivel cliente 

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza el primer check de la issue este se puede observar en el siguiente link https://github.com/udistrital/proyecto_academico_crud/commit/88469c47027b8bdbc6fe13910d8422fd07d13b65

**Comment by fabianbarreto02** [comment]
Se realiza el segundo check de la issue el cual se puede observar en el siguiente link https://github.com/udistrital/proyecto_academico_crud/commit/4eff410c7ccb3af0042c732be0c44adf2fb1f1a8

**Comment by fabianbarreto02** [comment]
Se realiza la correcion en el cliente, se da por finalizada la tarea, se espera revisión por parte de la lider técnica @mafeave

**Comment by mafeave** [comment]
Se revisa ajuste del campo en el modelo del API y del cliente. Se da por finalizada la tarea.
