### ISSUE TITLE
Realizar la funcionalidad para la creación de actividades hijas desde el componte de consulta de calendario a un proyecto

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#264]
Se debe realizar la funcionalidad para crear una actividad hija desde el componente buscar calendario por proyecto, desde aquí se debe crear un botón donde se registre la actividad hija y se consuma la función de creación de la actividad, desde esta vista se debe mostrar todas las activadas que tiene registrado el proyecto de consulta, la issue debe cumplir con los siguientes requerimientos:

- [x]  Crear un botón donde se permita ingresar una actividad de hija de una actividad existente desde el componente buscar calendario por proyecto

- [x] Desde el componente buscar calendario por proyecto se debe mostrar en su totalidad el calendario con actividades padres e hijas a un proyecto particular

**Comment by ricardoavendano** [comment]
Se ajusta desde el cliente la consulta de las actividades por calendario, en el calendario general solo aparecen las actividades padre, en el detalle aparecen tanto las actividades padre e hijas. Desde el componente de buscar se puede crear una actividad hija 
commit
udistrital/sga_cliente@812c5a7

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
