### ISSUE TITLE
Realizar funcionalidad para el registro de los conceptos pecuniarios y la cara de información existente en la base de datos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#265]
Se debe realizar la funcionalidad para consumir el servicio realizado con en api mid, después de realizar el registro se debe cargar la tabla con los datos registrados, también consumir los servicio para el select de vigencia y salario mínimo, la issue debe cumplir con los siguientes requerimientos :

- [x] Realizar la funcionalidad desde el cliente (JSON)  para el registro, modificación e inactivar un concepto 

- [x] Cargar componente con la información registrada en el api 

- [x] Consumir el [servicio](http://pruebasapi.intranetoas.udistrital.edu.co:8205/v1/salario_minimo/?limit=0) para cargar select de vigencia y salario minimo , despues se debe consumir el servicio de parametros_crud

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
