### ISSUE TITLE
Realizar funcion de calcular valores en cascada y realizar el registro de los costos en el api de parametros_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#266]
Se debe realizar la función a nivel de mid para realizar el calculo del costo con el factor  establecido y el salario minimo establecido para la vigencia para todos los conceptos que este registrados, para luego realizar el posterior registro de los costos en el api de parametros_crud, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar función a nivel de cliente que reciba los conceptos que este en esa vigencia, el salario minino en esa vigencia y el factor, debe calcular el costo con la formula definida en el [mockup](https://docs.google.com/document/d/1s41Jqd06-I4hfOJR-lWTZ2NoRBnrf_IVaD_6w_4t8TA/edit)

- [x] Una vez calculada se debe realizar el registro de los costos a cada uno de los conceptos recibidos

- [x] A nivel de cliente se debe actualizar el componente con los costos y utilizar la función para el registro de masivo de costos del concepto

**Comment by gabrielablanco** [comment]
Se da por finalizada esta tarea

**Comment by fabianbarreto02** [comment]
se da por finaliza la issue
