### ISSUE TITLE
Realizar función y funcionalidad para realizar el clonado de los conceptos desde una vigencia anterior 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#268]
Se debe desarrollar la función y la funcionalidad para poder clonar los conceptos de una vigencia anterior, se selecciona la vigencia se consulta los conceptos se realiza el registro de los conceptos con factores sin costos y se carga el componente del cliente, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear función en el mid donde reciba el id de la vigencia anterior y la nueva y consulta todos los conceptos realcionas con la vigencia antigua y genere los conceptos a la nueva vigencia

- [x] Realizar la funcionalidad del cliente para la función

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se realiza función de clonación de conceptos en [sga_mid](https://github.com/udistrital/sga_mid/commit/2b66314431a38103d2315ee0af288acdd457f2cf)

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
