### ISSUE TITLE
Agregar funcionalidad para modificar y consultar los enfasis para información básica de proyecto académico

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#27]
Agregar funcionalidad que permita modificar y consultar los enfasis de un proyecto teniendo en cuenta el desarrollo que permite por listas agregar los enfasis.
- [x] El sistema permite consultar los enfasis de un proyecto.
- [x] El sistema permite modificar los enfasis de un proyecto.

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea

**Comment by mafeave** [comment]
Se hace la verificación, pero no está cargando los énfasis en el formulario de edición:
![image](https://user-images.githubusercontent.com/14035745/66400312-e063f180-e9a6-11e9-806e-abcf294f7e65.png)
