### ISSUE TITLE
Inhabilitar proyecto académico

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#28]
Agregar funcionalidad que permita inhabilitar un proyecto academico.
- [x] El sistema permite inhabilitar un proyecto academico.

**Comment by JuanPiedrahita** [comment]
Se termina con la inactivación del proyecto academico.

**Comment by mafeave** [comment]
Se verifica funcionalidad para la inactivación de un proyecto académico, los campos de activo y oferta quedan con el valor de false:
![Captura de pantalla de 2019-10-08 07-49-21](https://user-images.githubusercontent.com/14035745/66396995-87915a80-e9a0-11e9-9bd1-18396e6abf21.png)

Ajustar el mensaje que aparece al seleccionar la opción de inactivar, en ves de decir "Actualizar" que diga "Inactivar" o "Inhabillitar":
![image](https://user-images.githubusercontent.com/14035745/66397083-b3144500-e9a0-11e9-9ab3-f6bb4ba20ffb.png)

**Comment by mafeave** [comment]
Se verifica ajuste solicitado:
![image](https://user-images.githubusercontent.com/14035745/67159176-d9be6e00-f306-11e9-87b5-4ede354028cb.png)

Se da por finalizada la tarea.
