### ISSUE TITLE
Ajustar el componente de información personal con los ajustes requeridos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#280]
Se debe ajustar el componente de información personal en el menú de inscripción/preinscripción/información básica se debe retirar los campos de foto y Documento de identificación para subir archivos, también se debe el campo para la fecha de expedición de documento junto a su funcionalidad,  realizar el registro en el api de tercero en la tabla de datos de identificación, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe quitar los campos de foto y Documento de identificación para subir archivos

- [x] Incluir el campo para  la fecha de expedición de documento

- [x] Revisar y ajustar la tr que se encarga de hacer el registro de la información  y realizar el registro de la información

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta tarea

**Comment by fabianbarreto02** [comment]
se da por terminada la issue
