### ISSUE TITLE
Ajustar orden de ejecución del componente de información personal para usuarios nuevos y ajustar la vista

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#281]
Se debe ajustar el componente  de información personal para que cuando es un usuario nuevo en tercero se ejecute al entrar al menú de preinscripción a proyectos académicos muestre de primeras el formulario de ingreso de información personal, si ya existe información en el api de tercero se debe mostrar el mismo componente con información registrada  y pedir verificar la información, posteriormente desarrollar el componente embebido,  tener en cuenta  el [mockup](https://docs.google.com/document/d/1HO-8t_EFPZNmWb7GJmp-BGDbSV5bDGvG02LM5sKaYb4/edit), se debe ajustar la vista como el mockup, la issue debe cumplir con los siguientes requerimientos:
 

- [x] Ajustar el componente con el nuevo orden de ejecución para la ejecución}

- [x] Revisión de información del tercero, se tiene que realizar la simulación del tercero 

- [x] Creación del componente como el mockup

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Se realizan ajustes segun issue en el commit
37d7140

**Comment by fabianbarreto02** [comment]
ajustar que el boton y tabla de recibos aparezca despues de seleccionar la carrera y el tipo de iscripción

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
