### ISSUE TITLE
Ajustar la carga del select para los proyectos academicos con el servicio del api de proyecto_academico_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#282]
Se debe ajustar el select con el servicio de carga del select de la carrera con el api de proyecto_academico_crud y realizar el filtrado de los proyectos por nivel del proyecto (pregrado/posgrado), también tener en cuenta solo cargar los proyectos que cuenta con una actividad  activa de proceso de inscripción de aspirantes, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el select con el servicio indicado 

- [x] Ajustar el filtrado de los  proyectos por nivel 

- [x] Cargar los proyectos que tengan la actividad registrada de proceso de inscripción de aspirantes

**Comment by ricardoavendano** [comment]
Se realizan ajustes segun issue en el commit 
https://github.com/udistrital/sga_cliente/commit/37d7140eece1421dcec27b6024bb56c847ab5602

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
