### ISSUE TITLE
Traer  fechas de pago para la inscripción del modulo de calendario académico establecidas para el proyecto seleccionado, consultar el valor del api de concepto pecuniarios para la inscripción y construir json necesario para la creación del recibo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#283]
Se debe crear el json para necesario para la creación del recibo de pago para inscripción, se debe consultar las fechas establecidas en la actividad  de inscripción, y el valor del derecho pecuniario de inscripción y realizar la construcción del json necesario para la generación del recibo, la issue debe cumplir con los siguientes requerimientos:

- [x] Consultar fechas de la activadad de inscripcion al proyecto particulas 

- [x] consultar el valor de derecho pecuniario para inscripción dependiendo del nivel 

- [x] Construir el JSON con la siguiente información:
`{
"NombreDelAspirante":"nombre_aspirante",
"DocumentoDelAspirante": "documento_aspirante",
"ProyectoAspirante": "proyecto_aspirante",
"Periodo":"periodo",
"Descripcion": "nombre_derecho_pecuniario",
"ValorDerecho":"valor_derecho_pecuniario",
"Fecha_pago": "fecha_actividad_consultada"
`

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by fabianbarreto02** [comment]
no se evidencia solución de la issue, mostrar una captura de la creación

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
