### ISSUE TITLE
Generar un registro a partir de un proyecto existente. Fechas, nombres y codigo SNIES en ceros. Sólo queda información básica del proyecto

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#29]
Agregar funcionalidad que permita generar un registro de un proyecto academico a partir de otro.
- [x] El sistema permite crear un proyecto academico con la información de otro.

**Comment by JuanPiedrahita** [comment]
Se permite crear un proyecto a partir de uno existente.

**Comment by mafeave** [comment]
Se hace la prueba de la funcionalidad, se permite clonar el proyecto en un nuevo formulario, pero al guardar la información sale el siguiente error:
![Captura de pantalla de 2019-10-08 08-15-10](https://user-images.githubusercontent.com/14035745/66398929-426f2780-e9a4-11e9-8403-40f240062d2c.png)

Error en el API de proyecto_academico_crud:
![image](https://user-images.githubusercontent.com/14035745/66399051-7c402e00-e9a4-11e9-81c1-9203f636349f.png)

**Comment by mafeave** [comment]
Se verifica:
- Ajuste para carga del campo de teléfono.
- No cargar los datos de Resolución (Número y Año), Fecha de creación, ni información de la vigencia.
- No llenado de la información en la sección de: Acto administrativo por medio del cual se crea el proyecto académico por parte del Consejo Superior Universitario

Se hace registro de nuevo proyecto a partir de uno existente, se da por finalizada la tarea.
