### ISSUE TITLE
Ajustes definidos en el modulo de calendario académico realizados por la analista

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#296]
Se debe realizar los [ajustes ](https://github.com/udistrital/sga_cliente/issues/291)sugeridos por @mafeave  en el modulo de calendario academico, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar los ajustes sugeridos en la issu #291

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Lista de ajustes a realizar:

- [ ] Agregar tooltips a iconos de la lista de calendarios
- [ ] Retirar columna de IDs de calendarios
- [ ] Ajustar color de la letra del botón "Guardar"
- [ ] Restringir los valores a ingresar en los campos de Resolución y Año de la resolución
- [ ] Ajustar mensaje de alerta al modificar un proceso
- [ ] Ajustar actualización de procesos
- [ ] Ajustar inactivación de procesos
- [ ] Ajustar mensaje de alerta al modificar una actividad
- [ ] Ajustar actualización de actividades
- [ ] Ajustar inactivación de actividades
- [ ] Revisar y ajustar el formato de las fechas en los campos de fechas en el dialogo Actividad.
- [ ] Revisar carga duplicada de actividades
- [ ] Agregar spinner de carga al formulario de editar/crear calendarios
- [ ] Ajustar color de la letra del botón "Agregar" al administrar los tipos de público
- [ ] Cambiar mensaje de "eliminar" calendario por inactivar
- [ ] No permitir asignar el calendario a los proyectos si no tiene procesos y actividades relacionadas
- [ ] Reducir tamaño del modal
- [ ] Optimizar carga de calendario al editar

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
