### ISSUE TITLE
Desarrollo del modulo de gestión de tipos de inscripción y ajuste de api de inscripción con nuevo campo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#297]
Se debe desarrollar el componente para el modulo de gestión de tipos de inscripción de acuerdo al [mockup](https://docs.google.com/document/d/1Ocgig6cEZmaJObqFB0wuG9mhZay9HSO6QnJ1iOCBjRo/edit), tambien se debe desarrollar la funcionalidad del post, put y delet(inhabilitar un tipo), esto de debe registrar en el api de [inscripción_crud ](https://github.com/udistrital/inscripcion_crud), se debe crear un nuevo campo en la tabla tipo_inscripcion llamado especial de tipo boolean para el registro de inscripciones especiales, la issue debe cumplir con los siguiente requerimientos:

- [x] Ajustar el modelo de datos con el nuevo campo en la tabla tipo_inscripcion llamado "especial" de tipo boolean

- [x] Realizar la documentación del ajuste del modelo de datos (sql, imagen) en la[ carpeta del modelo](https://drive.google.com/drive/u/0/folders/17UorN10whw5G2KopsRBHr4T9CNoKEiip) con una versión

- [x] Realizar el ajuste del api de inscripcion_crud con los ajustes realizados en el modelo y las migraciones

- [x] Desarrollo del mockups dado por el analista en un submenu del menu de administración 

- [x] Desarrollar el funcionamiento de post, put y inhabilitar algún tipo de inscripción

**Comment by ricardoavendano** [comment]
Se crea documentacion con el nuevo campo especial en la tabla tipo_inscripcion
https://drive.google.com/drive/u/0/folders/13Ho2PQTcdU2f3ud8QY8c9BjfF_-Jv9h7

Se crea campo especial en la tabla tipo_inscripcion en inscripcion_crud
https://github.com/udistrital/inscripcion_crud/pull/50

**Comment by ricardoavendano** [comment]
Se realiza nuevo componente en sga_cliente
commit: 1726c27

**Comment by fabianbarreto02** [comment]
No se actualiza el cupo especial, cuando se cambia de valor, si en la tabla se observa un "si" cuando es un cupo especial

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
