### ISSUE TITLE
Revisión del tag de información básica en la inscripción de una aspirante de posgrado  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#298]
Se debe ajustar el tag completo con las funciones de registro, consulta de información si existe en el tag de información basica (información caracteristica, información de contacto, información familiar) y la función put si llegara queda algo mal, la issue debe cumplir con los siguientes requerimientos:

- [ ] Revisar por el seletc de proyecto al ser selecionado por primera vez no queda cargado

- [x] Revisar y ajustar las tr definas a nivel de mid para casa subtag

- [x] Ajustar el registro de cada subtag en el api de [terceros](https://github.com/udistrital/terceros_crud), tener en cuenta el [excel ](https://docs.google.com/spreadsheets/d/1TSZGbbNIvKB4wXtzI0LFNCIxgV6XR0TiZ5Odp1Xf0Bw/edit#gid=150352529)

- [x] Si el usuario registrado ya tiene data se debe cargar los subtags con la información registrada 

- [ ] Se debe poder realizar un put si alguna información se modifica

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta tarea

**Comment by gabrielablanco** [comment]
Se da por finalizada la tarea 
Se tiene en cuenta que el select debe es cargarse por lo que no es necesario ese punto y las no existen funciones put por lo que queda esta parte para una próxima tarea.

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
