### ISSUE TITLE
Ajuste de registro de los periodos y ajuste de consulta de los periodos del api core_crud a Parametros

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#313]
Se debe realizar el proceso de ajustes para realizar el registro del periodo en el api de parametros y no al api de core_crud, tambien se debe realizar el ajustes en la consulta de los select de los periodo con la nueva api, estos son:

- Periodo en el componente del agregar, clonar calendarios academicos
- Periodo en el componente en preinscrito a un proyecto academico

La issue debe cumplir con los siguiente requerimientos:

- [x] Realizar el ajuste del registro de los periodos en los componente de agregar periodo en el modal al crear el calendario y el componente de crear un periodo en el menu de habilitar periodo
- [x] Realizar el ajuste de la carga de los componte antes mencionados

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea.
