### ISSUE TITLE
Ajuste de manejo de los registros en el tag de formación academica en inscripcion 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#314]
Se debe realizar el ajuste del tag de formación académica para migrar el registro del subtag de formación académica del api de formacion_academica ha un grupo de información del api de terceros de el modelo de datos de terceros, se debe tambien ajustar la consulta por medio del nit se cargue con la consulta del api de terceros con la tabla de rompimientos [tercero_tipo_tercero](https://github.com/udistrital/terceros_crud/blob/test/sql/Terceros_Schema.png) que consulte las universidades registradas en el sistema, si existe debe traer la información registrada en el sistema, también se debe registrar toda la información,  agregar la tabla donde se lleva el registro de la formación académica, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar ajuste de consulta de las universidades registradas en el api de terceros por nit y por nombre
- [x] Cagar la información de la universidad registrada en los campos de nombre, pais, direccion, correo, telefono 
- [x] Ajustar el registro (backend y cliente) para que el registro de el subtag de formación académica en el api de terceros, se debe crear el grupo de información complementaria(formacion academica) e información complementaria (información particular, fechas, programa academico, descripción), para la información de la universidad crear una información complementaria para que se registre el id del tercero universidad
- [x] Ajustar el migrations para la creación de el grupo_info_complementaria y las info_complementaria en el api de tercero
- [x] Documentar en el [documento](https://docs.google.com/spreadsheets/d/1TSZGbbNIvKB4wXtzI0LFNCIxgV6XR0TiZ5Odp1Xf0Bw/edit#gid=0) los grupo_info_complementaria y las info_complementaria creados

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
No se evidencia el pull requests de la migración el api de tercero_crud

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
