### ISSUE TITLE
Ajuste de manejo de los registros  en el tag de Experiencia laboral en inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#315]
Se debe realizar el ajuste del tag de  Experiencia laboral para migrar el registro del api de experiencia_laboral_crud ha un grupo de información del api de terceros de el modelo de datos de terceros, se debe tambien ajustar la consulta por medio del nit se cargue con la consulta del api de terceros con la tabla de rompimientos [tercero_tipo_tercero](https://github.com/udistrital/terceros_crud/blob/test/sql/Terceros_Schema.png) que consulte las empresas registradas en el sistema, si existe debe traer la información registrada en el sistema, también se debe registrar toda la información, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar ajuste de consulta de las empresas registradas en el api de terceros por nit y por nombre
- [x] Cagar la información de la empresa registrada en los campos de nombre, pais, direccion, correo, telefono, tipo de organización  
- [x] Ajustar el registro (backend y cliente) para que el registro de el subtag de experiencia profesional  en el api de terceros, se debe crear el grupo de información complementaria(Experencia laboral) e información complementaria (información particular, fechas, tipo de dedicación, tipo vinculacion, cargo y descripcion  ), para la información de la empresa crear una información complementaria para que se registre el id del tercero empresa
- [x] Ajustar el migrations para la creación de el grupo_info_complementaria y las info_complementaria en el api de tercero
- [x] Documentar en el [documento](https://docs.google.com/spreadsheets/d/1TSZGbbNIvKB4wXtzI0LFNCIxgV6XR0TiZ5Odp1Xf0Bw/edit#gid=0) los grupo_info_complementaria y las info_complementaria creados

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Ajustes en cliente y mid
https://github.com/udistrital/sga_mid/pull/201
https://github.com/udistrital/sga_cliente/pull/354

Ajustar el migrations para la creación de el grupo_info_complementaria y las info_complementaria en el api de tercero

**Comment by ricardoavendano** [comment]
Ajustar el migrations para la creación de el grupo_info_complementaria y las info_complementaria en el api de tercero
https://github.com/udistrital/terceros_crud/pull/54

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
