### ISSUE TITLE
Ajuste de manejo de los registros en el tag de formación academica  subtag de idiomas en inscripcion 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#316]
Se debe realizar el ajuste del tag de formación académica para migrar el registro del subtag de Idioma del api de idiomas_crud ha un grupo de información del api de terceros de el modelo de datos de [tercero](https://github.com/udistrital/terceros_crud/blob/test/sql/Terceros_Schema.png), se debe registrar toda la información,  ajustar  la tabla donde se lleva el registro de los idiomas registrados, cambiar el orden primero la tabla despues el formulario, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el registro (backend y cliente) para que el registro de el subtag de idiomas en el api de terceros, se debe crear el grupo de información _complementaria(Idiomas) e información complementaria (información particular, idiomas, nivel de escritura, nivel de escucha, nivel de habla, nivel de lectura, clasificación de idioma).
- [x] Ajustar el migrations para la creación de el grupo_info_complementaria y las info_complementaria en el api de tercero
- [x] Documentar en el [documento](https://docs.google.com/spreadsheets/d/1TSZGbbNIvKB4wXtzI0LFNCIxgV6XR0TiZ5Odp1Xf0Bw/edit#gid=0) los grupo_info_complementaria y las info_complementaria creados

**Comment by jupmorenor** [comment]
Se da inicio con esta tarea

**Comment by jupmorenor** [comment]
Luego de revisar la forma de adaptar los datos de idiomas al modelo de Terceros se determina por parte del líder técnico y el arquitecto que es mejor que esta información se mantenga en la API de idiomas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
