### ISSUE TITLE
Ajustar consulta para el tag de formación académica con la información registrada al tercero en el api de tercero  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#331]
Se debe realizar una función a nivel de mid para consultar toda la información de formación académica registrada en tercero, esta función debe traer la información de la formación académica seleccionada en la tabla donde van a estar todos los registros del tercero, cuando se seleccione cual consultar el formulario debe auto llenarse con la información registrada, la issue debe cumplir con los siguientes requerimientos:
 

- [x] Realizar una función a nivel de mid que consulte la información complementaria seleccionada 
- [x] Ajustar función para que realice la consulta seleccionada en la tabla de formación académica
- [x] Ajustar que el formulario se llene con la información del formación académica

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta tarea

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
