### ISSUE TITLE
Ajustar consulta para el tag de experiencia laboral con la información registrada al tercero en el api de tercero

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#332]
Se debe realizar una función a nivel de mid para consultar toda la información de experiencia laboral registrada en tercero, esta función debe traer la información de la experiencia laboral seleccionada en la tabla donde van a estar todos los registros del tercero, cuando se seleccione cual consultar el formulario debe auto llenarse con la información registrada, la issue debe cumplir con los siguientes requerimientos:
 

- [x] Realizar una función a nivel de mid que consulte la información complementaria seleccionada 
- [x] Ajustar función para que realice la consulta seleccionada en la tabla de experiencia laboral
- [x] Ajustar que el formulario se llene con la información del experiencia laboral

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Se ajusta sga_mid controlador GetExperienciaLaboralByTercero
Commit: https://github.com/udistrital/sga_mid/pull/221

Se ajusta sga_cliente para mostrar la experiencia laboral del usuario en sesion
Commit: https://github.com/udistrital/sga_cliente/pull/391

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
