### ISSUE TITLE
Ajustar consulta para el tag de idiomas con la información registrada al tercero en el api de idiomas_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#334]
Se debe realizar una función  para consultar toda la información de idiomas registrada en idiomas_crud, esta función debe traer la información de la idiomas  seleccionada en la tabla donde van a estar todos los registros del tercero, cuando se seleccione cual consultar el formulario debe auto llenarse con la información registrada, la issue debe cumplir con los siguientes requerimientos:
 

- [x] Ajustar función para que realice la consulta seleccionada en la tabla de idiomas 
- [x] Ajustar que el formulario se llene con la información del idiomas

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
