### ISSUE TITLE
Realizar los ajustes realizados por analista de requerimientos en el modulo de derechos pecunarios

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#336]
Se debe realizar el ajustes a los problema encontrados por @mafeave, estos están definidos en la [issue](https://github.com/udistrital/sga_cliente/issues/318), también se debe ocultar en el menú las opciones de producción académica y eventos, la issue debe cumplir con los siguientes requerimientos:

- [x] Ocultar las opciones de producción académica y eventos en el cliente
- [x] Realizar todos los ajustes definidos en la issue #318  en el componente de derechos pecuniarios

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
- [ ] Mostrar valores con formato de moneda.
- [ ] Corregir mensaje cuando no hay conceptos al consultar.
- [ ] Validar campos de creación de conceptos para limitar los valores.  
- [ ] Agregar mensaje de confirmación al modificar.
- [ ] No cargar conceptos inactivos.
- [ ] Actualizar tabla al modificar/inactivar conceptos.
- [ ] Corregir digitación en mensaje de inactivación de concepto.
- [ ] Revisar cálculo para conceptos especiales (Sistematización: S*F)
- [ ] Redondear valores a múltiplos de 100 (fotocopias a múltiplos de 50)

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
