### ISSUE TITLE
Asignación del coordinador al proyecto para proyecto académico, en el Tab de edición (definir quien registra las coordinaciones) - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#34]
Se debe crear el card donde se haga el manejo del registro del coordinado, el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en el mockup.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza la asignación de un coordinado aun proyecto académico, se expone la necesidad de cuadra el mid para traer la información del ultimo coordinador asignado, se espera revisión por parte @mafeave

**Comment by mafeave** [comment]
Se hace el registro de un coordinador, pero se está presentando el siguiente error:
![image](https://user-images.githubusercontent.com/14035745/66400760-b0691e00-e9a7-11e9-8c6b-79ac4b8d6979.png)

**Comment by mafeave** [comment]
El error se está presentando debido a los ajustes que se están haciendo mediante el issue https://github.com/udistrital/sga_cliente/issues/35

**Comment by mafeave** [comment]
Se veirfica registro del coordinador, se asigna y se consulta el proyecto para validar que se liste el coordinador asignado:
![image](https://user-images.githubusercontent.com/14035745/67147177-197a4c80-f258-11e9-96f6-de9d540d60a0.png)
