### ISSUE TITLE
Para asignar coordinador para proyecto académico, en el Tab de edición, configurar el API - 3 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#35]
Teniendo en cuenta la issue #34, donde se observo la falta del campo fecha de inicio en la asignación del coordinador al proyecto académico, se debe crear el campo en el modelo de datos y actualizar el [API](https://github.com/udistrital/proyecto_academico_crud/tree/feature/transacciones_registro), la issue debe cumplir con los siguientes requerimientos:

- [x] Actualizar el modelo de datos, anexar la nueva versión del modelo.
- [x] Actualizar la Api agregando el campo en el modelo y ajustar el controlador correspondiente.
- [x] Actualizar el scripts para beego migrations.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del modelo, en el [drive](https://drive.google.com/drive/folders/1fkQtK4dfDAciPboWMhRhqmGWNz3HP0Bx), se encuentra los archivos fuente del ajuste del modelo.

**Comment by fabianbarreto02** [comment]
Se realiza el segundo check de la issue esta se demuestra en el [commit](https://github.com/udistrital/proyecto_academico_crud/commit/691eb3088de44b21dd4615da5f6a718d4da411b9)

**Comment by fabianbarreto02** [comment]
Se realiza el tercer check de la issue, esta se demuestra en el [commit] (https://github.com/udistrital/proyecto_academico_crud/commit/f18d6abe990c1675a73026b59b61f7116606aa44).

**Comment by fabianbarreto02** [comment]
Se realiza la prueba con swagger y bee migrations de la issue con resultados positivos, se da por finalizado la issue, se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se veirfica registro del coordinador, con fecha de inicio de asignación:
![image](https://user-images.githubusercontent.com/14035745/67147177-197a4c80-f258-11e9-96f6-de9d540d60a0.png)

Observaciones:
- Ajustar nombre de la llave foránea de la tabla de proyecto_academico_rol_persona_dependecia
- Evaluar si se debe agregar un campo de fecha_finalizacion en la tabla de proyecto_academico_rol_persona_dependecia, para saber hasta que día estuvo activo el coordinador para el proyecto

**Comment by mafeave** [comment]
Ajustes realizados mediante los issues: https://github.com/udistrital/proyecto_academico_crud/issues/7 y https://github.com/udistrital/sga_mid/issues/19
