### ISSUE TITLE
Desarrollar la funcionalidad del método put para el tag de Información Básica en el proceso de inscripción posgrado

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#350]
Se debe desarrollar la funcionalidad del método put para el tag de Información Básica en el proceso de inscripción posgrado, para que el aspirante pueda actualizar algún registro realizado previamente en el tag de Información Básica, se debe desarrollar la función a nivel de mid para hacer el put de los datos previamente seleccionado de la tabla que contiene todos los registros del tercero en cuestión, la issue debe cumplir con los siguientes requerimientos:

- [x] Capturar el item de la tabla donde reposa la información del tercero en cuestión 

- [x] Se debe desarrollar una función en el SGA_MID, para que realice la actualización del registro seleccionado  

- [x] Actualizar el formulario con la información cambiada

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
