### ISSUE TITLE
Desarrollar funcionalidad para el al momento de crear un recibo en preinscripción del aspirante se realice el registro de la información en el api de inscripcion_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#352]
Se debe desarrollar la funcionalidad para que al momento de generar un recibo de inscripción por parte del aspirante se realice el registro de la siguiente información en el api de [inscripcion_crud](https://github.com/udistrital/inscripcion_crud/tree/develop):

- persona_id= Id tercero que esta previamente registrado en el api de terceros
- programa_academico_id= Id del programa previamente selecciónado por el aspirante( se puede modificar al momento de inscripción)
- recibo_inscripcion_id= Temporalmete se registra un id quemado mientras se define el servicio del recibo 
- periodo_id= id del periodo previamente seleccionado por el sistema y consultado en el api de parametros_crud
- acepta_terminos= registra bandera en true pues el aspirante debe aceptar los terminos cuando crea el tercero
- fecha_aceptacion= fecha en la cual se acepta los terminis
- tipo_inscripcion_id= id de tipo de inscripción seleccionado por el aspirante
- estado_inscripcion_id= id del estado aspirante 

Se debe registrar e informa si el aspirante intenta registrar una inscripción con el mismo programa académico, si esto pasa debe mostrar un modal donde informe que no puede realizar doble inscripción al mismo programa, tambien solo se permitirá la creación  de tres recibos y tres registros en el api de inscripción_crud, al intentar una cuarto recibo se debe notificar con un modal informado que solo puede generar maximo tres recibos y que debe pagar primero los generados para poder generar mas recibos, este se debe manejar desde el cliente o consultando el api de  inscripción_crud, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el registro en el api de inscripción_crud cada vez que se genere un recibo con la información indicada 
- [x] Manejar el excepción de no poder inscribirse dos veces al mismo programa
- [x]  Manejo de excepción de solo se permitirá la creación  de tres recibos y tres registros en el api de inscripción_crud, al intentar una cuarto recibo se debe notificar con un modal informado que solo puede generar maximo tres recibos y que debe pagar primero los generados para poder generar mas recibos, este se debe manejar desde el cliente o consultando el api de  inscripción_crud

**Comment by ricardoavendano** [comment]
Se realiza desarrollo en sga_cliente
commit: https://github.com/udistrital/sga_cliente/pull/396

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
