### ISSUE TITLE
Realizar los mockups para el modulo de Actualización de datos, menú, Solicitud Estudiante y Estudiante solicitud en proceso

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#355]
Se debe desarrollar los [mockups](https://drive.google.com/file/d/1RJULoXyjON2dtcBAOzQP_A53Mz_9RLkK/view?usp=sharing) diseñados por nuestra analista de requerimientos @mafeave para el modulo de actualización de datos, se debe desarrollar las vistas de menú (menú estudiante y menú oficina admisiones), Solicitud Estudiante ( Solicitud de Actualización de datos de identificación y Solicitud de Actualización de datos nombre y Solicitud de Inscripción), tener en cuenta los modales que se definen en cada mockup, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar el mockup  menú (menú estudiante y menú oficina admisiones)
![image](https://user-images.githubusercontent.com/43799065/103394904-577c2d00-4af9-11eb-8e99-83e7bdfa2a2b.png)

- [x] Desarrollar el mockup Solicitud Estudiante ( Solicitud de Actualización de datos de identificación, Solicitud de Actualización de datos nombre y Solicitud de Inscripción) 
![image](https://user-images.githubusercontent.com/43799065/103394920-72e73800-4af9-11eb-9d87-7ab2fa7ec244.png)
![image](https://user-images.githubusercontent.com/43799065/103394926-7a0e4600-4af9-11eb-96ab-ece7f6e1ffd2.png)
![image](https://user-images.githubusercontent.com/43799065/103394929-7ed2fa00-4af9-11eb-8aba-4ffaf330c7dd.png)

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
