### ISSUE TITLE
Ajustar la captura del error en el tag información personal en el proceso de preinscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#356]
Se debe ajustar el error que se genera cuando no existe información del usuario de wso2 en el api de terceros, en lugar de notificar un 404 data not found se debe generar un modal donde se informe al usuario que debe registrar la información del formulario para el registro en el api de tercero, la issue debe cumplir con los siguinete requerimientos:

- [x] Capturar el error de 404 de data not found y dar manejo para que no se muestre un error
- [x] Desarrollar el modal para informar al usuario que debe ingresar la información del formulario con la captura del error

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
