### ISSUE TITLE
Ajuste de funcionalidad de clonar en el modulo de calendario académico 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#359]
Se debe realizar el ajuste de la funcionalidad de clonar un calendario, puesto que al realizar las pruebas se encontraron algunos errores en la funcionalidad, realizar los ajustes necesarios para que esta funcionalidad quede funcionando bien, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la funcionalidad en el cliente y en el sga_mid para que quede funcionando bien
- [x] Realizar el ajuste de manejo de errores al realizar el clonaje del calendario cunado se pretende crear un calendario nuevo a partir de otro ya existente.

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Se realizan ajustes en 
sga_mid commit: https://github.com/udistrital/sga_mid/pull/209
sga_cliente: https://github.com/udistrital/sga_cliente/pull/365

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
