### ISSUE TITLE
Crear Mid para el registro calificado y de acreditación a un proyecto ya existente - 3 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#36]
Se debe desarrollar la funcionalidad para cambiar el estado de campo activo cuando se cree un registro nuevo a un proyecto académico existente, tambien se debe crear una funcionalidad que al momento de consultar la información del registro del proyecto debe traer el registro mas actual y activo para el tag de edición del cliente. La issue debe cumplir con los siguientes requerimientos:

- [x] Funcionalidad que al recibir un identificador del cliente desactive el registro anterior del registro y cree el nuevo registro al proyecto.
- [x] Funcionalidad de consulta que solo envie la información del registro mas actual de un proyecto académico existente.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo.

**Comment by fabianbarreto02** [comment]
Se realiza el primer check de la issue se puede observa en los [commits](https://github.com/udistrital/sga_mid/commit/7c69a9c713212119f07069598bd77758dc34d553) y [commit](https://github.com/udistrital/sga_mid/commit/0b20645c79cebb403567d4ba28219c4658f116ff)

**Comment by fabianbarreto02** [comment]
Se realiza el segundo check de la issue, se puede observar en el [commit](https://github.com/udistrital/sga_mid/commit/4915e2d5831ec49743764bd67c07e64e36c3b2da)

**Comment by fabianbarreto02** [comment]
Se da por terminada la tarea se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
- Tener en cuenta que si el proyecto no cuenta con registro de alta calidad, y se accede a la opción de agregar un registro de Alta calidad en el formulario de histórico de registros, se está presentando el siguiente error:
![image](https://user-images.githubusercontent.com/14035745/67159551-b0eca780-f30b-11e9-8b04-5e54c37b211a.png)

**Comment by fabianbarreto02** [comment]
Se corije observación de manejo de error cuando el proyecto no cuente con un registro calificado con antelación, se realiza en el [commit](https://github.com/udistrital/sga_mid/commit/b684dd877200b50c46097871d3ac4d4bd68b8b0b), rama Proyecto_academico, sga_mid, realizar pull para revisar la correción, se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica corrección de la observación dada. Se da por finalizada la tarea.
