### ISSUE TITLE
Desarrollar cliente para el registro calificado y de acreditación a un proyecto ya existente - 5 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#37]
Se debe desarrollar las funcionalidades a nivel cliente, para el registro de un registro calificado y alta calidad cuando el proyecto ya cuente con data anterior de un registro, esta tarea depende de #36, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear funcionalidad para la creación de un registro de acreditación a un proyecto existente. 
- [x] Crear funcionalidad para la creación de un registro de alta calidad a un proyecto existente. 

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se da por terminada la tarea, se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica opción para ver histórico de los registros calificado y de acreditación
![image](https://user-images.githubusercontent.com/14035745/67159426-2eafb380-f30a-11e9-9ae7-24149633b084.png)

Ajustar el campo date: Fecha de creación - Firefox (no carga): ajustarlo al componente usado en el formulario de registro de proyecto curricular.

Tener en cuenta que si el proyecto no cuenta con registro de alta calidad, y se accede a la opción de agregar un registro de Alta calidad en el formulario de histórico de registros, se está presentando el siguiente error:
![image](https://user-images.githubusercontent.com/14035745/67159551-b0eca780-f30b-11e9-8b04-5e54c37b211a.png)

Ajustar mensaje del botón:
![image](https://user-images.githubusercontent.com/14035745/67159445-6f0f3180-f30a-11e9-8d5b-bb1e1d10362f.png)

Espacio en tiempo de vigencia
![image](https://user-images.githubusercontent.com/14035745/67159464-a1209380-f30a-11e9-976a-9a683dd71969.png)

**Comment by DianaPatriciaRamirez** [comment]
@JuanPiedrahita va apoyar la actividad: Ajustar el campo date: Fecha de creación - Firefox (no carga): ajustarlo al componente usado en el formulario de registro de proyecto curricular.

Las 2 ultimas observaciones las ajusta el ingeniero @fabianbarreto02

**Comment by fabianbarreto02** [comment]
Se corrige observación del del espacio entre vigencia, se corrige a nivel de mid en el [commit](https://github.com/udistrital/sga_mid/commit/c9cf864b8cd07858b4667bb966f610bbd787106c) se debe realizar un pull a la rama del mid Proyecto_academico para observar la corrección, se espera  revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica ajuste del campo de Tiempo de vigencia y del mensaje del botón de registro calificado y acreditación. Se da por finalizada la tarea.
