### ISSUE TITLE
Ajustar bug de datepicker en el modulo de calendario en el cual se corre la fecha un dia de la que se selecciona 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#378]
Se debe correguir el bug de datepicker en el modulo de calendario en el cual se corre la fecha un dia de la que se selecciona, revisar y ajustar bug, se debe ajustar en todos los subcomponentes del modulo, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el bug por el cual se correr las fechas seleccionadas un día hacia atrás 
- [x] Ajustar en todos los componentes de edición de actividades y creación de actividades

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se da por finaliza la issue
