### ISSUE TITLE
Cargar el tipo de inscripción seleccionado para el tercero consultado en el modulo de preinscripción y el y los / proyectos temporalmente escogidos en el modulo de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#379]
Cargar el tipo de inscripción seleccionado para el tercero consultado en el modulo de preinscripción y el o los / proyectos temporalmente escogidos en el modulo de inscripción, esta consulta se debe hacer del api de inscripcion_crud previamente registrado, también se debe ajustar el flujo de pre inscripcion y el de inscripción teniendo en cuenta el [mockup ](https://docs.google.com/document/d/1HO-8t_EFPZNmWb7GJmp-BGDbSV5bDGvG02LM5sKaYb4/edit) ajustado por @mafeave, la tabla se debe realizar la consultar y llenar con la información del tercero, ajustar el botón de opción simulando con una variable cuando  el recibo este pendiente de pago o se encuentre en estado pago, ajustar el modulo de inscripción como esta en el mockup, cargar la información del periodo, el tipo de inscripción con información registrada y el nivel, finalmente se debe precargar el select con los varoles del proyecto dependiendo del nivel y que tenga la actividad de pago de inscripción habilitado en su proyecto, el select se cargara con un valor prefijo definido por el aspirante pero se podra cambiar el select, la issue debe cumplir con los siguientes requerimientos:

- [x]  Cargar el tipo de inscripción seleccionado para el tercero consultado en el modulo de preinscripción
- [x] Ajustar el flujo de pre inscripción y el de inscripción teniendo en cuenta el [mockup ](https://docs.google.com/document/d/1HO-8t_EFPZNmWb7GJmp-BGDbSV5bDGvG02LM5sKaYb4/edit)
- [x] La tabla se debe realizar la consultar y llenar con la información del tercero
- [x] Ajustar el botón de opción simulando con una variable cuando  el recibo este pendiente de pago o se encuentre en estado pago
- [x] Ajustar el modulo de inscripción como esta en el mockup, cargar la información del periodo, el tipo de inscripción con información registrada y el nivel
- [x] se debe precargar el select con los valores del proyecto dependiendo del nivel y que tenga la actividad de pago de inscripción habilitado en su proyecto, el select se cargara con un valor prefijo definido por el aspirante pero se podrá cambiar el select

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de la issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
