### ISSUE TITLE
Listado del histórico de registros de acreditación y alta calidad del proyecto - 8 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#38]
Se debe desarrollar un componente donde se pueda consultar el historico de registros de acreditación y alta calidad de un proyecto académico, el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en el mockup.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se da por finalizado la tarea, se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica funcionalidad para consultar el histórico de las acreditaciones y registro calificado de los proyectos académicos:
![image](https://user-images.githubusercontent.com/14035745/67167844-abbb4700-f363-11e9-8e87-704290e83644.png)
Se da por finalizada la tarea.
