### ISSUE TITLE
Revisión y ajuste del tag de inscripcion de posgrado producciones academicas  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#380]
Se debe realizar realizar el ajuste del tag de producciones academicas   en el modulo de inscripciones para posgrados, esto contempla  revisar el registro(post) de la producción académica pues se realiza el post pero no se notifica al usuario (modal), ajustar los placeholder del formulario de Producción académica de los distintitos Tipo de producción y sub tipos de producción, ajustar la carga de la lista de las producciones académicas registradas para el tercero seleccionado y ajustar función put para una producción ya creada con anterioridad, la issue debe cumplir con las siguientes requerimientos:

- [x]  Ajustar el registro(post) de la producción académica pues se realiza el post pero no se notifica al usuario (modal)
- [x] ajustar los placeholder del formulario de Producción académica de los distintitos Tipo de producción y sub tipos de producción
- [x] Ajustar la carga de la lista de las producciones académicas registradas para el tercero seleccionado
- [x] Ajustar función put para una producción ya creada con anterioridad

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
