### ISSUE TITLE
Realizar el ajuste a nivel crud y cliente para el tag de descuento en el proceso de inscripción de posgrado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#389]
Se debe realizar los ajustes a nivel de api [descuento_academico_crud](https://github.com/udistrital/descuento_academico_crud), se debe realizar el migrations para la tabla parametrica de tipo_descuento con el [documento ](https://docs.google.com/spreadsheets/d/1UOOf_X4_Df9UwaZKr69vZ8Ft4VCLQpZ9wurT5MeuGvc/edit#gid=1452795450) dado, de esta tabla se consulta en el cliente el select de descuento, tambien ajustar el nombre del campo persona_id de la tabla solicitud_descuento por tercero_id, realizar el migrations para ese ajuste, despues de realizar esos ajustes se debe realizar el proceso de registro y consulta de los descuentos, se debe registrar el proceso en la tablas solicitud_descuento, soporte_descuento, descuento_dependencia y tipo_descuento por ahora y posterior consulta de los registro por tercero, finalmente realizar la actualización de algún registro, la issue debe cumplir los siguientes requerimientos:

- [x] Realizar la migracion para el ajuste del campo especificado y los insert  de la tabla tipo_descuento con la información brindada, y documentar (imagen en el drive los cambios)
- [x] Realizar el proceso de consulta en el select con la información de la tabla tipo_descuento
- [x] Realizar el proceso de registro en las tablas solicitud_descuento, soporte_descuento y descuento_dependencia
- [x] Realizar el proceso de consulta de los registros de tercero en la tabla del tag
- [x] Realizar el proceso de actualización de un registro de un tercero

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Se realiza migration en descuento_academico_crud
commit: https://github.com/udistrital/descuento_academico_crud/pull/11

**Comment by fabianbarreto02** [comment]
se da por finaliza la isuue
