### ISSUE TITLE
Realizar ajuste nivel crud y cliente para el tag de documentos solicitados en el modulo de inscripción posgrado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#390]
Se debe realizar el ajuste en el api [inscripciones_crud ](https://github.com/udistrital/inscripcion_crud) a nivel de api y modelo de datos para incluir el manejo de los documentos de un aspirante, para esto se van a crear 3 tablas, la primera con nombre tipo_documento_programa de tipo paramétrica y realizar el insert por medio de migrations de informacion de pruebas (documento de identidad, foto, Tarjeta profesional, Carta de recomendación, Certificado de Eps), otra tabla llamada documento_programa que relaciona que documentos solicita cada programa, se debe realizar migracions de prueba con un proyecto que solicite todos los tipos de documentos para el desarrollo y finalmente una tabla con nombre soporte_documento_programa  que relaciona eel documento_id(archivo),el tipo de documento por medio de la tabla documento_programa y la inscripción con la cual se esta realizando (mirar la imagen de guía)  

![image](https://user-images.githubusercontent.com/43799065/103969469-f75a3c00-5133-11eb-9097-db7dd14cbcdb.png)

También se debe realizar el registro del documento y la consulta de algún documento registrado con anterioridad, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el ajuste a nivel api, junto al modelo de datos, se debe documentar (imagen y sql) en drive para trasabilidad
- [x] Realizar los migrations para ajustar el modelo de datos en ambiente de test con los insert  antes mencionados 
- [x] Realizar el proceso de registro de un documento en el api de inscripcion_crud
- [x] Realizar el proceso de consulta de los documentos previamente seleccionados  
- [x] Realizar el proceso de modificación de los documentos existentes

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se realiza modelo de datos con los ajustes requeridos, ubicado en: https://drive.google.com/drive/u/0/folders/1BwwFw_iKFeJEtod24O9wIJVo0pnb1ZMx
![inscripcion_V_15](https://user-images.githubusercontent.com/11802554/104645148-af2fa200-567c-11eb-8ac0-90c826c7ac3e.png)

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
