### ISSUE TITLE
Ajustes en el desarrollo de oferta académica y habilitar periodo por cambio de la versión de angular de 6 a 7

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#4]
Se debe integrar los componentes de habiliatar perido y consulta oferta academica al cliente desarrollado para el sistema de gestión academica, el  cliente debe cumplir con los siguientes requerimientos:

- [x] Los componentes deben ajustarce correctamente al cliente ya desarrollado.
- [x] Se debe cumplir con el linting satisfactoriamente.

Lider técnica : @mafeave

**Comment by fabianbarreto02** [comment]
Se realiza la integración de los componentes, tipo periodo, habilitar periodo y oferta academica, en el repositorio sga_cliente en la rama [Habilitar periodo oferta academica](https://github.com/udistrital/sga_cliente/tree/hablitar_perido_oferta_academica), se espera revisión por parte de la lider técnica: @mafeave

**Comment by mafeave** [comment]
Se verifica la funcionalidad migrada a Angular 7. Se da por finalizada la tarea.
