### ISSUE TITLE
Verificar compatibilidad del navegador del picker time, evaluar mejor alternativa de solución; en caso de ser necesario, ajustar el código

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#40]
Verificar compatibilidad del componente date-time-picker para el navegador Firefox y de ser necesario cambiar el componente para usar el nuevo.
- [x] El componente datetime picker tiene compatibildad en chrome
- [x] El componente datetime picker tiene compatibildad en firefox

**Comment by JuanPiedrahita** [comment]
Se verifica que el componente no funciona en el navegador Firefox, se empieza a buscar un nuevo componente que tenga compatibilidad con más navegadores.

**Comment by JuanPiedrahita** [comment]
Se validaron diferentes alternativas para poder solucionar el problema, a contnuación se listan algunas: 
- [angular-bootstrap-datetimepicker](https://www.npmjs.com/package/angular-bootstrap-datetimepicker)
- [ng-pick-datetime](https://www.npmjs.com/package/ng-pick-datetime)
- [angular-datetime-picker](https://www.syncfusion.com/angular-ui-components/angular-datetime-picker)

Al final de todo se escogio esta alternativa: [angular-datepicker](https://www.npmjs.com/package/angular-datepicker)

Se listan url utiles: 
- [Demo](https://vlio20.github.io/angular-datepicker/#)
- [Proyecto de github](https://github.com/vlio20/angular-datepicker)

El componente tiene la siguiente visualizacion: 
- Firefox
![imagen](https://user-images.githubusercontent.com/25555966/66592148-1d241a00-eb5a-11e9-99e3-8b7e980df785.png)
- Chrome
![imagen](https://user-images.githubusercontent.com/25555966/66592195-2e6d2680-eb5a-11e9-96ad-e05521bb90f5.png)


La definición del componente es la siguiente:
```html
<dp-date-picker id="daytimePicker"
                        name="daytimePicker"
                        #dateComponent
                        #daytimePicker="ngModel"
                        [(ngModel)]="date"
                        (onChange)="log($event)"
                        [mode]="'daytime'"
                        [displayDate]="displayDate"
                        (open)="opened()"
                        (close)="closed()"
                        (onLeftNav)="onLeftNav($event)"
                        (onRightNav)="onRightNav($event)"
                        (onSelect)="onSelect($event)"
                        [disabled]="disabled"
                        [minDate]="validationMinDate"
                        [maxDate]="validationMaxDate"
                        [required]="required"
                        [placeholder]="placeholder"
                        [config]="config"
                        theme="dp-material">
</dp-date-picker>
```

**Comment by JuanPiedrahita** [comment]
SE da por terminada la tarea, queda pendiente unicamente actualizar las fechas que se esten utilizando para la creación u edición de los registros calificados.

**Comment by mafeave** [comment]
Se verifica carga de Date time picker tanto en chrome como en el formulario de registro de proyecto académico: 
![image](https://user-images.githubusercontent.com/14035745/67167942-85e27200-f364-11e9-9a5c-6ae0ba1780c4.png)
