### ISSUE TITLE
Ajustar y revisar los tag de propuesta de trabajo de grado con los nuevos servicios del cidc y ajustar el resumen del perfil

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#404]
Se debe ajustar y revisar el tag de propuesta de grado post, consulta y editar con el nuevo [servicio ](https://autenticacion.portaloas.udistrital.edu.co/apioas/siciud_crud/v1/research_group) para cargar el grupo de investigación, por ahora el select de liena de investigación quemado mientras nos define el servicio del cidc, también se debe ajustar el tag de perfil con el resumen de la inscripción, finalmente se debe verificar que al llenar toda la información de la hoja de vida  se pueda realizar la inscripción del aspirante y realizar el put actualizando el estado del aspirante y verificar el proyecto al cual se esta inscribiendo, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el tag de propuesta de grado con post y el get de consulta y put de editar 
- [x] Ajustar el servicio de consulta del grupo de investigación con el servicio nuevo, ya que el servicio se demora en consultar agregar un spiner para informar al usuario que se esta cargando los datos
- [x] Ajustar el tag de perfil para mostrar el resumen de la hoja de vida del aspirante 
- [x] Se debe verificar que cuando todo este lleno todos los porcentaje se encuentren en 100 % y que el aspirante pueda inscribirse 
- [x] Finalmente se debe cambiar el estado del aspirante a inscrito con un put en la tabla de inscripcion y actualizar el proyecto si se cambio de proyecto

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
servicio lineas de investiacion
https://autenticacion.portaloas.udistrital.edu.co/apioas/siciud_crud/v1/research_focus
no esta funcionando 
{
    "fault": {
        "code": 404,
        "type": "Status report",
        "message": "Runtime Error",
        "description": "No matching resource found for given API Request"
    }
}
servicio grupo de investigacion
https://autenticacion.portaloas.udistrital.edu.co/apioas/siciud_crud/v1/research_group (OK)
servicio tipo proyecto
https://autenticacion.portaloas.udistrital.edu.co/apioas/inscripcion_crud/v2/tipo_proyecto?query=Activo:true&limit=0 (no trae info)

**Comment by ricardoavendano** [comment]
Insert en tabla tipo_proyecto en inscripcion_crud
https://github.com/udistrital/inscripcion_crud/pull/61

**Comment by ricardoavendano** [comment]
Ajuste formato fecha para put de propuesta en inscripcion_crud
commit: https://github.com/udistrital/inscripcion_crud/pull/63

**Comment by ricardoavendano** [comment]
Ajuste modulo propuesta grado, creacion post y put
commit: https://github.com/udistrital/sga_cliente/pull/425

**Comment by ricardoavendano** [comment]
Ajuste en sga_cliente para mostrar el modulo de perfil y actualizacion en tabla inscripcion de inscripcion_crud
commit: https://github.com/udistrital/sga_cliente/pull/432

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
