### ISSUE TITLE
Desarrollar componente para Administración de criterios y subcriterios reutilizando el componente de calendario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#405]
Se debe desarrollar el componente de Administración de criterios y subcriterios segun el [mockup](https://docs.google.com/document/d/1h0izTrH7J_BpBlaVXczTzhIuaMgdq8z7XiCQ2DTOEbc/edit) diseñado por @mafeave, tener en cuenta que se puede reutilizar el componte de calendario ya que maneja el mismo flujo (criterios --> procesos), (subcriterios --> Actividades), se debe desarrolar la funcionalidad para realizar el post en el api de   [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud/tree/develop), [modelo](https://drive.google.com/drive/u/0/folders/13vYsTRMkAX5iM1OX2lo3CrxQBwMqDOmF) actual, se debe realizar un ajuste del modelo actual teniendo en cuenta el mockup de la base de datos:

![image](https://user-images.githubusercontent.com/43799065/104784391-2be27f00-5756-11eb-8a5d-3bfb620d6a84.png)

Se debe ajustar por medio de migracion y documentar los cambios del modelo, finalmente se debe realizar las funciones post, get y put para los criterios y los subcriterios, la issue debe cumplir los siguientes requerimientos:

- [x] Realizar el ajuste del modelo de datos con su migracion y documentacion
- [x] Realizar el componente teniendo en cuenta los mockups datos
- [x] Ajustar funcionalidad para post, get y put para los criterios y subcriterios

**Comment by jupmorenor** [comment]
Se realiza ajuste al modelo de datos, adjunto link e imagen:
https://drive.google.com/drive/u/0/folders/1KfN14GuqyuYLnE58suckgTzoGEM_F7zY
![evaluacion_inscripcion_V4](https://user-images.githubusercontent.com/11802554/104960404-25484780-59a2-11eb-9e29-b90aeea101da.png)

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
se valida la issue
