### ISSUE TITLE
Revisar filtro en listado de proyectos académicos

### ISSUE THREAD

**Issue by mafeave** [udistrital/sga_cliente#41]
Revisar error que se está presentando con el filtro utilizado en en la tabla que lista los proyectos académicos:
![image](https://user-images.githubusercontent.com/14035745/66516793-7c752200-eaa7-11e9-86a6-dc6143b9f619.png)

**Comment by JuanPiedrahita** [comment]
SE corrige el filtro por nombre, se adjunta evidencai del funcionamiento del filtro 
![imagen](https://user-images.githubusercontent.com/25555966/66710776-8c5d6200-ed44-11e9-9902-ec042f0d08e8.png)

**Comment by mafeave** [comment]
Se verifica ajuste del error que se estaba presentando con el filtro de la tabla de listado de proyectos, se da por finalizada la tarea.
