### ISSUE TITLE
Realizar la funcionalidad de visualización de los recibos de inscripción con el botón de la tabla de consulta 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#417]
Se debe desarrollar la función para poder visualizar el recibo para descargar o visualizar los recibos que tiene el aspirante relacionado en la tabla 

![image](https://user-images.githubusercontent.com/43799065/105427226-a6117880-5c1a-11eb-94cf-606c563d74f3.png)

Se debe consumir el servicio desarrollado en el api mid el cual genera el binario con la información necesaria, la visualización debe ser dinamica dependiendo del recibo seleccionado, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la funcionalidad para la visualización del recibo seleccionado en la tabla
- [x] Utilizar el servicio desarrollado en el mid

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se valida la issue
