### ISSUE TITLE
Generación del comprobante de inscripción al momento de inscribirse un aspirante 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#418]
Se debe generar un comprobante de inscripción cuando el aspirante aspirante termine de realizar la inscripción a un proyecto, se debe tener en cuenta el componente de perfil y utilizar esa información para generar el pdf teniendo en cuenta el [mockup](https://app.diagrams.net/#G1iZf51Xc_skbJtqatkDbJBapT1_KUqZNp) desarrollado por @mafeave, este comprobante se genera por cada inscripción, la issue debe cumplir con los siguientes requerimientos:

- [x] Utilizar la información del componte perfil para consultar la información 
- [x] Generar un pdf con la información requerida para el comprobante de inscripción 
- [x] El comprobante debe generarse por cada inscripción que tenga el aspirante

**Comment by fabianbarreto02** [comment]
https://github.com/udistrital/produccion_academica_cliente/issues/62

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
