### ISSUE TITLE
Ajustar el componente de registro de criterios con el campo de "Requiere asistencia"

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#419]
Se debe ajustar el componente de registro de un criterio y la consulta del criterio (tabla) se debe incluir un check box para saber si el criterio requiere asistencia, se debe ajustar a nivel de api y base de datos con su respectivo migrations, ajustar el post del criterio y el get con su tabla del criterio, la issue debe cumplir con la siguientes requerimientos:

- [x] Ajustar el modelo de datos y el api con su respectivo migracions campo asistencia de tipo boolean en la tabla requisito 
- [x] Ajustar el componente de registro y consulta con el nuevo campo 
- [x] ajustar el post, put y get del criterio

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se ajusta el modelo de datos agregando la columna "asistencia" a la tabla Registro:
![evaluacion_inscripcion_V5](https://user-images.githubusercontent.com/11802554/106076287-4e24b700-60dd-11eb-8400-2c2c41d6ba25.png)

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea.

**Comment by fabianbarreto02** [comment]
Se valida la issue
