### ISSUE TITLE
Función para mostrar la información del coordinador asignado si ya el proyecto cuenta con uno (issue extra) 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#42]
Se debe realizar una función (mid y Cliente) que muestre la información de un coordinador asignado a un proyecto existente, esta issue sale de una necesidad encontrada al momento de desarrollo.

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se  inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza la función para mostrar información de un coordinador asignado a un proyecto existente, se espera revisión por parte de @mafeave

**Comment by fabianbarreto02** [comment]
Durante el desarrollo de la issue, se observa la necesidad de crear una funcionalidad que al momento de asignar un coordinador nuevo y ya exista uno asignado al proyecto académico, desactive el registro anterior y asigne al nuevo coordinador.

**Comment by mafeave** [comment]
Se verifica carga de información del coordinador cuando el proyecto académico tiene uno asignado. La observación dada por @fabianbarreto02 se realiza mediante el issue https://github.com/udistrital/sga_mid/issues/16
