### ISSUE TITLE
Realizar el componente y la funcionalidad de Asignar criterios de evaluación a los programas académicos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#420]
Se debe desarrollar los mockups para  Asignar criterios de evaluación a los programas académicos ajustando y desarrollando los [mockups ](https://docs.google.com/document/d/1h0izTrH7J_BpBlaVXczTzhIuaMgdq8z7XiCQ2DTOEbc/edit)desarrollado por @mafeave, se debe desarrollar la parte de asignación de los porcentajes para los criterios y los subcriterios, realizar la funcionalidad para el post, put y el get de los criterios y los sub criterios, en el api de evaluacion_inscripcion_crud, tener en cuenta las notas del modelo, el registro se debe realizar en la tabla requisito_programa_academico 
![image](https://user-images.githubusercontent.com/43799065/105430449-892c7380-5c21-11eb-8fbb-65b4f99ab94d.png)

La issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar y desarrollar los componentes para la asignación de criterios de evaluación segun el mockup
- [x] Realizar la funcionalidad para los criterios y los sub criterios de post, put y el get

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Se realiza ajuste en cliente usando crud de evaluación
commit: https://github.com/udistrital/sga_cliente/pull/453

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
