### ISSUE TITLE
Desarrollar el mockups para la EVALUACIÓN DE CRITERIOS DE ADMISIÓN

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#421]
Se debe desarrollar los [mockups](https://docs.google.com/document/d/1dlHqDRghT0oBxKRIUfIvhK0ubn6ZZODoqBMxQDk6xFk/edit) desarrollado por @mafeave para Evaluación de criterio sin subcriterios con o sin asistencia y Evaluación de criterios con subcriterios con y sin asistencia, se debe desarrollar el componente de forma dinámica para que la columna de asistencia se muestre o no depende de la carga del criterio, solo de debe desarrollar los componente y se se alcanza realizar la función de post en e api de evaluacion_inscripcion en la tabla detalle_evaluacion, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar los mockups para los criterios y subcriterios 
- [x] Desarrollar que los componentes sean dinámico 
- [ ] Si se alcanza realizar la función de post en e api de evaluacion_inscripcion en la tabla detalle_evaluacion

**Comment by gabrielablanco** [comment]
Se da inicio con la solucion de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se  valida la issue el ultimo item se desarrolla en otra issue
