### ISSUE TITLE
Función para mostrar la información de un registro de alta calidad a un proyecto si cuenta con uno (issue extra) 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#43]
Se debe realizar una función (mid y Cliente) que muestre la información de un registro de alta calidad de un proyecto existente si ya cuenta con uno, esta issue sale de una necesidad encontrada al momento de desarrollo.

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se desarrolla la funcionalidad a nivel de mid para traer la información  de un registro de alta calidad si el proyecto cuenta con uno, esto se realizo en la [issue](https://github.com/udistrital/sga_mid/commit/97ae51da7f601362680f8f4f2b2ce00ded25ac78)

**Comment by fabianbarreto02** [comment]
Se realiza la funcionalidad para mostrar la información de un registro de alta calidad de un proyecto académico, si este cuenta con uno, se finaliza la issue.

Se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica la carga de la información correspondiente al registro de alta calidad de un proyecto académico:
![image](https://user-images.githubusercontent.com/14035745/67168771-01482180-f36d-11e9-85aa-f8b912199c32.png)
