### ISSUE TITLE
Ajustar la sincronización de  todo el proceso de inscripción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#434]
Se debe realizar el ajuste de sincronización de todos los componentes en el proceso de inscripción de posgrado para que el componente no se muestre si no ha llegado la información de consulta, se debe realizar esa sincronización para todos los tag de inscripción y agregar un sppiner  cuando se esta esperando la consulta de los datos, también ajustar el color verde de los tag de inscripción por los colores del sistema, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la sincronización de todo el proceso de inscripción  para que no se muestre el componente si espera información 
- [x] Ajsutar el color de los tag de verde al color del sistema

**Comment by ricardoavendano** [comment]
se realiza ajuste de spinner en modulo insccripcion
commit: https://github.com/udistrital/sga_cliente/pull/463

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
