### ISSUE TITLE
Realizar la funcionalidad para el registro y la consulta del modulo de evaluación de criterios

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#436]
Se debe desarrollar la funcionalidad para consultar los inscritos en el programa seleccionado y el periodo los terceros que esten en estado de inscripción "inscrito) para llenar las tabla de cada uno de los criterios y subcriterios definidos por el programa, ajustar una función a nivel de mid que consulte los inscritos por programa, periodo y estado  y devuelva los nombres de los terceros, después se debe realizar la funcionalidad para  realizar el registro de los valores de cada uno de los inscritos en la tabla de detalle_evaluación, donde se debe registrar en el campo de nota_requisito la nota computada de los subcriterios de acuerdo al procentaje general del criterio y en el campo detalle_calificacion, un json con el detalle de la evaluación de los subcriterios si requiere, realizar una función que realice el registro de varios inscritos de forma automatica, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la función de consulta de los inscritos al programa y al periodo seleccionado con nombres de los terceros
- [x] Realizar    la funcionalidad par registrar varios detalles evaluación  para los terceros inscritos con el computo de la nota del requisito 
- [x] Realizar la consulta y mostrar en el componente la información registrada

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada esta tarea
