### ISSUE TITLE
Ajustar el orden de la consulta de los recibos para el aspirante por fecha del mas viejo al mas actual, ajustar funcionalidad de botón de pago en pruebas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#437]
Se debe ajustar la consulta de los recibos para que se organicen de forma descendientes del mas viejo al mas actual en la tabla de consulta y se debe incluir la funcionalidad del boton pagar siguiendo la siguiente estructura:

REFERENCIA:Numero de recibo 
NUM_DOC_IDEN: # del aspirante
TIPO_DOC_IDEN: Tipo documento
NOMBRE: Nombre aspirante
VALOR_RECIBO: valor de pago
CONCEPTO: inscripción virtual 
VALOR_IVA= valor iva

Ejemplo:

https://pruebasfuncionarios.portaloas.udistrital.edu.co/botonPago/index.php?recibo=&REFERENCIA=8826&NUM_DOC_IDEN=24682&TIPO_DOC_IDEN=CC&NOMBRE=prueba%20nombre%20apellido&VALOR_RECIBO=1000&CONCEPTO=Inscripcion%20Virtual&VALOR_IVA=0 

La issue debe cumplir con la siguientes requerimientos:

- [x] Ajustar el orden de los recibos como esta definido 
- [x] Ajustar funcionalidade de boton de pago con la información por cada recibo

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada esta tarea
