### ISSUE TITLE
Ajustar el control de maximo de recibos con el estado pendiente de pago

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#438]
Se debe tener un control de un máximo de tres recibos de pago con estado pendiente de pago, actualmente se controla con el numero de recibos de todos los estado, el aspirante puede tener n recibos de pago pero solo general en estado pendiente de pago máximo 3, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el control de la generación de los recibos con los estado del recibo pendiente de pago

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada esta tarea
