### ISSUE TITLE
Ajustar los modelos de datos de evaluación_inscripcion y inscripcion_crud

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#439]
Se debe realizar los ajustes de los modelos de datos de evaluación_inscripcion_crud y inscripción_crud para el registro de la evaluación de los diferentes aspirantes a un proyecto particular y periodo, se debe eliminar la tabla evaluacion_inscripcion en el api de  evaluación_inscripcion_crud  y cambia el campo en la tabla de detalla_evaluacion de evaluacion_inscripcion_id por inscripcion_id  , en el api inscripción_crud  en la tabla inscripción incluir el campo de nota_final como tipo numérico y puede ser nulo, tener en cuenta los borradores de los ajustes 

![image](https://user-images.githubusercontent.com/43799065/106336232-7686ef80-625c-11eb-8d51-3ca723b28383.png)

![image](https://user-images.githubusercontent.com/43799065/106336252-843c7500-625c-11eb-8e59-86cbfb079002.png)

La issue debe cumplir con los siguiente requerimientos:

- [x] Realizar el ajuste del modelo por medio de migraciones 
- [x] Documentar los ajustes 
- [x] Actualizar las apis con los ajustes del modelo

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Nueva versión del modelo de Inscripción:
https://drive.google.com/drive/u/0/folders/13_3KjP_-NtIrSmUJ08AleIjIzKhRcsFU
![inscripcion_V_16](https://user-images.githubusercontent.com/11802554/106511241-f8199000-649d-11eb-9644-cb62bafd8854.png)

**Comment by jupmorenor** [comment]
Nueva versión del modelo de Evaluacion-Inscripción:
https://drive.google.com/drive/u/0/folders/1RbRxlRRNWrrsbhq0AyJt-2P0TrCVn0Ng
![evaluacion_inscripcion_V6](https://user-images.githubusercontent.com/11802554/106512368-7e82a180-649f-11eb-960a-824b3fd6fcf0.png)

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea.

**Comment by fabianbarreto02** [comment]
se valida la issue
