### ISSUE TITLE
Realizar la funcionalidad para verificar que todos los criterios para cada aspirante del programa, agregar el boton para calcular la nota final de cada aspirante 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#444]
Se debe realizar realizar la funcionalidad para controlar que se halla hecho el registro de las notas a todos los aspirantes por cada criterio, esto se valida con el botón nuevo de "Asignar nota final ", al oprimir ese botón se debe realizar una función a nivel de mid para que calcule la nota final a cada aspirante y realice el registro en el api de inscripciones, la issue debe cumplir con los siguientes requerimientos:

- [x] Controlar que todos los aspirantes tengan asignados notas en cada criterio
- [x] Realizar la función a nivel de mid para calcular la nota final de cada aspirante con los porcentajes defindos 
- [x] Realizar el registro de las notas finales de cada aspirante en el api de inscripciones

**Comment by fabianbarreto02** [comment]
https://docs.google.com/document/d/1dlHqDRghT0oBxKRIUfIvhK0ubn6ZZODoqBMxQDk6xFk/edit

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
