### ISSUE TITLE
Cambiar flujo de asignación de cupos, realizar el registro de cupos para pregrado y posgrados, generar la selección de admitidos con los cupos y generar la tabla de admitidos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#445]
Se debe cambiar el flujo de asignación de cupos,  se debe pasar la funcionalidad de asignación de cupos al menú de actualizar estado aspirantes, solo para el nivel de pregrado, crear nuevo componente de asignación de cupos para posgrados, se debe revisar y ajustar la funcionalidad de selección de admitidos teniendo en cuenta los cupos y el orden de puntación total de mayor a menor, cambiar el estado del aspirante de admitido y no admitido y agregar botón para mostrar la lista con los resultados con la funcionalidad de listar aspirantes, la issue debe cumplir con los siguiente requerimientos:

- [x]  Pasar la funcionalidad de asignación de cupos al menú de actualizar estado aspirantes, solo para el nivel de pregrado, crear nuevo componente de asignación de cupos para posgrados
- [x] Revisar y ajustar la funcionalidad de selección de admitidos teniendo en cuenta los cupos y el orden de puntación total de mayor a menor
- [x]  Cambiar el estado del aspirante de admitido y no admitido según el calculo 
- [x] Agregar botón para mostrar la lista con los resultados con la funcionalidad de listar aspirantes,

**Comment by fabianbarreto02** [comment]
https://docs.google.com/document/d/15x4gwBZyyaKqVvkTB3FY3-OWOStcoiCntlPoTkBr-MM/edit

**Comment by ricardoavendano** [comment]
inicio tarea

**Comment by ricardoavendano** [comment]
Se realiza integracion de actualizacion estado aspitante 
commit: https://github.com/udistrital/sga_cliente/pull/471

**Comment by fabianbarreto02** [comment]
No veo los ajustes realizados

**Comment by jupmorenor** [comment]
Los ajustes se encuentran relacionados en el merge #471 
Esta issue fué finalizada satisfactoriamente.
