### ISSUE TITLE
Realizar ajustes de seguridad encontrados en el informe de seguridad del modulo de derechos pecuniarios y calendario académico 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#449]
Realizar ajustes de seguridad encontrados en el informe de seguridad del modulo de derechos pecuniarios y calendario académico,  tener en cuentas las observaciones del ing jose y el documento relacionado:

 

- Calendario académico : https://docs.google.com/document/d/15t4vuFQvy_uYyw0dhNXzjoJw0r6EDfwMJO3W8TRMdzo/edit
- Derechos pecuniarios: https://drive.google.com/drive/folders/1a3vKHz5vJWAshTk-Zo3m_WzKipRE5-gr

Tener precaución con la actualización de las dependencias, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el modulo de  Calendario académico
- [x] Ajustar el modulo de Derechos pecuniarios:

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se realiza actualización de dependencias teniendo en cuenta que no rompan el funcionamiento de las aplicación y que se corrijan la mayor cantidad de vulnerabilidades posibles.
El estado inicial era este:
![image](https://user-images.githubusercontent.com/11802554/107387802-2d883400-6ac3-11eb-93ce-059536cbad56.png)
Y el estado final es el siguiente:
![image](https://user-images.githubusercontent.com/11802554/107387849-37aa3280-6ac3-11eb-8d3a-36dde29eda4b.png)
Estas vulnerabilidades restantes corresponden al paquete protractor, en su [repositorio](https://github.com/angular/protractor/pulls) se puede ver que no han aceptado las correcciones que requiere.

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea.

**Comment by fabianbarreto02** [comment]
Se da por finalizada esta tarea.
