### ISSUE TITLE
Ajustar la consulta de todos los módulos que tienen los niveles quemados y ajustar la consulta 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#455]
Se debe realizar el ajuste de todos los módulos que tiene un select de nivel (pregrado y posgrado) que cuenten con la información quemada en el cliente, se debe consultar el servicio de api de proyecto_academico_crud, y ajustar la consulta de los proyectos que cuenta con ese nivel, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la carga de los select con el nivel correspondiente en los modulos necesarios 
- [x] Ajustar la consulta  de los proyectos académicos con su respectivo nivel

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
