### ISSUE TITLE
Diseñar y plantear un modelo de datos para el manejo de información de un estudiante 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#457]
Se debe diseñar y plantear un modelo de datos  para el manejo de información de un estudiante  que pueda manejar las siguiente información:

- Tercero
- código
- proyecto académico (solo un proyecto)
- Estado estudiante (activo, vacaciones, prueba académica) posible paramétrica   
- numero de renovaciones de matriculaciones 
-  normativa, acuerdos (paramétrica) 
- modalidad (hora, créditos ) posible tabla en otro esquema 
- plan de estudios (tabla semi paramétrica) posible tabla en otro esquema

Se debe realizar el diseño y presentar a @fabianbarreto02  y @mafeave, si es posible realizar la presentación con dbas y arquitectos, si se aprueba el modelo realizar el api  del modelo, la issue debe cumplir con los siguientes requerimientos:

- [x] Diseñar el modelo de datos con la información presentada
- [x] Explicar el modelo a líder técnico y analista de requerimientos
- [x] Si se aprueba, realizar Reunión con dbas y arquitecto 
- [ ] si se aprueba, realizar el api para  para el modelo de datos aprobado

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Versión preliminar del modelo de datos
![estudiantes_v1](https://user-images.githubusercontent.com/11802554/108202828-b28cd200-70ef-11eb-87a0-c414c2dcd138.png)

**Comment by jupmorenor** [comment]
### Registro de estudiantes admitidos

El día 17 de febrero se realiza reunión con arquitectos, DBAs y encargados del sistema Cóndor para socializar el modelo de datos propuesto para el registro y control de estudiantes.

Como conclusión se nos propone que en lugar de crear un esquema de datos y una API nuevos se almacene la información en los esquemas de datos ya existentes, los datos relacionados al estudiante en el esquema Terceros utilizando los grupos de información complementaria y la nueva tabla de vinculación, los diferentes estados que puede tener el estudiante y las diferentes normatividades académicas que lo rigen se pueden almacenar en el esquema Parámetros.

A partir de estas observaciones se hace la distribución de los datos originalmente requeridos en el modelo propuesto a los esquemas sugeridos así:

1. Vinculación del tercero como ESTUDIANTE de la UNIVERSIDAD DISTRITAL: en la tabla terceros.vinculacion se relaciona el tercero con la UD y se relaciona en el campo tipo_vinculacion_id un registro en parametros.parametro agrupado dentro del tipo_parametro.id=14.
- Esta vinculación tendría efecto una vez se ha formalizado (pagado) la matricula, para esto se usa el campo fecha_inicio_vinculacion.
- El registro del tipo de vinculación ESTUDIANTE en la tabla parametro no existe y hay que agregarlo.
- El campo dependencia_id se usará para indicar el proyecto curricular al cual se ha adscrito el estudiante. (oikos o programa)
- El campo periodo_id relaciona el periodo académico en que inicia la vinculación, es decir, la cohorte.
- Si el estudiante llega a tener mas de una vinculación con la universidad (contratista o docente) simultáneamente, esto se puede registrar sin inconvenientes.

2. Estados del ESTUDIANTE durante su vinculación con la universidad: Se debe agregar al esquema de parámetros un nuevo tipo de parámetro (tipo_parametro) que agrupe todos los estados (parametro) que un estudiante puede tener durante su vinculación con al universidad, estos datos deberían agregarse a la base de datos a traves de migraciones. Se requiere consultar cuales son los estados disponibles en Condor.

Ejemplo:
```
grupo_info_complementaria: Información histórica de estudiantes
	info_complementaria: Estado académico
		info_complementaria_tercero: dato: { CodigoEstudiante: 20111020059, PlandeEstudios: <id_plan> } //registro padre
		info_complementaria_tercero: dato: { Estado: <id_estado>, renovaciones: 1}, info_complementaria_padre ^
		info_complementaria_tercero: dato: { Estado: <id_estado>, renovaciones: 2}, info_complementaria_padre ^
```

3. Normatividad que rige al estudiante: Para este caso también se debe registrar en el esquema parámetros dentro de un mismo tipo de parámetro los diferentes acuerdos que reglamentan la situación académica de los estudiantes en la universidad, estos se relacionan por medio de los grupos de información complementaria así:

Ejemplo: 
```
grupo_info_complementaria: Información histórica de estudiantes
	info_complementaria: Normatividad
		info_complementaria_tercero: dato: { NormativaId: 20, MaxRenovaciones: 15 }
```
- normativa_id es el id del parámetro en parámetros.
- max_renovaciones es el numero máximo de renovaciones de matricula que ese reglamento estipula para ese estudiante, teniendo en cuenta el nivel de formación que está cursando. (este campo podría moverse a parámetros)

**Comment by jupmorenor** [comment]
Se da por finalizada la solución de esta tarea.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
