### ISSUE TITLE
Generar el reporte de spagobi para el listado de admitidos, opcionado  y no admitidos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#458]
Se debe generar el reporte con spagobi donde se pueda observar el listado de los admitidos, opcionado  y no admitidos por proyecto y periodo, para poder realizar esta issue se debe tener en cuenta la siguiente documentación:

- https://github.com/udistrital/sga_mid/issues/148
- http://www.aiknow.info/2018/03/07/knowage-create-data-reports-with-birt/
- https://github.com/udistrital/inscripcion_crud/issues/16
- https://github.com/udistrital/sga_cliente/issues/13
- https://drive.google.com/drive/folders/1co2UPrqEBHJHn65hpTq5qEbrFqg-CPBw
- https://github.com/udistrital/sga_cliente/issues/57
- https://github.com/udistrital/sga_cliente/issues/58  
- https://github.com/udistrital/sga_cliente/issues/66 
- https://github.com/udistrital/sga_cliente/issues/67   
- https://github.com/udistrital/sga_cliente/issues/76
- https://github.com/udistrital/sga_cliente/issues/142   

La issue debe cumplir con los siguientes requerimientos:

- [x] Revisar la documentación y entender como funciona el sistema spagobi para la generación de reportes
- [x] Revisar lo implementado en el desarrollo con respecto a la creación de entrada y la generación del reporte 
- [x] Generar el reporte con la infomación requerida ( tipo documento, docuemento, nombre y estado)

**Comment by ricardoavendano** [comment]
Se realiza nuevo modulo en reportes para admitidos, opcionado y no admitidos
commit: https://github.com/udistrital/sga_cliente/pull/497/commits/d7202a0fe08eee492e002121c467f94e7ab5fe71

**Comment by ricardoavendano** [comment]
reporte:
[admitidos_proyecto.rptdesign.txt](https://github.com/udistrital/sga_cliente/files/6128068/admitidos_proyecto.rptdesign.txt)

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
