### ISSUE TITLE
Desarrollar la funcionalidad para el registro de la solicitud de actualización de identificación y de nombres en el modulo de datos básicos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#459]
Se debe desarrollar la funcionalidad para el registro de una solicitud de   actualización de identificación y de nombres en el modulo de datos básicos, primero se debe crear un menu padre dentro del menu datos basicos con el nombre de actualización de datos que contenga los menos de solicitud de actualización de identificación y solicitud de actualización de nombres, luego se debe cargar en los siguientes campos la informacion existente:

identificación 

![image](https://user-images.githubusercontent.com/43799065/107815152-f8891500-6d40-11eb-93c9-59e997f8c03c.png)

Nombres

![image](https://user-images.githubusercontent.com/43799065/107815213-0e96d580-6d41-11eb-9826-aad586f35459.png)

Después de cargar esa información se debe consumir el servicio de [solicitudes_crud ](http://pruebasapi2.intranetoas.udistrital.edu.co:8117/v1/solicitud)con el siguiente modelo de datos:

![image](https://user-images.githubusercontent.com/43799065/107815483-6a615e80-6d41-11eb-8c40-d74483dc360b.png)

Se debe tener en cuenta realizar una funcion a nivel de mid para registrar los siguientes datos:

Tabla solicitante:

- tercero_id
- solicitud_id
- activo 

Tabla solicitud:

- referencia: json con ={datos anteriores, datos nuevos )
- fecha_radicacion: fecha de solicitud
- activo= true
- estado_tipo_solicitud_id = id referencia a la tabla con el estado definido 

Tabla estado_tipo_solicitud

- tipo_solicitud: crear dos registros paramétricos con migracion en la api de solicitud para actualización de identificación y actualización de nombres 
- estado_id: buscar id del estado radicado en la tabla parametrica 
- dependecia_id: buscar en el api de oikos buscar id de oficina de admisiones
- numero_dias=0
- activo=true 

La issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el menu como se menciono 
- [x] Consulta la información necesaria en oikos
- [x] Realizar la migracion en el api de solicitudes_crud
- [x] Realizar funcionalidad en el mid de sga para el registro necesario de la solicitud 
- [x] Realizar la consulta de las solicitudes  del tercero en cuestion en el componente   lista de solicitudes realizadas

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
