### ISSUE TITLE
Desarrollar componente para visualizar el perfil de cada aspirante por proyecto curricular y periodo determinado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#465]
Se debe desarrollar el componente para poder visualizar el perfil de forma individual para cada uno de los inscritos a un proyecto determinado y periodo dado, se debe crear un nuevo menú en el modulo de admisiones con nombre evaluación de documentos de inscriptos, tener en cuanta el siguiente mockup:

![image](https://user-images.githubusercontent.com/43799065/108554941-cccad980-72c2-11eb-927d-b78e921dce76.png)

Reutilizar el componente  de listar aspirantes, organizar la consulta de la información presente en el mockup, con el botón de acción se debe cargar el componente de detalle inscripción del modulo de inscripción con la información de cada inscrito, tener en cuenta el [mockup](https://docs.google.com/document/d/1ORpJ6bgcF7_mTXIZNSFpVeTcaelIpm8tuGqHZNCIBs8/edit),  la issue debe cumplir con los siguientes requerimiento:

- [x] Realizar el nuevo sub menú informado con el mockup dado y reutilizar el componente definido 
- [x] Reutilizar  la funcionalidad para que cuando se seleccione el periodo y proyecto se cargue la información de los inscritos al programa
- [x] Reutilizar la funcionalidad   para cargar la información de detalle de inscripción para cada inscrito al programa

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
