### ISSUE TITLE
Desarrollar componente para visualizar y aprobar o hacer alguna observación a los documentos solicitados de cada aspirante en la submenu de evaluación de documentos de inscriptos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#466]
Desarrollar componente para visualizar y aprobar o hacer alguna observación a los documentos solicitados de cada aspirante en la submenu de evaluación de documentos de inscriptos, tener en cuenta el desarrolla de la issue #465, se debe desarrollar el componente teniendo en cuenta el `[mockup](https://docs.google.com/document/d/1ORpJ6bgcF7_mTXIZNSFpVeTcaelIpm8tuGqHZNCIBs8/edit), se debe crear un componente que cargue el componente con la acción del botón (ojo) como un pop up teniendo en cuenta el siguiente mockup:

![image](https://user-images.githubusercontent.com/43799065/108562121-626b6680-72cd-11eb-9ade-7eacb4968a1e.png)

dentro de ese componente se puede observar cada uno de los documentos y poder aprobar o realizar una observación a ese documento, esa información se  registrar  en el campo metadatos de documento en el api de documentos_crud, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el componente segun el mockup para la visualización del documento y aprobar o agregar una observación 
- [x] Realizar la funcionalidad para cargar documentación requerida
- [x]  Realizar la funcionalidad de put para actualizar la aprobación o la observación en el api de documentos_crud

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se da por terminada esta tarea.

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
