### ISSUE TITLE
Ajustar el tag de documentos solicitados y detalle de  inscripción en el proceso de inscripción teniendo en cuenta las observacion y/o aprobación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#467]
Se debe ajustar el tag de documento agregando una nueva columna donde se visualice la observación que se le asigne a cada documentos (aprobado o observación), tener en cuenta el mockup:

![image](https://user-images.githubusercontent.com/43799065/108563767-03f3b780-72d0-11eb-840a-f72562ce4ada.png)

esa información también se debe actualizar con el campo de metadatos en la tabla documento en el api de documentos_crud, se debe tambian actualizar el tag de detalle de inscripción teniendo en cuenta el mockup:

![image](https://user-images.githubusercontent.com/43799065/108564096-91370c00-72d0-11eb-8712-be54d3cbecc2.png)

la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar las componentes de documentos solicitados y detalle de inscripción teniendo en cuenta  los borradores de mockup
- [x] Ajustar la consulta con la infomación en el campo dado

**Comment by ricardoavendano** [comment]
Inicio tarea

**Comment by ricardoavendano** [comment]
Se crean columnas con el estado y observación para documentos solicitados
commit: https://github.com/udistrital/sga_cliente/pull/482

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
