### ISSUE TITLE
Crear funcionalidad para realizar la notificación por medio de un correo cuando se realiza una observación en un documento de un inscrito 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#468]
Se debe reutilizar la funcionalidad de notificación por medio de un correo cuando se realizar la observación de un documento particular de un inscrito, para realizar esa funcionalidad tener en cuenta las siguientes issues:

- https://github.com/udistrital/google_mid/issues/1
- https://github.com/udistrital/produccion_academica_cliente/issues/39
-
Se debe utilizar el api de google_mid para realizar la funcionalidad de notificación por un correo, la issue debe cumplir con los siguiente requerimientos:

- [x] Revisar documentación dada para entender el servicio de correos
- [x] Crear plantilla para la notificación del documento 
- [x] Realizar la funcionalidad para enviar el correo al inscrito al que se realiza la observación al documento 
- [x] Realizar la validación del correo del tercero con pop pup

**Comment by ricardoavendano** [comment]
Se realiza ajuste en sga_cliente para envio de mensaje
commit: https://github.com/udistrital/sga_cliente/pull/488/commits/53ce22f50ac9ec4c0be6014b62242368005ef97f
se crea plantilla en google_mid con formato a enviar por correo
commit:

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
