### ISSUE TITLE
Ajustar en todas apis del proyecto SGA la librería de auditoria

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#474]
Se debe realizar el ajuste de la librería de auditoria en todos las apis (no cliente ) del proyecto, tener en cuenta los [repositorios](https://github.com/orgs/udistrital/teams/academica/repositories), la inclusión de la librería  se puede guiar del [repositorio ](https://github.com/udistrital/configuracion_api/blob/release/0.0.1/main.go#L42)de configuración api, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el ajuste a todas las apis del team

**Comment by jupmorenor** [comment]
Esta issue fue finalizada satisfactoriamente
