### ISSUE TITLE
Realizar el funcionalidad para el subproceso de aprobación de solicitudes de actualización de datos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#476]
Se debe realizar el funcionalidad para el subproceso de aprobación de solicitudes de actualización de datos, se debe realizar la funcionalidad para hacer el registro en la tabla solicitud_evolucion _estado para tener la trazabilidad del proceso de aprobación, se debe actualizar la tabla solicitud cuando la solicitud ha sido aprobada y actualizar el estado de la solicitud, realizar la función en el caso que la solicitud tenga una observación, por algún dato quedo o el documentos quedo mal, ajustar el componente para que al visualizar la solicitud y para el rol indicado (simular el rol por el momento) se pueda o aprobar, rechazar o generar una observación, la issue debe cumplir con los siguiente requerimientos :

- [x] Realizar funcionalidad para tener la trazabilidad de la solicitud cuando se cambie de estado      
- [x] Realizar funcionalidad cuando una solicitud es aprobada o rechazada
- [x] Realizar la funcionalidad cuando la solicitud tiene una observación 
- [x] Ajustar el componente para tener la parte administrativa simulando los roles del sistema

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
En la tabla _estado_tipo_solicitud_ 
- El registro con id **17** referencia al tipo de solicitud _cambio de identificación_ y la solicitud es _aprobada_.
- El registro con id **18** referencia al tipo de solicitud _cambio de nombre_ y la solicitud es _aprobada_.
- El registro con id **19** referencia al tipo de solicitud _cambio de nombre_ y la solicitud es _rechazada_.
- El registro con id **19** referencia al tipo de solicitud _cambio de identificación_ y la solicitud es _rechazada_.

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
