### ISSUE TITLE
Realizar el ajuste del proceso completo de admisión desde la preinscrición hasta generar los admitidos del proceso con su respectiva documentación 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#477]
Se debe realizar los ajustes y controlar todos lo errores que puedan salir en el proceso completo de admisión desde el primer momento de la pre inscripción (crear tercero) hasta el momento que se genera el reporte de los admitidos, a mismo tiempo se debe generar un manual donde se evidencie todo el proceso, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el proceso completo y capturar los errores que se estan presentando y ajustar los errores encontrados 
- [x] Realizar la documentación completa donde se explique el proceso de admisión

**Comment by ricardoavendano** [comment]
Realizar el proceso completo y capturar los errores que se estan presentando y ajustar los errores encontrados
commit: https://github.com/udistrital/sga_cliente/pull/492/commits/a199463a0326f6b28597286a74d1e52ffa67e65e

Realizar la documentación completa donde se explique el proceso de admisión
[Fix477_documentacion_inscripcion_usuario_nuevo.docx](https://github.com/udistrital/sga_cliente/files/6108097/Fix477_documentacion_inscripcion_usuario_nuevo.docx)

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
