### ISSUE TITLE
Desarrollar el maquetado del mockup solicitud para el modulo de gestión de prácticas académicas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#478]
Se debe desarrollar el maquetado del [mockup](https://app.diagrams.net/#G12xMORSvr9NOCFy33alD8Ko3uYhB-KJpC), para el proceso de solicitud  por parte del docente final y listado de solicitudes de practicas académicas, la issue debe cumplir con los siguiente requerimientos:

- [x] Realizar mockup Solicitud de Práctica Académica
-
![image](https://user-images.githubusercontent.com/43799065/109343284-1a06f800-783b-11eb-8dcc-20cf7e9121f7.png)

 
 
![image](https://user-images.githubusercontent.com/43799065/109343305-22f7c980-783b-11eb-8e44-6fefa716a99e.png)

- [x] Realizar mockup Lista de solicitudes de prácticas académicas
![image](https://user-images.githubusercontent.com/43799065/109343348-386cf380-783b-11eb-9342-d9582b6c7907.png)

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
