### ISSUE TITLE
Carga de documentos por variable de entorno que sea encriptado, para el uso de gestión documental

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#48]
Parametrizar como variables de entorno los parametros de conexión de Nuxeo
- [x] Las contraseñas quedan en los archivos de variables de entorno.

**Comment by JuanPiedrahita** [comment]
Se cargan las credenciales desde variable de entorno, se deja encriptación de los archivos a consideración con la herramienta [git-crypt](https://github.com/AGWA/git-crypt).

**Comment by DianaPatriciaRamirez** [comment]
Se sugiere revisión y aprobación de la sugerencia realizada por el ingeniero @JuanPiedrahita, de utilizar la herramienta git-crypt para la encriptación de archivos, a los ingenieros @mafeave @corio27 @jairolh @fernandotower
