### ISSUE TITLE
Carga de documentos para historial de acreditaciones

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#49]
Agregar funcionalidad para cargar documentos cuando se agrega el historial de acreditaciones
- [x] El cliente solicita los documentos necesarios para crear una acreditación.
- [x] El cliente carga y guarda los documentos en el sistema de gestión documental.
- [x] El cliente guarda los documentos en el sistema de gestión academica.

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea se deja evidencai de subida de archivo de creación de registro.

![imagen](https://user-images.githubusercontent.com/25555966/67149259-cf509580-f26e-11e9-9406-e70b2a345586.png)

**Comment by JuanPiedrahita** [comment]
Para probar la tarea usar:
- sga_cliente: rama feature/nuxeo
- sga_mid: rama dev
- oikos_api
- proyecto_academico_crud: rama feature/transacciones_registro
- documentos_crud: rama feature/nuxeo, rama creada temporalmente, lo único que se necesita en realidad es que el tipo de documento referencie al Workspace donde se guardara el documento y que existan los dos migrations para el registro del documento 
```sql
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Resolución registro calificado','Documento de resolución asociada a un registro calificado','RRC', true,9,5,'pdf','/desarrollo/workspaces/planestic/Inscripcion/Descuentos','File'); -- Id 9
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Acto adminnistrativo proyecto','Documento de acto administrativo por el que se crea un proyecto academico','AAP', true,10,5,'pdf','/desarrollo/workspaces/planestic/Inscripcion/Descuentos','File'); -- Id 10
```

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea pero se evidencia la falta de funcionalidad para actualiizar los documentosde los registros que se suben en el componente de modificación.

**Comment by mafeave** [comment]
Se verifica subida de documento a NUXEO.

Revisar la carga del documento en ventana nueva:
![image](https://user-images.githubusercontent.com/14035745/67203710-6b92ad80-f3d1-11e9-8cc0-cf3c57e92f8b.png)

**Comment by mafeave** [comment]
Se debe verificar con el API local para verificar si el problema se debe a permisos sobre el API de Planestic

**Comment by mafeave** [comment]
Se ajusta carga de archivo en ventana nueva, https://github.com/udistrital/sga_cliente/commit/ebcc42b061c2ae3bc7fc7d6b3dbadc0266051ddf, https://github.com/udistrital/sga_cliente/commit/ebd865cce965399a91615aa1b44b9ed5b65a641c

![Captura de pantalla de 2019-11-12 05-55-15](https://user-images.githubusercontent.com/14035745/68666651-4e558880-0512-11ea-96f1-60de3f0bff3a.png)
