### ISSUE TITLE
Asignación de roles en el proyecto

### ISSUE THREAD

**Issue by gabrielablanco** [udistrital/sga_cliente#491]
Se debe realizar un servicio que centralice la captura del rol de cada usuario en donde dependiendo de como se loguea se le mostrará los menús, sub-menús o algún componente específico. La issue debe cumplir con los siguientes requerimientos:
- [x] Analizar el modelo de datos de _configuracion-crud_ (https://github.com/udistrital/configuracion_api/blob/dev/sql/configuracion_schema_v2.png) y registrar la información del sistema en éste
- [x] Configurar la visualización del menú dependiendo del rol asignado a ese usuario

**Comment by gabrielablanco** [comment]
Teniendo en cuenta la tabla **_menu-opcion-padre_** se obtiene la siguiente jerarquía del menú de SGA:
1. **Padre:** solicitudes
    **Hijos:** 
    - Lista de solicitudes (_URL_: /pages/solicitudes/list-solicitudes-estudiante)
2. **Padre:**: solicitud
    **Hijos:**  
    - Actualizar identificación (_URL_: /pages/solicitud/actualizacion-datos)
    - Actualizar nombres (_URL_: /pages/solicitud/actualizacion-nombres)
3. **Padre:** Gestionar solicitudes
    **Hijos:**  
    - Solicitudes de actualización (_URL_: /pages/solicitudes/gestionar-solicitudes)
4. **Padre:** Calendario académico
    **Hijos:**  
    - Listar calendarios académicos (_URL_: /pages/calendario-academico/list-calendario-academico)
    - Calendario académico por proyecto (_URL_: /pages/calendario-academico/calendario-proyecto)
5. **Padre:** Periodo
    **Hijos:** 
    - Lista Periodo (_URL_: /pages/periodo/list-periodo)
    - CRUD Periodo (_URL_: /pages/periodo/crud-periodo)
6. **Padre:** Proyecto Academico
    **Hijos:** 
    - Registro de un Proyecto (_URL_: /pages/proyecto_academico/crud-proyecto_academico)
    - Listar Proyectos (_URL_: /pages/proyecto_academico/list-proyecto_academico)
7. **Padre:** Inscripcion
    **Hijos:**  
    - Pre Inscripcion (_URL_: /pages/inscripcion/preinscripcion)
8. **Padre:** Admision
    **Hijos:**   
    - Administrar criterios (_URL_: /pages/admision/administrar-criterios)
    - Criterios admisión (_URL_: /pages/admision/criterio_admision)
    - Actualizacion Estado (_URL_: /pages/admision/asignacion_cupos)
    - Evaluación de documentos de inscritos (_URL_: /pages/admision/evaluacion-documentos-inscritos)
    - Evaluación de aspirantes (_URL_: /pages/admision/evaluacion-aspirantes)
9. **Padre:** Derechos Pecuniarios
    **Hijos:**  
    - Consultar conceptos (_URL_: /pages/derechos-pecuniarios/consultar-conceptos)
    - Definir Conceptos (_URL_: /pages/derechos-pecuniarios/crud-derechos-pecuniarios)
    - Asignar valores (_URL_: /pages/derechos-pecuniarios/list-derechos-pecuniarios)
10. **Padre:** Archivo Icfes
      **Hijos:**  
     - Registrar archivo (_URL_: /pages/archivo_icfes/crud-archivo_icfes)
11. **Padre:** Reportes
      **Hijos:** 
      - Inscripciones [Inscritos por proyecto (_URL_: /pages/reportes/inscripciones/inscritos-proyecto)]
      - Icfes [Registro Icfes por proyecto (_URL_: /pages/reportes/icfes_SNP/icfes-proyecto)]
      - Proyectos [Proyectos (_URL_: /pages/reportes/proyectos/list-proyectos), HistoricoAcreditaciones (_URL_: /pages/reportes/proyectos/historico-acreditaciones)]
12. **Padre:** Administración
      **Hijos:**  
      - enfasis [Registrar Enfásis (_URL_: /pages/enfasis/crud-enfasis), Listar Enfásis (_URL_: /pages/enfasis/list-enfasis)]
      - Tipo Inscripción (_URL_: /pages/tipo_inscripcion/list-tipo_inscripcion)

**Comment by gabrielablanco** [comment]
A continuación se mostrarán las secciones del menú junto con los roles que tienen acceso a éstas:

**Todo el menú**
- ADMIN OAS (ID: 113)
- ADMINISTRADOR (ID: 152)
- ADMIN SGA (ID: 114) 

**Prácticas académicas (Nueva solicitud, Invitación prácticas académicas, Solicitudes en proceso)**
- ADMIN_DOCENCIA (ID: 112)
- DOCENTE (ID: 138)

**Prácticas académicas (Nuevas solicitudes)**
- LABORATORIOS (ID: 140) 
- ADMIN_CAMPUS (_Pendiente_)
- COORDINADOR (ID: 133)
- FUNCIONARIO (ID: 139)

**Datos básicos (listado)**
- ADMIN_CAMPUS (_Pendiente_)
- COORDINADOR (ID: 133)
- FUNCIONARIO (ID: 139)
- ESTUDIANTE (ID: 154)

**Actualización datos**
- ESTUDIANTE (ID: 154)

**Datos estudiantes**
_Pendiente_

**Calendario académico (todo), Periodo (todo), Proyecto académico (todo), Derechos pecuniarios (todo)**
- SEC_ACADEMICO (ID: 143)
- SEC_GENERAL (ID: 144)
- SEC_PROYECTO (ID: 146)
- ADMIN_CAMPUS (_Pendiente_)

**Reportes (todo), Administración (todo)**
- SEC_ACADEMICO (ID: 143)
- SEC_GENERAL (ID: 144)
- SEC_PROYECTO (ID: 146)
- ADMIN_CAMPUS (_Pendiente_)
- COORDINADOR (ID: 133)
- FUNCIONARIO (ID: 139)

**Inscripción**
- ASPIRANTE (_Pendiente_)

**Admisiones (todo), Archivo ICFES (todo)**
- ADMISIONES_REG (ID: 116)
- ADMIN_CAMPUS (_Pendiente_)

**Comment by gabrielablanco** [comment]
Por otro lado, se añade la siguiente jerarquía que se presentó en el menú
13. **Padre:** Prácticas académicas ID: 711
    **Hijos:** 
    - Nueva solicitud (_URL_ /pages/practicas-academicas/nueva-solicitud) ID: 712
    - Nuevas solicitudes (_URL_ /pages/practicas-academicas/lista-practicas) ID: 713
    - Solicitudes en proceso (_URL_ /pages/practicas-academicas/lista-practicas) ID: 714
    - Invitacion(_Sin URL_) ID: 715

**Comment by gabrielablanco** [comment]
El usuario **_utest01_** cuenta con los siguientes roles:
- "ADMIN_CAMPUS"
- "DOCENTE"
- "CONTRATISTA"
- "Internal/everyone"
- "Internal/selfsignup"
- "Application/utest01_DefaultApplication_SANDBOX"
- "ESTUDIANTE"

Por otro lado, el usuario _**pruebasoas**_ cuenta con los siguientes roles:
- "Internal/everyone"-
- "SUPERVISOR"
- "ADMIN_NECESIDADES"
- "ADMIN_PRESUPUESTO"
- "ADMIN_CONTABILIDAD"
- "ESTUDIANTE"
- "Application/pruebasoas_DefaultApplication_SANDBOX"

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by gabrielablanco** [comment]
La jerarquía del módulo de admisiones ha sido actualizada quedando así:
8. **Padre**: Admision ID: 686
    **Hijos**:
- Administrar criterios (URL: /pages/admision/administrar-criterios) ID: 687
- Criterios admisión (URL: /pages/admision/criterio_admision) ID: 688
- Actualizacion Estado (URL: /pages/admision/asignacion_cupos) ID: 689
- Listar aspirantes (URL: /pages/admision/listado_aspirante) ID: 751
- Evaluación de documentos de inscritos (URL: /pages/admision/evaluacion-documentos-inscritos) ID: 690
- Evaluación de aspirantes (URL: /pages/admision/evaluacion-aspirantes) ID: 691

**Comment by gabrielablanco** [comment]
Se ha añadido un nuevo componente al proyecto llamado _**Espacios académicos**_ en donde se añade la siguiente jerarquía en el menú:
13. **Padre**: Espacios académicos ID: 752
      **_Hijos_**:
- Preinscripcion espacios (URL /pages/espacios-academicos) ID: 753

El rol que tendrá acceso a este componente es ESTUDIANTE (ID: 154)

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
