### ISSUE TITLE
Ajustes en el módulo de inscripción y admisión según reunión del 17 de marzo

### ISSUE THREAD

**Issue by ricardoavendano** [udistrital/sga_cliente#499]
En la reunión del 17 de marzo del 2021, se creó un usuario desde 0 en donde se encontraron los siguientes ajustes para la funcionalidad del módulo de inscripción y admisiones. Por ello, se encontraron los siguientes ajustes:
- [x] Se debe quitar del módulo de _preinscripcion_ en el genero "No aplica". Para ello de debe revisar los datos de la API.
- [x] Cuando se guarde la _información  básica_ en el módulo de  pre-inscripción se debe _"cambiar"_  la pestaña al módulo de _inscripción_.
- [x] A la hora de inscribirse a un programa académico solo se debe dejar el nivel de posgrado.
- [x] Se deben controlar los errores a la hora de generar una inscripción.
- [x] Una vez generado el recibo de pago en el módulo de inscripción se debe cargar dicha información en la tabla.
- [x] En el módulo de periodos, se debe ajustar el orden de la tabla mostrándola de primeras.
- [x] En el módulo de inscripción se deben actualizar el porcentaje de los tabs de cada categoría (Información básica, formación académica, etc.).
- [x] Se debe revisar los spinner cuando sale error, puesto que algunos no se detienen.
- [x] En admisiones en el módulo de actualización de estado aspirante se debe tener en cuenta que no hay cupos especiales ni opcionados por lo que esa que muestra cupos especiales NO ES NECESARIA, solo se tiene en cuenta los siguientes descuentos: monitor, egresado y certificado electoral. Teniendo en cuenta lo anterior, solo se pedir el número de cupos a cada proyecto.
- [x] Verificar y corregir la función en el MID sobre el cambio de estado de los aspirantes **(No funciona con el usuario nuevo)**
- [x] Se deben desacoplar los componentes en el módulo de actualización de estado de aspirantes.
- [x] Cuando se guarde información en el componente de información básica se debe cambiar de pestaña, ya que no es intuitivo si hay varias.
- [x] Se debe ocultar barra de pre-inscripción cuando se está inscribiendo la información del aspirante para evitar confusiones.
- [x] El tab de _información familiar_ no debería estar en el módulo de información básica.
- [x] En el módulo de inscripción se debe ocultar el botón de _regresar_ cuando se ingrese a un tab.
- [x] Se debe revisar el _progressbar_ con el fin de que cargue el porcentaje completo.
- [x] El módulo de _descuento de matricula, producción académica_ y _propuesta trabajo de grado_ NO debe pedirse o tenerse en cuenta para cargar el progressbar. 
- [x] Se deben cagar los porcentajes apenas se abra la ventana de inscripciones.
- [x] Se debe ajustar la carga la información que se había guardado en el módulo _actualización de estado de aspirantes_.
- [x] Se debe ajustar el rol Internal/everyone.
- [x] Se debe agregar la funcionalidad para asignarle un porcentaje a los subcriterio de un criterio específico teniendo en cuenta la estructura que aparece en el siguiente modelo de datos: https://user-images.githubusercontent.com/11802554/106519727-bbec2c80-64a9-11eb-9b9b-fff2c0df868d.png
- [x] Eliminar estilos SCSS duplicados para reducir el consumo de memoria durante la compilación.
- [x] Ajustar el control de errores del MID en formación académica.
- [x] Ajustar control de errores en el componente de formación académica.
- [x] Ajustar el llamado de la función GET del componente de inscripción en el tab de producción académica
- [x] Ajustar el menú con los nuevos módulos que se han añadido al desacoplar el módulo de admisiones
- [x] Ajustar el ancho de las tablas del detalle de inscripción.

**Comment by ricardoavendano** [comment]
En admisiones en el módulo de actualización de estado aspirante se debe tener en cuenta que no hay cupos especiales ni opcionados por lo que esa que muestra cupos especiales NO ES NECESARIA, solo se tiene en cuenta los siguientes descuentos: monitor, egresado y certificado electoral. Teniendo en cuenta lo anterior, solo se pedir el número de cupos a cada proyecto.
commit: https://github.com/udistrital/sga_cliente/pull/507/commits/0de52d1632a97e1d9b7307c6833f1b4bcd2553fb

**Comment by ricardoavendano** [comment]
- [ ] Se deben desacoplar los componentes en el módulo de actualización de estado de aspirantes.

- [ ] Se debe ajustar la carga la información que se había guardado en el módulo actualización de estado de aspirantes.

commit: https://github.com/udistrital/sga_cliente/pull/507/commits/c6868022a87a7bdbe75fb7ac0f1d19e83944bc05

**Comment by ricardoavendano** [comment]
Ajuste modulo admisiones, cambio estado inscritos a admitidos
Commit: https://github.com/udistrital/sga_cliente/pull/509/commits/bffa16249399b213b156d020eb7ee810323d37bc

**Comment by ricardoavendano** [comment]
Se debe agregar la funcionalidad para asignarle un porcentaje a los subcriterio de un criterio específico teniendo en cuenta la estructura que aparece en el siguiente modelo de datos: https://user-images.githubusercontent.com/11802554/106519727-bbec2c80-64a9-11eb-9b9b-fff2c0df868d.png
Commit: https://github.com/udistrital/sga_cliente/pull/517/commits/9d4ddcb7a44b0a9c44709fd36f94248c7888972a

**Comment by ricardoavendano** [comment]
Ajuste JSON subcriterios modulo criterios de admisiones por proyectos
commit: https://github.com/udistrital/sga_cliente/pull/526/commits/c9d2c9a8384e7bb1f690eb27a636df5f6e88008a

**Comment by jupmorenor** [comment]
Se han realizado todos los ajustes requeridos y los que surgieron durante el proceso.
Se autoriza la salida a producción.
