### ISSUE TITLE
Carga de documentos para creación de proyectos

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#50]
Agregar funcionalidad para cargar documentos cuando se crear un proyecto academico.
- [x] El cliente solicita los documentos necesarios para crear un proyecto academico.
- [x] El cliente carga y guarda los documentos en el sistema de gestión documental.
- [x] El cliente guarda los documentos en el sistema de gestión academica.

**Comment by JuanPiedrahita** [comment]
Se da por temrinada la tarea

**Comment by JuanPiedrahita** [comment]
Para probar la tarea usar:
- sga_cliente: rama feature/nuxeo
- sga_mid: rama dev
- oikos_api
- proyecto_academico_crud: rama feature/transacciones_registro
- documentos_crud: rama feature/nuxeo, rama creada temporalmente, lo único que se necesita en realidad es que el tipo de documento referencie al Workspace donde se guardara el documento y que existan los dos migrations para el registro del documento 
```sql
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Resolución registro calificado','Documento de resolución asociada a un registro calificado','RRC', true,9,5,'pdf','/desarrollo/workspaces/planestic/Inscripcion/Descuentos','File'); -- Id 9
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Acto adminnistrativo proyecto','Documento de acto administrativo por el que se crea un proyecto academico','AAP', true,10,5,'pdf','/desarrollo/workspaces/planestic/Inscripcion/Descuentos','File'); -- Id 10
```

**Comment by mafeave** [comment]
Se verifica carga de documento a NUXEO.

Revisar la carga del documento subido en ventana nueva:
![image](https://user-images.githubusercontent.com/14035745/67203382-92041900-f3d0-11e9-946c-51633a3dee1a.png)

**Comment by mafeave** [comment]
Se debe verificar con el API local para verificar si el problema se debe a permisos sobre el API de Planestic

**Comment by mafeave** [comment]
Se ajusta carga de archivo en ventana nueva, https://github.com/udistrital/sga_cliente/commit/ebcc42b061c2ae3bc7fc7d6b3dbadc0266051ddf, https://github.com/udistrital/sga_cliente/commit/ebd865cce965399a91615aa1b44b9ed5b65a641c

![Captura de pantalla de 2019-11-12 05-55-15](https://user-images.githubusercontent.com/14035745/68666123-4a753680-0511-11ea-9a0b-a4bd5a29f4ad.png)
