### ISSUE TITLE
Maquetado para Preinscripción de espacios académicos

### ISSUE THREAD

**Issue by gabrielablanco** [udistrital/sga_cliente#500]
Se debe realizar el mockup de la preinscripción de espacios académicos con el fin de obtener el número de créditos preinscritos para asignar un valor a la matrícula (en caso de posgrado, en pregrado se omite el proceso del cálculo); para ello la issue debe cumplir con los siguientes requerimientos:
- [x] Desarrollar el mockup (https://app.diagrams.net/#G1WMXrvHeAna0d0xfSIfy3FXijJM1ExioN - https://app.diagrams.net/#G1WMXrvHeAna0d0xfSIfy3FXijJM1ExioN)
- [x] Simular la malla curricular para poder realizar la preinscripción (créditos, nombre materia, etc)

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea.
