### ISSUE TITLE
Ajustar el formulario de consulta a dos columnas - 3 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#51]
Se debe realizar ajuste del tap de consulta de un proyecto académico, este cuenta actualmente con un dimensión muy larga, se debe dividir el tag a dos columnas.

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste del tap de consulta, dividendo el card de información basica en dos columnas por observación de la lider técnica @mafeave  se espera revisión.

**Comment by mafeave** [comment]
Se verificará una vez que se validen los despliegues de las APIs de: documentos_crud, proyecto_academico_crud y sga_mid. Dirección de pruebas: pruebassga.portaloas.udistrital.edu.co
