### ISSUE TITLE
Carga de documentos para edición de proyectos

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#52]
Agregar funcionalidad que permita cargar los documentos necesarios para editar la información de un proyecto curricular y de sus registros calificados.
- [x] El sistema permite editar los documentos de los registros.
- [x] El sistema permtie editar el documento de creación del proyecto.

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea, sin embargo se observa que siempre qeu se consulta un registro de alta caldiad trae un registro diferente, este bug debe solucionarse, sin embargo esto no afecta la modificación del archivo esto se esta realizando de forrma correcta.

**Comment by mafeave** [comment]
Se verificará la funcionalidad, una vez que se validen los despliegues de las APIs de: documentos_crud, proyecto_academico_crud y sga_mid
