### ISSUE TITLE
Realizar despliegue en producción de APIs para despliegue de cliente

### ISSUE THREAD

**Issue by jupmorenor** [udistrital/sga_cliente#529]
Desplegar en producción las APIs que se necesitan para el despliegue de SGA Cliente, se debe actualizar `drone.yml` cuando sea necesario.

- [x] Inscripción 
- [ ] Evaluación Inscripción
- [x] Proyecto académico
- [ ] Descuento académico
- [x] Eventos
- [x] Idiomas
- [x] Solicitudes
- [x] Producción académica
- [ ] Persona
- [x] SGA MID
- [x] Google MID
- [ ] SGA Cliente

En algunos casos solo hay que hacer push sobre master.

**Comment by jupmorenor** [comment]
Adjunto enlaces a Kanban de las solicitudes realizadas a Infraestructura y DBA:

- produccion_academica_crud  pruebas: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41586
- produccion_academica_crud  produccion: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41590
- eventos_crud pruebas: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41591
- eventos_crud  produccion: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41592
- inscripcion_crud pruebas: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41593
- inscripcion_crud produccion: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41594
- proyecto_academico_crud pruebas: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41595
- proyecto_academico_crud produccion: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41596
- descuento_academico_crud pruebas: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41597
- descuento_academico_crud produccion: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41598
- evaluacion_inscripcion_crud produccion https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41773
- evaluacion_inscripcion_crud  pruebas: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41775
- Bases de datos: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=41674

**Comment by fabianbarreto02** [comment]
Se da continuidad con la issue en la isuue https://github.com/udistrital/sga_cliente/issues/532
