### ISSUE TITLE
Realizar el cargue de un documento (una resolución de Decanatura) cuando se nombra o cambia un Coordinador de Proyecto Curricular

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#53]
Realizar carga de docmento cuando se nomba o cambia un coordinador en un proyecto academico.
- [x] El sistema debe almacenar la información del documento de resolución.
- [x] El sistema debe dejar consultar el documento por el cual se nombra al docente.

**Comment by JuanPiedrahita** [comment]
El sistema permite la cara y descarga del documento. Para probar la tarea usar:
- sga_cliente: rama feature/nuxeo
- sga_mid: rama dev
- oikos_api
- proyecto_academico_crud: rama feature/transacciones_registro
- documentos_crud: rama feature/nuxeo, rama creada temporalmente, lo único que se necesita en realidad es que el tipo de documento referencie al Workspace donde se guardara el documento y que existan los dos migrations para el registro del documento. **Importante** se agrego el registro 11 para tipo_documento, en documentos_crud.
```sql
INSERT INTO documento.tipo_documento(nombre, descripcion, codigo_abreviacion, activo, numero_orden,tamano,extension,workspace,tipo_documento_nuxeo) VALUES ('Resolución asignación coordinador','Documento de acto administrativo por el que se asigna un nuevo coordinador a un proyecto','RAC', true,11,5,'pdf','/desarrollo/workspaces/planestic/Inscripcion/Descuentos','File');
```

Se da por terminada la tarea.

**Comment by mafeave** [comment]
La funcionalidad se verificará una vez que se verifiquen los despliegues de las APIs de: documentos_crud, proyecto_academico_crud y sga_mid

**Comment by mafeave** [comment]
Se hace la prueba de asignación del coordinador a un proyecto académico:
![Captura de pantalla de 2019-11-14 17-08-34](https://user-images.githubusercontent.com/14035745/68900544-114fe880-0702-11ea-8d09-69af9db45e57.png)

Pero cuando se vuelve a consultar la información del proyecto no está cargando el documento subido al momento de hacer la asignación del coordinador:
![Captura de pantalla de 2019-11-14 17-14-42](https://user-images.githubusercontent.com/14035745/68900674-5116d000-0702-11ea-91fd-35c2b8f55262.png)

**Comment by mafeave** [comment]
Se despliegan ajustes faltantes en API de proyecto_academico_crud, con lo cual ya se puede acceder correctamente a la funcionalidad.
![Captura de pantalla de 2019-11-20 15-32-56](https://user-images.githubusercontent.com/14035745/69275986-83fe0f80-0bab-11ea-8234-6673435d88db.png)

Funcionalidad desplegada en ambiente de pruebas, se da por finalizada la tarea.
