### ISSUE TITLE
Ajustar el campo date: Fecha de creación - Firefox (no carga): ajustarlo al componente usado en el formulario de registro de proyecto curricular.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#54]
Se debe ajustar los datepicker del componente del formulario de registro de un proyecto curricular por incompatibilidad de navegadores, esta tarea surge de una observación en la [issue](https://github.com/udistrital/sga_cliente/issues/37).

Lider Técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste

**Comment by fabianbarreto02** [comment]
Se ajusta los campos date en todos los componentes faltantes para compatibilidad con navegadores, se espera revisión por parte de @mafeave  y @JuanPiedrahita

**Comment by mafeave** [comment]
La funcionalidad se verificará una vez que se validen los despliegues de las APIs de: documentos_crud, proyecto_academico_crud y sga_mid
