### ISSUE TITLE
Ajustar carga del coordinador de un proyecto academcio

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#540]
Se debe ajustar el servicio de carga del coordinador en la función de edición del proyecto académico pasando del servicio personas_crud(no funcional) al servicio de tercero_crud, solo se debe cargar solo los terceros que tengan en la tabla vinculacion el cargo_id con el id de docente, la issue debe cumplir con los siguientes requerimientos 

- [x] Ajustar la carga con el servicio antes definido 
- [x] Ajuste de función para la asignación del coordinador en el modulo de proyecto académico

**Comment by JQuinteroC** [comment]
Se inicia la issue

**Comment by fabianbarreto02** [comment]
Se incluye nuevo item

**Comment by JQuinteroC** [comment]
se concluye desarrollo, a la espera de revisión
