### ISSUE TITLE
Capturar error cuando no existe menú definido para un rol WSO2

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#541]
Se debe ajustar y capturar el error cuando un usuario se logue y no tenga menú definido en el api de configuraciones, se debe mostrar un modal informando que no tiene menú definido, la issue debe cumplir con los siguientes requerimiento:

- [x] Capturar el error y crear el modal para informar al usuario

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se da por finalizada
