### ISSUE TITLE
Revisar y ajustar los labels para los menus 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#544]
Se debe revisar el porque no funciona el label del menú en diferentes módulos, los módulos que se tienen que revisar son:

- [ ] Derechos pecuniarios / Asignar Valores 
- [ ] Archivos icfes / ...
- [ ] Reportes / ....
- [ ] Administración / ...

**Comment by fabianLeon** [comment]
Lo que veo es que el componente no está diseñado para más de dos niveles, propongo ajustar el menú para solo 2 niveles y redefinir los títulos.

**Comment by fabianbarreto02** [comment]
Por favor ajustar el menu con los 2 niveles, incluir la ruta en la issue para ajustar el arbol de menu en configuraciones

**Comment by fabianLeon** [comment]
Se ajusta componente para n niveles, de esta manerra se resuelven labels.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
