### ISSUE TITLE
Incluir etiquetas en los botones de las tablas del cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#546]
Se debe incluir etiquitas en las acciones de las tablas para dar un mayor entendimiento al usuario, se puede guiar con la imagen:
![image](https://user-images.githubusercontent.com/43799065/125014470-6822d800-e033-11eb-9126-c8f899a8cf41.png)

Se debe realizar el ajuste en las siguientes tablas:

- [x] Datos básicos / lista de solicitudes realizadas
- [x] Calendario académico / listar calendario académicos
- [x] Habilitar periodo / Habilitar/Deshabilitar un periodo
- [ ] Proyecto académico / lista proyecto académico
- [x] Admisiones / administrar criterios de admisión 
- [x] Derechos pecuniarios / definir conceptos (seleccionar vigencia) 
- [x] Derechos pecuniarios / asignar valores (seleccionar vigencia)
- [x] Administración / Tipo inscripción

También se debe ajustar que cuando se crea un periodo se re direccione a la tabla de los periodos ya creados.

- [x] Ajustar re dirección de periodos

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by JQuinteroC** [comment]
Se concluye con la issue quedando pendiente la tabla "Proyecto académico / lista proyecto académico" por modificación en el diseño pendiente

**Comment by fabianbarreto02** [comment]
Se revisa la issue, se da por finalizada la issue
