### ISSUE TITLE
Revisión del estado actual de actualización de datos, ajuste de visualización segun rol y proceso de solicitud, revisión y aprobación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#547]
Se debe realizar la revisión del estado actual de modulo de actualización de datos, revisar hasta donde esta el proceso, si se genera la solicitud en el api de solicitudes, que información se relaciona  en la solicitud, revisar si  el componente de respuesta de la solicitud funciona realizando la revisión, aplazamiento o aprobación a las solicitudes realizadas, también se debe  ajustar la visualización del componente según sea el rol (ESTUDIANTE y COORDINADOR), de no estar desarrollado la parte de seguimiento y aprobación se debe iniciar con el desarrollo, la issue debe cumplir con los siguientes requerimiento:

- [x]  Revisar hasta donde esta el alcance de los módulos de datos básicos y actualización de datos
- [x] Ajustar la visualización del componente para los dos roles presenten en el proceso
- [ ] Si no esta desarrollado los cambios de estados de l solicitud (aplazada, aprobada o rechazada) realizar el desarrollo a nivel backend (mid y api)
-

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by JQuinteroC** [comment]
Se suspende la issue por solicitud del líder tecnico

**Comment by fabianbarreto02** [comment]
El requerimiento faltante se pasa a una tarea independiente, el motivo de la suspensión de la issue, fue los ajustes solicitados  en los modulos de inscripción y de admisión para la realización de las pruebas pilotos y funcionales por usuarios, se da por finalizada la issue.
