### ISSUE TITLE
Cambiar tabla de proyectos academicos a ng2-smart-table

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#561]
Se debe actualizar la tabla en el componente proyecto académico en el modulo de listar proyecto con el componente ng2-smart-table para unificar el cliente, la issue debe cumplir con los siguientes requerimientos:

- [x] Actualizar tabla con el componente definido
- [x] Ajustar la funcionalidad ya existente ( consulta, editar y Inhabilitar/Habilitar)

**Comment by JQuinteroC** [comment]
Se da inicio con la issue

**Comment by fabianbarreto02** [comment]
Se revisa la issue se da por finalizada la issue
