### ISSUE TITLE
Revisión y ajuste  del modulo de inscripción con el proceso completo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#567]
Se debe realizar una revisión completa y realizar los ajustes del modulo de inscripción, para esto debe realizar los siguientes requerimientos:

- [x] Crear un usuario de wso2 para simular todo el proceso, se debe documenta en la issue el usuario creado.
- [x]  Crear y simular la información personal para el nuevo usuario, se debe verificar la creación y la consulta cuando ya se halla creado la información 
- [x] Realizar el proceso de una nueva inscripción para la verificación de los tres estados del recibo, cuando se crea se debe permitir observar el recibo y habilitar la opción de pago en linea, cuando se encuentra vencido no se debe permitir ni ver el recibo ni ninguna opción y como ultimo estado de recibo es pago (asignar el recibo con secuencia 30778/2020) este estado puede ver el recibo y la opción de inscribirme
- [x] Al ingresar a la opción de inscribirme el select de programa debe cargarse con el programa establecido en la tabla de recibos generados, este select se debe poder cambiar el programa
- [x] Revisar, simular y ajustar el tag de información básica crear información característica e información de contacto, revisar la carga de información registrada .
- [x]   Revisar, simular y ajustar el tag de formación  académica crear una información de formación académica  e Idiomas, revisar la carga de información registrada .
- [x]   Revisar, simular y ajustar el tag de Experiencia laboral  crear una información de experiencia laboral , revisar la carga de información registrada .

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by JQuinteroC** [comment]
usuario: inscripcion01

**Comment by JQuinteroC** [comment]
se concluye desarrollo, a la espera de revisión

**Comment by JQuinteroC** [comment]
Se realizan correciones

**Comment by fabianbarreto02** [comment]
Se da por  finalizada  la issue
