### ISSUE TITLE
Ajustar consulta de grupos de investigación y líneas de investigación con nuevos endpoint

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#568]
Se debe ajustar la  consulta en el tag de trabajo de grado, con los siguiente requerimientos: 

- [x] Para el select de Grupos de investigación: research_units,  y organizar la data( solo Nombres)

- [x] Líneas de investigación: subtypes, filtrar en el cliente los que tienen "type_id": 53

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by JQuinteroC** [comment]
se concluye desarrollo, a la espera de revisión

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
