### ISSUE TITLE
Realizar reportes de proyecto curricular, Listado de Proyectos Académicos, en spagobi

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#57]
Crear reporte que liste todos los proyectos académicos.
- [x] El reporte permite listar los proyectos académicos.

**Comment by JuanPiedrahita** [comment]
El reporte debe tener las siguientes caracteristicas

Nombre del Reporte | Campos Obligatorios | Parámetros de búsqueda
-- | -- | --
Listado de Proyectos Académicos | -Código SNIES-Nombre del Proyecto-Nivel-Abreviación-Correo Electrónico-Duración-Tipo de duración-Tipo de Registro-Ciclos Propedéuticos-Cuenta con enfásis | -Facultad-Nivel-Metodología-Se ofrece
-- | -- | --

**Comment by JuanPiedrahita** [comment]
SE agrega [plantilla](https://drive.google.com/open?id=1lXSBc4ZOwFP5L0mzB2JvyDopj7sgzmMB) del deploy y se despliega en SpagoBi.

**Comment by JuanPiedrahita** [comment]
SE agrega evidencia de ejecucion del reporte

![imagen](https://user-images.githubusercontent.com/25555966/67902843-1b85ba80-fb38-11e9-974c-af488da465d0.png)

**Comment by JuanPiedrahita** [comment]
se da por terminada la tarea

**Comment by mafeave** [comment]
Se sugiere ajustar formato del reporte, incluyendo el nombre del Macroproceso y Proceso correspondiente. Esta observación se trabajará mediante el issue https://github.com/udistrital/sga_cliente/issues/67
