### ISSUE TITLE
Revisión y ajustes del modulo de admisiones con el proceso  completo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#571]
Se debe realizar la revisión y realizar los ajustes correspondientes para el modulo de admisiones cuando se realiza el proceso completo, la issue debe cumplir con los siguiente requerimiento:

- [x] Realizar la revisión y los posible ajustes para el submodulo de administración de criterios de admisión 
- [x] Realizar la revisión y los posible ajustes para el submodulo de  criterios de admisión  por proyecto
- [x] Realizar la revisión y los posible ajustes para el submodulo de Asignación de cupos por proyecto
- [x]  Realizar la revisión y los posible ajustes para el submodulo de  Evaluación de documentos de inscritos 
- [x] Realizar la revisión y los posible ajustes para el submodulo de  Evaluación de aspirantes
- [x] Realizar la revisión y los posible ajustes para el submodulo de  Listar aspirantes

**Comment by JQuinteroC** [comment]
Se concluye con el desarrollo y se da espera a revisión y aprovación

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
