### ISSUE TITLE
Realizar reportes de proyecto curricular: Histórico de Acreditaciones de un Proyecto Académico, en spagobi

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#58]
Se debe crear un reporte que dado un proyecto curricular liste todos sus registros de acreditación.
- [x] El reporte recibe como input el id de un proyecto curricular.
- [x] El reporte lista todos los registros de un proyecto curricular.

**Comment by JuanPiedrahita** [comment]
El reporte debe tener las siguientes caracteristicas

Nombre del Reporte | Campos Obligatorios | Parámetros de búsqueda
-- | -- | --
HIstórico de Acreditaciones de un Proyecto Académico | -Código SNIES-Nombre del Proyecto-Nivel-Abreviación-Correo Electrónico-Tipo de duración-Fecha de aprobación del proyecto-Fecha renovación registro calificado vigente-No. Registro calificado vigente-Fecha de aprobación de Alta Calidad-No. Registro Alta Calidad vigente-Fecha renovación registro alta calidad vigente-Ciiclos Propedéuticos-Cuenta con enfásis | -Nombre del Proyecto
-- | -- | --

**Comment by JuanPiedrahita** [comment]
SE agrega [plantilla](https://drive.google.com/open?id=11L3yhR27hjaLyt3DJBnhSyTg5i0d_7DJ) del deploy y se despliega en SpagoBi.

**Comment by JuanPiedrahita** [comment]
SE agrega evidencia de ejecucion del reporte

![imagen](https://user-images.githubusercontent.com/25555966/67903000-7c14f780-fb38-11e9-9114-1f91181060a4.png)

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea

**Comment by mafeave** [comment]
Se sugiere ajustar formato del reporte, incluyendo el nombre del Macroproceso y Proceso correspondiente. Esta observación se trabajará mediante el issue https://github.com/udistrital/sga_cliente/issues/67
