### ISSUE TITLE
Ajustar porcentaje de avance en documentos en inscripción y experiencia laboral

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#586]
Se debe ajustar la visualización del porcentaje de avance para el modulo de inscripción en los submodulos  de experiencia laboral ( cuando se tiene información registrada y se registra una nueva el porcentaje pasa de 100 a 200), de forma análoga se deje ajustar el submodulo de documentos para que la visualización del porcentaje informe al usuario con respecto a la información registrada en el select, este select se cargara dependiendo del programa y el aspirante esta obligado a cargar todos los documentos pedidos en el select, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la visualización del porcentaje para el submodulo de experiencia laboral 
- [x] Ajustar la visualización para el submodulo de documentos con el requerimiento mencionado

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by JQuinteroC** [comment]
Se da por concluido el desarrollo, a la espera de revisión

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
