### ISSUE TITLE
Ajustar el no paso del tag de información personal y preinscripción a proyectos  sin creación de la información personal

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#587]
Se debe ajustar que si el aspirante no tiene registrado información personal (primer ingreso al sistema) no se puede permitir el paso al tag de inscripción de proyectos, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el ajuste para el paso entre tag si no cuenta con información personal
- [x] Crear modal para informar al usuario que debe crear primero la información personal para continuar con el proceso

**Comment by JQuinteroC** [comment]
Se da inicio a la issue

**Comment by JQuinteroC** [comment]
![imagen](https://user-images.githubusercontent.com/21268124/128298950-6ca62188-507a-4b23-8bc2-1186a70765d0.png)

**Comment by JQuinteroC** [comment]
Se concluye con el desarrollo y se da espera a la aprobación

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
