### ISSUE TITLE
Configurar tema en el cliente con la paleta de colores del SGA Tarea no planea para este sprint

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#60]
Teniendo en cuenta los [lineamientos] (https://docs.google.com/document/d/1CYv0sBfMXPEad7mfebhp1FxhRVnAjk79EnL9-ajvSWc/edit) se debe ajustar el tema del cliente del Sistema de Gestión Académica,  la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar los ajustes del cliente con los lineamientos datos.
- [x] Ajustar el cliente con los logotipos establecidos.
- [x] Ajustar la paleta de colores establecidos.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea, se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se hace merge de la rama a dev y test, se verifica ajuste del tema en el despliegue, ver https://pruebassga.portaloas.udistrital.edu.co/

Falta ajuste de Footer
