### ISSUE TITLE
Formulario información_familiar en inscripciones, tarea no planeada para este sprint.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#61]
Se debe integrar y modificar el componente de [inscripción](https://github.com/planesticud/campus_cliente) desarrollado por el equipo de campus, para esta tarea se desarrollará solo el tag del formulario información_familiar, sin funcionalidad, tener presente el [manual](https://docs.google.com/document/d/1fsKlGWu_LWgNr30_XraAccepOSXWHVhMWakBeBXxIJc/edit) para ver el proceso, tambien tener en cuenta para el diseño del formulario el [levantamiento de información](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit), el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en los documentos antes mencionados.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza la tarea de  crear un tag adicional para el registro de la información familiar sin funcionalidad, se debe tener en cuenta el proceso de pasar el componente del cliente de campus al de SGA llevo mucho mas tiempo de lo planeado se consumieron 48 horas de trabajo, se espera revisión tecnica por parte de @mafeave

**Comment by mafeave** [comment]
Se hace merge de los commits a la rama dev y test, se verifica integración del componente de Información Básica el cual contiene los formularios de:
- Información personal
- Información característica
- Información de contacto
- Información familiar

![Captura de pantalla de 2019-11-14 17-40-59](https://user-images.githubusercontent.com/14035745/68902318-fa12fa00-0705-11ea-8b0d-0d266fb40ed1.png)

Se da por finalizada la tarea.
