### ISSUE TITLE
Ajustar consulta de documentos en general en el modulo de admisión 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#632]
Se debe ajustar y desarrollar la consulta de los documentos en el modulo de admisión para que al visualizar los documentos, no se descarguen, si no reutilizar el componente que se implemento en la sección de evaluación de documentos, sin la función de aprobar documento, esto se debe  realizar en la sección de información académica, experiencia laboral, producciones académicas, descuento de matricula y propuesta de trabajo de grado, la issue debe cumplir con los siguientes requerimientos:

- [ ] Ajustar e incluir el botón soporte en la sección de información académica   
- [x] Ajustar la visualización  en la sección de experiencia laboral
- [ ]  Ajustar e incluir el botón soporte en la sección de producciones académicas
- [x] Ajustar la visualización  en la sección de Descuento de matricula 
- [x] Ajustar la visualización  en la sección de Propuesta de trabajo de grado

**Comment by fabianLeon** [comment]
Dado que los servicios para información básica y produccion académica no retornan el documento se da por finalizado esta tarea estableciendo un flujo de presentación del componente.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue.
