### ISSUE TITLE
Ajustar error de cuando no exista información en el tag de formación academica y experiencia laborar cuando no exista informacion con el nit

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#636]
Se debe capturar el error cuando se ingrese el nit de una universidad, colegio o empresa, actualmente si no se encuentra registrada se queda cargado y no permite continuar, se debe mostrar un modal informado que no existe información registrada, también algunas veces el nit se ingresa con un carácter vacío al principio o final del nit que totea la consulta, se debe controlar ese error, la issue debe cumplir con los siguientes requerimientos:

- [x] Capturar y ajustar el error de información no registrada 
- [x] Capturar y ajustar el error de caracteres vacíos

**Comment by JQuinteroC** [comment]
Se concluye desarrollo, a la espera de aprobación

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue.
