### ISSUE TITLE
Crear componente para asignación de documento a programas y descuentos

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#639]
Se debe crear un nuevo sub modulo de admisiones con nombre "Asignación de documentos y descuentos por proyecto" , se debe construir el componente reutilizando los que ya están definidos, se anexan mockup guía 

![image](https://user-images.githubusercontent.com/43799065/131149220-2803b4ba-e4f5-40e6-8682-af90a60eca7c.png)

 Al seleccionar descuento o documentos se abre una nueva vista que permite a partir de un select múltiple los documentos o descuentos que ya estén registrados , ver imagen guia

![image](https://user-images.githubusercontent.com/43799065/131147674-df048783-85f1-4c94-9374-e5e594fd73d2.png)

Si no existe en la lista se debe permitir el registro de un tipo de documento o descuento en el botón de administrar y este abre un modal para crear la información en la base de datos , ver imagen de guía 

![image](https://user-images.githubusercontent.com/43799065/131149396-f760ecfa-5892-40b7-aac9-82c2acef7020.png)

![image](https://user-images.githubusercontent.com/43799065/131147868-27bf9c6b-187a-4d13-817f-d7a0f1ffdff1.png)

Para la creación de la información paramétrica el  componente debe realizar la funcionalidad de get, post, put y delete tanto en documento como en descuentos, tener en cuenta que para la creación de un descuento existe un campo adicional que es porcentaje para la construcción del componente, la issue debe cumplir con los siguientes requerimientos:

- [x] Construir con base en los módulos ya existentes  para la Asignación de documentos y descuentos por proyecto
- [x] Construir los submodulos de creación de documentos y descuentos con su funcionalidad

**Comment by JQuinteroC** [comment]
Se concluye desarrollo de interfaz, a la espera de aprobación

**Comment by JQuinteroC** [comment]
Se realizaron correcciones

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue.
