### ISSUE TITLE
Revisar consulta de reporte de Histórico de Acreditaciones de un Proyecto Académico

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#66]
Revisar consulta de reporte de historico de acreditacionespuesto que esta es muy lenta.
- [x] El reporte de historico de acreditaciones por proyecto se demora menos en cargar.

**Comment by JuanPiedrahita** [comment]
El reporte actual se demora 30 segundos en ejecutarse.

**Comment by JuanPiedrahita** [comment]
SE mejora plantilla, se sube la plantilal al [drive](https://drive.google.com/open?id=1AyuXVWdFAhZqgvkGry2TFnL1C4t7Hr_t).

**Comment by JuanPiedrahita** [comment]
Se ejecuta nuevamente el reporte, la consulta tarda solo 2 segundos.

**Comment by JuanPiedrahita** [comment]
Se ejecuta nuevamente el reporte, la consulta tarda solo 2 segundos. Se adjunta evidencia de funcionamiento del reporte.

![imagen](https://user-images.githubusercontent.com/25555966/68252575-e4118500-fff3-11e9-96d7-4f4e4afcea11.png)

**Comment by JuanPiedrahita** [comment]
SE da por terminada la tarea.

**Comment by mafeave** [comment]
Se verifica ajuste en el reporte, se da por finalizada la tarea.
