### ISSUE TITLE
Arreglar el formato de los reportes: Listado de Proyectos Académicos y Histórico de Acreditaciones de un Proyecto Académico

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#67]
Arreglar formato de reportes de spagoBI.
- [x] El reporte de proyectos curriculares tiene el formato definido.
- [x] EL reporte de historico de registros por proyecto curricular tiene el formato definido.

**Comment by JuanPiedrahita** [comment]
Se comienza a revisar el ejemplo de formato subido a Spago como prueba Arka

**Comment by JuanPiedrahita** [comment]
Se ajusta plantilal de los reportes siguiendo el formato, se actualiza [plantilal ](https://drive.google.com/open?id=1AyuXVWdFAhZqgvkGry2TFnL1C4t7Hr_t) en el drive.

**Comment by JuanPiedrahita** [comment]
Se agrega evidencia de reporte de listado de proyectos

![imagen](https://user-images.githubusercontent.com/25555966/68409472-21415880-0155-11ea-9f96-b1a024e2d8e7.png)

**Comment by JuanPiedrahita** [comment]
Se agrega evidencia de registros por proyecto

![imagen](https://user-images.githubusercontent.com/25555966/68409530-3918dc80-0155-11ea-88c5-44ee9fae986c.png)

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea.

**Comment by JuanPiedrahita** [comment]
Se corrige formato con titulos del macroproceso y el proceso, se adjunta evidencia:


![imagen](https://user-images.githubusercontent.com/25555966/68681093-c03cca80-0530-11ea-8169-c5ac9d855a39.png)
![imagen](https://user-images.githubusercontent.com/25555966/68681110-cb8ff600-0530-11ea-9562-d5cceb22afb7.png)

**Comment by mafeave** [comment]
Verificados los formatos por el equipo de trabajo, se da por finalizada la tarea.
