### ISSUE TITLE
Creación del flujo para  la creación parcial de los terceros como universidades, colegios y empresa en el modulo de inscripción

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#670]
Se debe incluir un flujo alterno cuando no existe el tercero (colegio, universidad y empresa) en los módulos de inscripción tag de formación académica y experiencia laboral, en caso de que no exista información registrada en el sistema con la búsqueda del nit, se debe realizar los siguientes requerimientos:

 

- [x] Ajustar visualmente el componente de formación académica y experiencia laboral segun el mockup
![image](https://user-images.githubusercontent.com/43799065/133654471-de566729-bb9c-4de9-8803-0880a9720685.png)

- [x] Desarrollar un componente para incluir la información del tercero (colegio, universidad y empresa), puede ser un pop up o en el mismo formulario ya establecido, tener en cuenta los campos definidos en la imagen 
![image](https://user-images.githubusercontent.com/43799065/133650489-6bcd4e35-678a-4e7d-a2c5-c47e319f4b6e.png)

- [x] Crear submetodo o parte del método que antes de crear el tercero (colegio, universidad y empresa) verificar con el nit ingresado si no existe un tercero ya creado, si es asi devolver información y mostrar en el cliente un mensaje informado la existencia 

- [x] Se debe crear la Transacción a nivel del MID para la creación del tercero con el campo activo con valor false,  tener en cuenta que: en la tabla tercero enviar los siguientes campos ( nombre completo, lugar de origen ( id de ubicaciones_crud),  tipo_contribucion (id =2, persona jurídica) y fechas de creación y modificación según lineamientos)), tabla informacion_complementaria_tercero   campos (  tercero_id(previamente creado), info_complementaria_id (telefono id= 51, correo id= 53 y dirección id = 54) el dato es un json con el dato capturado del cliente) y en la tabla datos_identificación enviar siguientes campos ( tipo_documento_id= 7, tercero_id= id creado en la tabal tercero, numero = dato del cliente , campo activo y fechas de creación y modificiación))

- [x] Finalmente conectar lo desarrollado  en el nuevo flujo con el flujo actual para los tag de formación académica y experiencia laboral

**Comment by fabianLeon** [comment]
se tiene problemas al consultar tercero creado en experiencia_laboral/informacion_empresa.
portal motivo el tercero creado falla en el flujo de experiencia laboral.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue.
