### ISSUE TITLE
Analizar y replicar la funcionalidad del botón de pago según información compartida

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#672]
Se debe analizar la funcionalidad implementada para el botón de pago implementado en el sistema condor, para esto se cuenta con la siguiente información:

1. Código fuente  donde se implemento la funcionalidad de botón de pago para derechos pecuniarios en condor, desarrollado en php
[admin_consultarRecibosPecuniariosEstudiante.zip](https://github.com/udistrital/sga_cliente/files/7179894/admin_consultarRecibosPecuniariosEstudiante.zip)

2. host_servicio:
"https://funcionarios.portaloas.udistrital.edu.co/botonPago/index.php?recibo="
parámetros:
&REFERENCIA={secuencia}&NUM_DOC_IDEN={doc}&TIPO_DOC_IDEN={tipoDoc}

3. endpointABCPagos:
"https://www.abcpagos.com/udistrital/index.php"
empresaPSE:"0106"
servicioPSE:"1001"

Una vez analizada  la información se debe implementar la replica de esta funcionalidad en el componente de pago de derechos pecuniarios y preinscripción, la issue debe cumplir con los siguientes requerimientos:

- [x] Analizar la función desarrollada en el aplicativo condor para poder realizar la replica a nuestro sistema
- [ ] Implementar la funcionalidad de botón de pago para los módulos de  pago de derechos pecuniarios y preinscripción

**Comment by JQuinteroC** [comment]
Al analizar la tarea, se identifico que se debe consumir el servicio de producción y no el de pruebas, para esto es necesario realizar la prueba en un entorno real para manejar las bases de datos adecuadas.

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue.
