### ISSUE TITLE
Crear formulario de inscripcion para pregrado, posgrado, profesionalizacion tecnologos, ciclos propedeuticos, transferencia interna o externa, y reingreso - 2 semanas - 48 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#69]
Teniendo en cuenta que cada tipo de inscripción maneja un formulario diferente o pequeñas diferencias entre si, se debe desarrollar y organizar los formularios de inscripción, se debe tener en cuenta la información establecida en el [documento](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit),  el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en los documentos antes mencionados.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo.

**Comment by fabianbarreto02** [comment]
Se da por terminada la issue, se realizan los formularios necesarios para los tipo de inscripción establecidos en el documento relacionado al issue, ningún formulario cuenta con funcionalidad y estos formularios cambian dependiendo del select de tipo de inscripción, se agrega el tipo de inscripción movilidad académica que esta incluido en el documento pero no se planea en el sprit, se espera revisión por parte de la lider técnica @mafeave

**Comment by mafeave** [comment]
Se verifica carga de formularios de los siguientes tipos de inscripción:

Para pregrado, Ciclos propedéuticos, Transferencia externa, Movilidad Académica, Profesionalización tecnólogos:
![Captura de pantalla de 2019-12-04 06-38-52](https://user-images.githubusercontent.com/14035745/70139900-83f91780-1661-11ea-8bb3-ce70dcce6444.png)

Para Transferencia interna, Reingreso:
![Captura de pantalla de 2019-12-04 06-40-30](https://user-images.githubusercontent.com/14035745/70139915-91160680-1661-11ea-90b2-f8af0714ac58.png)

Para posgrado:
![Captura de pantalla de 2019-12-04 06-39-57](https://user-images.githubusercontent.com/14035745/70139928-9a9f6e80-1661-11ea-8f4f-2659dffa5cdf.png)
