### ISSUE TITLE
Diseño de mockups de gestión de proyecto curricular: consulta, registro y edición

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#7]
Se debe diseñar los posibles mockups para la gestión de los proyectos curriculares, el registro, la consulta y la edición de un proyecto, para el diseño de los mockups se tendra en cuenta la [historias de usuario](https://docs.google.com/spreadsheets/d/1QWxJGTgIzVM_2vNB2Dfs6NO16tR1vWOD32SlwhiBtcM/edit#gid=1979612365), la issue debe cumplir con los siguiente requerimiento:

- [x] Los mockups se debe realizar en la herramienta draw.io como esta establecido en los lineamiento de la OAS.
- [x] Los mockups debe contemplar todo lo definido en la historia de usuarios.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup general para el registro por primera vez de un proyecto curricular 

![Mockup Registro de proyecto curricular(1)](https://user-images.githubusercontent.com/43799065/64069844-6195cf00-cc18-11e9-8393-7de44df95781.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup de registro

![Mockup Registro de proyecto curricular(2)](https://user-images.githubusercontent.com/43799065/64069853-afaad280-cc18-11e9-8027-c984db14fd5e.png)
 de un proyecto curricular

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup general para la consulta de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares](https://user-images.githubusercontent.com/43799065/64069870-10d2a600-cc19-11e9-86ff-cb3dd56d250f.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup de consulta basica de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares(1)](https://user-images.githubusercontent.com/43799065/64069879-5c854f80-cc19-11e9-9c8d-499336720a31.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup la consulta completa o modificación de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares(2)](https://user-images.githubusercontent.com/43799065/64069887-98b8b000-cc19-11e9-957d-62191ffa77c5.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup la modificación de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares(3)](https://user-images.githubusercontent.com/43799065/64069898-c867b800-cc19-11e9-9bfd-8060508c13bc.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup para inhabilitar de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares(4)](https://user-images.githubusercontent.com/43799065/64069904-fc42dd80-cc19-11e9-976c-c31fa9d26f86.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup de una inhabilitar realizada de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares(5)](https://user-images.githubusercontent.com/43799065/64069913-357b4d80-cc1a-11e9-8ab1-6200493d96b5.png)

**Comment by fabianbarreto02** [comment]
Se expone en la siguiente imagen el mockup general de la acción de inhabilitar de un proyecto curricular

![Mockup Consulta, inhabilitar y modificacón de proyectos curriculares(6)](https://user-images.githubusercontent.com/43799065/64069932-73787180-cc1a-11e9-96bd-6e3e4f742ce8.png)

**Comment by fabianbarreto02** [comment]
Se espera la revisión técnica por parte de la técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se espera la revisión técnica por parte de la técnica @mafeave

**Comment by mafeave** [comment]
Se verifica con @FaustoPuerto y el equipo de trabajo los mockups realizados, se da por finalizada la tarea.
