### ISSUE TITLE
Ajustes de la función Crud (crear, consultar y editar) del tag de formación académica y  tag de experiencia laboral 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#701]
Se debe realizar el ajuste de la funcionalidad Crud para el tag formación académica (si es back o front) y el tag experiencia laborar en el tag de experiencia laboral , la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la migración para incluir la nueva información complementaria para los dos tag en el api de tercero 
- [x] Ajustar la función post (cliente y back) para los tag de  formación académica y tag de experiencia laboral con el nuevo flujo de almacenamiento de la información 
- [x] Ajustar la función de consulta  (cliente y back) para los tag de  formación académica y tag de experiencia laboral con el nuevo flujo de almacenamiento de la información, recuerso solo traer los registros activos. 
- [x] Ajustar la función de editar  (cliente y back) para los tag de  formación académica y tag de experiencia laboral con el nuevo flujo de almacenamiento de la información 
- [x] Crear la funcionalidad de eliminar ( desactivar el registro)  (cliente y back) para los tag de  formación académica y tag de experiencia laboral con el nuevo flujo de almacenamiento de la información

**Comment by JQuinteroC** [comment]
Se concluye desarrollo a la espera de correcciones

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
