### ISSUE TITLE
Ajustes Hito 1 SGA - proyecto curricular y reportes

### ISSUE THREAD

**Issue by DianaPatriciaRamirez** [udistrital/sga_cliente#72]
De acuerdo a la primera revisión funcional del hito 1 del Sistema de Gestión Académica realizada el 12 de noviembre; se revisa junto a la jefe Beatriz Jaramillo, el arquitecto Jhon Castellanos, Diana Guayara y el equipo SGA, y se realizan las siguientes observaciones:

- [x] En datos básicos, cambiar el orden del "Tipo duración" por "Duración". https://github.com/udistrital/sga_cliente/commit/f9af17430c3d98391f45eddae5b5b41aff936e62
- [x] La letra de los subtitulos está muy pequeña, también cambiar color. https://github.com/udistrital/sga_cliente/commit/89b93e8d909ffd9753164452064ecf6145315f2e
- [x] Revisar ortografía. Unificar formatos de textos, tamaño, mayúsculas, alineación textos en columnas, etc. https://github.com/udistrital/sga_cliente/commit/89b93e8d909ffd9753164452064ecf6145315f2e
- [x] Validar el servicio existente para "Titulación SNIES" y validar que el código SNIES se encuentre en la bodega de datos, preguntar a Diego Castellanos, Jhon Castellanos y Fausto Puerto. Verificar procedimiento. https://github.com/udistrital/sga_cliente/issues/74
- [x] En listado de proyectos, revisar la columna "Correo" ya que la información sale cortada, https://github.com/udistrital/sga_cliente/issues/76
- [x] En "Vigencia del registro": no está actualizando la fecha de finalización cuando se cambia el mes o cuando se cambia la fecha de creación, no recalcula.
- [x] Cambiar visualización como se está desarrollando en el "registro de acta de inicio en Arka II".
- [x] Cuando se cree el proyecto curricular exitosamente, se debe deshabilitar el botón de "Registro de Proyecto Curricular" y redirigir al formulario de consulta.
- [x] Solicitar a Viviana apoyo con el cambio de la paleta de colores, ya que cansa visualmente.
- [x] Revisar el mensaje "400 La solicitud contiene sintaxis errónea" y que visualice en qué campo se encuentra el error.
- [x] En la edición, revisar "Registro calificado y de alta calidad" ya que sale un error al guardar cambios.
- [x] En Consulta de un Proyecto Académico, alinear las tablas.
- [x] Tener en cuenta estas recomendaciones para todos los proyectos: 1) entre menos se digiten datos mejor, revisar si es posible obtenerlos de otro lado, 2) entre menos clicks de un usuario mas usable, 3) entre menos navegue el usuario por la pantalla mejor, sino tiene que hacer scroll super, y 4) entre menos deba salir y volver a entrar, mejor.

REPORTES:

- [x] Actualizar data source de los reportes
- [x] @FaustoPuerto revisar si están formalizados en el SIGUD, en caso negativo, solicitar al usuario formalizar los formatos de los reportes: listado de proyectos e histórico de acreditaciones.

CORE:

- [ ] Solicitar revisión de la interfaz única con respecto a la plantilla de despliegue de menús.

**Comment by mafeave** [comment]
De acuerdo a recomendación de @corio27, hablar con Alejandro Camacho de la Oficina de Acreditación, para socializar el desarrollo realizado y determinar que funciones cumplirían ellos en el sistema.

Tener en cuenta que se debe guardar la relación de los proyectos: cuando un proyecto cambia de nombre, se crea uno nuevo, pero debe quedar la relación con el proyecto antecesor

Se debe crear un nuevo proyecto si hay cambio de nombre o del número de créditos

**Comment by fabianbarreto02** [comment]
Se da inicio a los ajustes

**Comment by DianaPatriciaRamirez** [comment]
Actualizar data source de los reportes: https://github.com/udistrital/sga_cliente/issues/76

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se realizan ajustes adicionales como mover a un tag del registro del coordinador a un tag independiente para mejor entendimiento, el ajuste de la paleta de colores queda pendiente los lineamientos para realizar los ajustes. Pendiente revisión por parte de lider tecnica  @mafeave

**Comment by mafeave** [comment]
Revisar 
- redirección al formulario de listado de proyectos académicos
- selección de la fecha, cuando se clona el proyecto

**Comment by fabianbarreto02** [comment]
Se realizan los ajustes suguridos por @mafeave, se espera revision por parte de lider tecnica

**Comment by mafeave** [comment]
Se despliegan los ajustes en el entorno de pruebas, se verifica ajuste para la selección de la fecha de creación del proyecto y la redirección al listado de proyectos, una vez se realiza correctamente el registro del proyecto académico.
