### ISSUE TITLE
Ajustes calendario académico y proyectos curriculares 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#729]
Se debe realizar los ajustes a los módulos calendario académico y proyectos curriculares con los siquientes requerimientos:

- [x] Ajustar consulta en menú buscar calendario por proyecto para quitar loading cuando el json es vacío
- [x]  Cambiar  nombres de etiquetas en todo la sección de proyectos  de proyectos académicos a proyectos curriculares, también   revisar tildes.
- [x]  Cambiar orden de menús en la opción editar  proyecto curricular,  pasar acto administrativo después de información básica
- [x]  Cambiar nombre del botón "Agregar nuevo registro de alta calidad" por "Agregar acreditación en alta calidad"
- [x] Ajuste para centralizar el componente del registro de un proyecto curricular 
- [x] Revisar error al crear un nuevo énfasis en un proyecto creado al momento de actualizar 
- [x] Incluir etiqueta en el Select del experiencia laboral explicando como llegar el select

**Comment by JQuinteroC** [comment]
se concluye desarrollo, a la espera de correcciones

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
