### ISSUE TITLE
Revisión roles modulo de proyecto curricular

### ISSUE THREAD

**Issue by mafeave** [udistrital/sga_cliente#73]
Evaluar cuales son los roles que tendrían acceso al módulo de Gestión de Proyectos Curriculares

**Comment by mafeave** [comment]
De acuerdo con la información levantada por el analista @FaustoPuerto, la dependencia encargada del módulo es Vicerrectoría Académica desde el rol de Marco..

 Por otra parte, de acuerdo a información dada por @corio27, también interviene la Oficina de Acreditación, con la  cual está pendiente validar hasta que punto tendrían acceso del módulo desarrollado, para definir los roles involucrados en el sistema.

**Comment by DianaPatriciaRamirez** [comment]
Pendiente reunión con Acreditación para saber realmente el rol de ellos en el sistema @FaustoPuerto
