### ISSUE TITLE
Ajustar configuración de asignación de descuentos por vicerrectoría y no por programas en el tag de admisión

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#731]
Se debe ajustar el componente de asignación de descuentos para que sea visualizado solo por el rol "VICERRECTOR" y "ASESOR_VICE", usando la directiva ya desarrollada previamente, la issue debe cumplir con los siguientes requerimientos:

- [x]  Ajustar la visualización de la asignación de descuento con los roles mencionados

**Comment by JQuinteroC** [comment]
se concluye desarrollo

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
