### ISSUE TITLE
Ajustes de soporte documental para Tipo de población (antes grupo étnico)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#744]
se debe realizar el ajuste para incluir el soporte documental en el modulo de inscripción cuando se seleccione el tipo de población, se debe replicar la funcionalidad que se realizo para el documento de condición de discapacidad, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar el componente para la carga del documento soporte, este debe ser semejante al de tipo de discapacidad  
- [x] Cambiar el nombre de la etiqueta de Grupo étnico por Tipo de población 
- [x] Anexar un mensaje informativo al momento de seleccionar un tipo de discapacidad con el siguiente mensaje "Aspirante : Tenga en cuenta que la discapacidad debe estar contenida en la ley estatutaria 1618 de 2013, con su respectivo soporte documental"
- [x] Ajustar la funcionalidad para guarda el documento nuevo ( incluir el nueva información complementaria via migrations en tercero para almacenar el id del documento)
- [x] Ajustar la funcionalidad para la consulta de nuevo documento 
- [x]  Ajustar la funcionalidad para la edición de nuevo documento

**Comment by JQuinteroC** [comment]
se concluye desarrollo, se queda al pendiente alguna corrección y la observación de la resolución para el mensaje en el tipo de población

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
