### ISSUE TITLE
Ajustar visualización de columnas de reportes de Proyecto Curricular

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#76]
Corregir los reportes de proyecto curricular para que las columnas se visualicen de forma correcta.
- [x] Los textos en las columnas se muestran completamente.

**Comment by JuanPiedrahita** [comment]
Se corrige la plantilla, se adjunta evidencia.

![imagen](https://user-images.githubusercontent.com/25555966/69010815-6de51a80-0931-11ea-9e94-0c005f56bb1a.png)

**Comment by JuanPiedrahita** [comment]
Se actualizan datasources del reporte para que liste el reporte de la basde de datos udistrital_academica.

**Comment by JuanPiedrahita** [comment]
Se actualiza [carpeta](https://drive.google.com/open?id=1AyuXVWdFAhZqgvkGry2TFnL1C4t7Hr_t) de  reportes.

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea.

**Comment by mafeave** [comment]
Se verifica que el reporte esté consultando la base de datos udistrital_academica del ambiente de pruebas, sin embargo la columna del correo sigue saliendo cortada, ver https://pruebassga.portaloas.udistrital.edu.co/#/pages/reportes/proyectos/list-proyectos
![Captura de pantalla de 2019-11-18 08-00-38](https://user-images.githubusercontent.com/14035745/69054452-97f21780-09d9-11ea-90b9-5cd1ced78b5b.png)

**Comment by JuanPiedrahita** [comment]
Se corrige error en pruebas de sga:

![imagen](https://user-images.githubusercontent.com/25555966/69357960-11953a00-0c54-11ea-82e3-a02250fff5e0.png)

Se actualiza la [plantilla](https://drive.google.com/open?id=1AyuXVWdFAhZqgvkGry2TFnL1C4t7Hr_t) y se da por terminada la tarea.

**Comment by mafeave** [comment]
Se verifica ajuste de la plantilla, se da por finalizada la tarea.
