### ISSUE TITLE
Ajuste de sincronización de carga de información tag de información basica y ajustes de consulta select ciudad en el tag de información de contacto 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#767]
Se debe realizar  los siguientes ajustes en el componente de inscripción:

- [x] Ajuste de sincronización de la carga de información básica 
- [x] Ajustes de la consulta del select en el tag de información de contacto

**Comment by JQuinteroC** [comment]
se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
