### ISSUE TITLE
Revisar y ajustar los servicios del cliente en preproducción

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#77]
Revisar los servicios del cliente en preproducción y verificar que esten funcionando ok.
- [x] Los servicios del cliente en preprodcción se consumen de forma correcta.

**Comment by JuanPiedrahita** [comment]
Se realizó la revisión de los servicios en preproducción y se observó que el sga_mid no esta activo en esete momento y por lo tanto no se pudo realizar la validación del registro del coordinador, motivo por el cual esta tarea no se ha revisado.

**Comment by fabianbarreto02** [comment]
Se corrigen los servicios del cliente para pasar por autenticación, tambien se realizan los ajuste sugeridos por lider tecnica @mafeave por medio del correo, no se realiza el ajuste, de la revisión del error al actualizar un documento en el cliente, pues no conozco bien el funcionamiento de nuxeo, se espera apoyo de sebastian @JuanPiedrahita, se da por finalizada la issue, se espera la revisión por parte @mafeave

**Comment by mafeave** [comment]
Se verifica correcta carga de los servicios, hace falta asociar el API de ubicaciones_crud al cliente en WSO2
