### ISSUE TITLE
Desarrollar la funcionalidad para invitación a practicas académicas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#776]
Se debe desarrollar la funcionalidad para invitación a practicas académicas, los siguiente requerimientos:

- [x] Implementar la funcionalidad de consulta de la tabla de Lista de solicitudes de prácticas académicas
- [x] Implementar la funcionalidad de consulta del tag de solicitante 
- [x] Implementar la funcionalidad de consulta del tag de datos de la solicitud 
- [x] Implementar la funcionalidad de consulta del tag de consulta de documentos
- [x] Desarrollar la funcionalidad para el envio de correos, esta función debe recibir un arreglo con correos (quemadas inicialmente) y enviar los correos, tener como guia las [issues ](https://github.com/udistrital/produccion_academica_cliente/issues/39) y [issue ](https://github.com/udistrital/google_mid/issues/1) y consumir el servicio de google_mid

**Comment by JQuinteroC** [comment]
Se resuelve la issue, pero se deja como pendiente la consulta de los estudiantes inscritos al espacio académico hasta que su desarrollo se de por finalizado

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
