### ISSUE TITLE
Desarrollar funcionalidad para el informe de practica

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#788]
Se debe desarrollar para el informe de practica, la issue debe cumplir con los siguientes requerimientos:
 
- [x] Implementar la funcionalidad de consulta de la tabla de Lista de solicitudes de prácticas académicas
- [x] Implementar la funcionalidad de consulta del tag de solicitante 
- [x] Implementar la funcionalidad de consulta del tag de datos de la solicitud 
- [x] Implementar la funcionalidad de consulta del tag de consulta de documentos
- [x] Desarrollar la funcionalidad para la carga de los documentos informe de la practica y cumplido de la practica, junto a la funcionalidad de la actualización del estado de la solicitud

**Comment by JQuinteroC** [comment]
Se hace necesario agregar una tarea relacionada al desarrollo de la corrección de la solicitud de la practica a académica cuando esta es devuelta por parte de coordinación al docente solicitante, esto se resuelve en el siguiente commit asociado a la presente issue

**Comment by JQuinteroC** [comment]
se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
