### ISSUE TITLE
Analizar cómo funciona la consulta para los módulos producción  académica sub menu lista solicitudes para revisión de comité  y lista solicitudes tratadas en comité 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#793]
Se debe realizar el análisis de como  funciona la consulta para los módulos producción  académica sub menú lista solicitudes para revisión de comité  y lista solicitudes tratadas en comité para entender y poder realizar  los ajustes correspondientes, la issue debe cumplir con los siguientes requerimientos:

- [x]  Analizar cómo funciona la consulta para los módulos producción  académica submenú lista solicitudes para revisión de comité  
- [x] Analizar cómo funciona la consulta para los módulos producción  académica submenú lista solicitudes tratadas en comité

**Comment by JQuinteroC** [comment]
En el análisis se detectó que es necesario hacer la paginación de las solicitudes desde las peticiones realizadas a [sga mid](https://github.com/udistrital/sga_mid), pero es necesario la integración de más datos para poder evaluar mejor el comportamiento de las solicitudes

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
