### ISSUE TITLE
Modelo de datos proyecto curricular, teniendo en cuenta los modelo de datos de programas curriculares y el de Oikos (12 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#8]
Se debe diseñar el modelo de datos para los proyectos curriculales y el sistema OIKOS, la issue debe cumplir con los siguiente requerimientos:

- [x] El modelo debe seguir los lineamientos estipulasdos por la OAS.
- [x] El modelo debe desarrollarse en pgmodeler.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia Proceso de diseño

**Comment by fabianbarreto02** [comment]
Se inica el proceso de diseño, se ven los cambios del modelo actual con @mafeave y se verifica información con @FaustoPuerto

**Comment by fabianbarreto02** [comment]
Se anexa propuesta para el modelo de datos del proyecto academico.

![Programa academico V1](https://user-images.githubusercontent.com/43799065/64355108-40413400-cfc6-11e9-811f-7b9fa5750dc5.png)

**Comment by fabianbarreto02** [comment]
Se espera reunion para poder realizar la issue #9

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se realiza reunión con @jairolh, @corio27, @nodier25 en la cual se dieron las siguientes observaciones:
- Agregar los campos que relacionan el área y núcleo básico de conocimiento en la tabla programa_academico_institucion
- Agregar campo de enlace al documento de la resolución
- Cambiar nombre del esquema a proyecto_academico
- Cambiar nombre de la tabla programa_academico_institucion por proyecto_academico_institucion
- Cambiar tamaño del campo duracion de 10 a 3
- Cambiar nombre del campo compentencias a competencias
- Cambiar los campos codigo y codigo_snies  de tipo numeric a alfanumérico
- Agregar tabla paramétrica de tipo de registro (calificado, acreditación), unificar los campos de los tipos de registro
- Agregar los campos de fecha_creacion y fecha_modificacion en las tablas de programa_academico-institucion
- Relación de la persona (Coordinador y Asistente) con el programa_academico
- Campo que indique el tipo de titulación: SNIES y/o por genero
- En OIKOS: crear el tipo de dependencia 'coordinacion', para poder relacionar varios proyectos académicos a una misma coordinación, desde el cliente de registro del proyecto curricular, se debe hacer esa asociación
- Agregar la documentación del modelo - notas explicativas

**Comment by fabianbarreto02** [comment]
Se realizan las correciones en la #9, se espera revisón por parte de @mafeave
