### ISSUE TITLE
Desarrollar funcionalidad para tag generar recibo derechos pecuniarios y tabla de resumen 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#808]
Se debe desarrollar la funcionalidad para la generación del recibo de derechos, la issue debe cumplir con los siguientes requerimientos:

- [x]  Funcionalidad de consulta componente Generar recibo derechos pecuniarios
- [x] Funcionalidad Nueva Solicitud Boton resumen
- [x] Funcionalidad de consulta  Códigos relacionados al número de identificación
- [x] Funcionalidad de consulta   Derecho pecuniario
- [x] Funcionalidad de consulta   Verificación de datos para la generación de recibo
- [ ] Funcionalidad de generar el recibo (sujeto a disposición del servicio)

**Comment by JQuinteroC** [comment]
Se queda a la esperar del servicio para concluir la isssue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
