### ISSUE TITLE
Ajuste de bug en el modulo de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#819]
Se debe realizar el ajuste de los bug encontrados en el modulo de inscripción, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el loading del modulo de información básica cuando realmente no existe información 
- [x] Ajustar el porcentaje del tag de documentos en el modulo de información académica idiomas y actualizar la tabla al eliminar registro 
- [x]  Ajustar el botón de subir documento en el tag de documentos para que se pueda subir un documento después de otro
- [x] Ajustar el porcentaje del tag de descuentos 
- [x] Ajustar la carga de los select (sincronización) del tag de propuesta de trabajo de grado
- [x] Ajuste de carga inicial de los porcentajes en general

**Comment by JQuinteroC** [comment]
Se da por finalizada la issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
