### ISSUE TITLE
Desarrollar componente para las NOTAS PARCIALES con el ROL ESTUDIANTE 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#868]
Se debe desarrollar el componen para  las NOTAS PARCIALES con el ROL ESTUDIANTE  siguiendo los [mockups](https://drive.google.com/file/d/1ODbfpS-pbdM4Z5bd_CTV2ngLtO7ac_Hw/view?usp=sharing), la issue debe cumplir los siguientes requerimientos:

- [x] Desarrollar el componente NOTAS PARCIALES con el ROL ESTUDIANTE  

![image](https://user-images.githubusercontent.com/43799065/152072007-a753e99b-7474-4e89-b037-1c3fa3e5512c.png)

**Comment by NeFaWaltPint** [comment]
Se da inicio al desarrollo de la issue

**Comment by NeFaWaltPint** [comment]
Actividad terminada, se incluye creación de modulo _Asignaturas_ para alojar el componente requerido: **Notas parciales**.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
