### ISSUE TITLE
Desarrollar  api crud para el modelo de datos definidos 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#870]
Se debe desarrollar el api crud para el modelo de datos definido en la issue #869 , siguiendo todos los lineamientos definidos por la oficina, la issue debe cumplir con los siguientes requerimientos:

- [x] El api debe tener lo métodos básicos (POST, GET, UPDATE y DELETE)
- [x] El api debe contar con variables de entorno como los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/variables_en_api.md)
- [x] El api debe contar con el refactor para control de errores definidos en los [lineamientos](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/control_error_json_crud.md) 
- [x] El API debe contar con las migraciones para la creación del modelo segun los [lineamientos ](https://github.com/udistrital/lineamientos_oas/blob/master/generacion_de_apis/beego_migrations.md)
- [x] Documentar el repositorio con el readme, ramas y .gitignore  segun los [lineamientos ](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/contenido_readme.md)

**Comment by NeFaWaltPint** [comment]
Las tareas han sido terminadas dando como resultado dos api crud desarrolladas en NestJs, corriendo bajo _node 16.5.0_.

- [calificaciones_crud](https://github.com/udistrital/calificaciones_crud) - rama actualizada: **develop**
- [espacios_academicos_crud](https://github.com/udistrital/espacios_academicos_crud) - rama actualizada: **develop**

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
