### ISSUE TITLE
Desarrollar funcionalidad para la definición de Cortes ROL ADMINISTRATIVO y  activación botón de acción registrar notas según definición 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#881]
Se debe desarrollar la funcionalidad para la definición de Cortes ROL ADMINISTRATIVO y  activación botón de acción registrar notas según definición, la issue debe cumplir con los siguientes requerimientos:

- [x]  Desarrollar la funcionalidad para el registro, edición y visualización del la definición de los cortes con rol Administrativo 

![image](https://user-images.githubusercontent.com/43799065/153082816-8bf223a6-83b1-4d16-964d-31c4221b9257.png)

- [x]  Realizar la funcionalidad para la activación botón de acción registrar notas según definición, el boton se debe activar y permitir el paso de un ingreso si se encuentra habilitado  alguna fecha, de no esta habilitado mostrar modal donde se informe que no se encuentra habilitado el sistema

![image](https://user-images.githubusercontent.com/43799065/153083293-87776d6f-7d14-4c36-9170-e3e26c5781ac.png)

**Comment by NeFaWaltPint** [comment]
Se da inicio a las actividades

**Comment by NeFaWaltPint** [comment]
Las tareas se ha desarrollado.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
