### ISSUE TITLE
Desarrollar funcionalidad para ROL DOCENTE carga componente Captura de notas, Carga de información componente Registro de notas parciales y almacenamiento y carga de información del componente  Captura de porcentajes

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#884]
Se debe desarrollar funcionalidad para ROL DOCENTE carga componente Captura de notas, Carga de información componente Registro de notas parciales y almacenamiento y carga de información del componente  Captura de porcentajes, la issue debe cumplir con los siguientes requerimientos:

- [x] Ingresar un registro para tener información de consulta de un docente (utest01) y poder cargar la información en el componente carga académica asignada, registrar información en los modelos de espacio académico y  notas si es necesario.

![image](https://user-images.githubusercontent.com/43799065/153634972-7d6cf316-7421-418a-ab13-e55ef409f3ff.png)

- [x]  Realizar la función a función a nivel de mid para cargar la información de Registro de notas parciales

![image](https://user-images.githubusercontent.com/43799065/153635194-61ecc361-af8f-4c7f-b8a2-75ae28b2f004.png)

- [x] Realizar la función a nivle de mid para el almacenamiento y consulta del componente Captura de porcentajes

![image](https://user-images.githubusercontent.com/43799065/153635330-91916c3f-f1ef-4e1b-a88c-6bb39ad376a2.png)

**Comment by NeFaWaltPint** [comment]
Se da inicio y desarrollo a las tareas establecidas.

**Comment by NeFaWaltPint** [comment]
Se da por finalizada la issue las tareas han sido desarrolladas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
