### ISSUE TITLE
Ajustes modelo de datos proyecto curricular de acuerdo a observaciones de arquitectos y DBAs (2 horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#9]
Se debe realizar ajustes necesarios que se dispogan en la reunión por parte de los arquitectos y dbas, esta tarea depende de la tarea #8  para el inicio de la ejecución.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia tarea

**Comment by fabianbarreto02** [comment]
Segun lo acordado en la #8 en el [comentario](https://github.com/udistrital/sga_cliente/issues/8#issuecomment-528517695) se presenta el modelo con lo ajustes realizados 

![Programa academico V2](https://user-images.githubusercontent.com/43799065/64379117-da6ba100-cff3-11e9-928b-d243ef98ce08.png)

**Comment by fabianbarreto02** [comment]
Se espera revión por parte de @mafeave , @corio27 , @jairolh  y @fnrojash

**Comment by fabianbarreto02** [comment]
Se [anexa](https://drive.google.com/drive/folders/1KUbDWcM5kMtvE1J0auBr1Ink-OY89LI0) modelo base

**Comment by mafeave** [comment]
1. Cambiar nombre de la tabla institucion_enfasis por proyecto_academico_enfasis
2. Desde el Core no se almacenarán los años, por lo cual se debe ajustar los siguientes campos de  de integer a character varying de tamaño 4 y sin sufijo _id:
- Tabla: proyecto_academico_institucion, campo: ano_acto_administrativo_id
- Tabla: registro_calificado_acreditación, campo: ano_acto_administrativo_id
3. Quitar tilde en nombre de tabla registro_calificado_acreditación

**Comment by fabianbarreto02** [comment]
Se realizan correciones segun lider técnica, se actualiza tambien drive y api:

**Comment by jairolh** [comment]
Se verifica la corrección de los ajustes solicitados.
