### ISSUE TITLE
Ajuste hallazgo de pruebas seguridad modulo inscripciones 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#912]
Se debe realizar los ajustes de seguridad encontrados en el análisis de seguridad realizado y soportado en el [documento ](https://docs.google.com/document/d/15AM_XgOBjwZrgk2CaI2MUBH5zpjfKMW_c5WOuz3GIDs/edit?usp=sharing) entregado, la issue debe cumplir con los siguientes requerimientos: 

- [x] Capturar el error cuando se consulta el api sga_mid el endpoint [/v1/persona/consultar_persona/](http://pruebasapi.intranetoas.udistrital.edu.co:8119/v1/persona/consultar_persona/10090), persona que no existe 

![image](https://user-images.githubusercontent.com/43799065/156688262-e3fa82d4-de1c-453a-b454-df7d453c8d44.png)

- [x] Capturar el error cuando se consulta el api sga_mid el endpoint [/v1/persona/consultar_persona/](http://pruebasapi.intranetoas.udistrital.edu.co:8119/v1/persona/consultar_persona/10090), persona que no existe
![image](https://user-images.githubusercontent.com/43799065/156688316-0a662dd3-d3df-43b1-b902-6d3d26291426.png)

- [x] Capturar el error cuando se consulta el api sga_mid el endpoint [v1/persona/guardar_persona](http://pruebasapi.intranetoas.udistrital.edu.co:8119/v1/persona/guardar_persona) y se envia un json y body vacío
![image](https://user-images.githubusercontent.com/43799065/156688585-edf63901-0c77-43da-a263-f876b5020812.png)

- [x]  Capturar el error cuando se consulta el api sga_mid el endpoint [v1/persona/guardar_persona](http://pruebasapi.intranetoas.udistrital.edu.co:8119/v1/persona/guardar_persona) y se envia sin tipo de identificación, sin genero, sin estado civil
![image](https://user-images.githubusercontent.com/43799065/156688698-084d8f37-f86a-4cf4-bd97-81d7836cba55.png)

 - [x]  Capturar el error cuando se consulta el api sga_mid el endpoint /inscripciones/estado_recibos/{persona_id}/{id_periodo} cuando sin los parámetros de entrada, sin id del periodo y sin ningun parametro
![image](https://user-images.githubusercontent.com/43799065/156689006-86a77c8a-7e37-4cbe-bf19-0a5b33882f84.png)

- [x] Capturar la creación de dos recibos de inscripción con mismo usuario, carrera y periodo
![image](https://user-images.githubusercontent.com/43799065/156689366-312e5d7e-0844-4067-99da-13103213e8fe.png)

**Comment by NeFaWaltPint** [comment]
## PERSONA/CONSULTAR_PERSONA
### Id no existe
GET: `localhost:8119/v1/persona/consultar_persona/10090`
Respuesta:
```json
{
  "Data": null,
  "Message": "Error service SGA_MID: The request contains an incorrect parameter or no record exist",
  "Status": "404",
  "Success": false
}
```

### Id Nulo
GET: `localhost:8119/v1/persona/consultar_persona/NaN`
Respuesta:
```json
{
  "Data": null,
  "Message": "Error service SGA_MID: The request contains an incorrect parameter or no record exist",
  "Status": "404",
  "Success": false
}
```

_Ya solucionado con el controlador error.go_ :heavy_check_mark:

## PERSONA/GUARDAR_PERSONA
### json Nulo
POST: `localhost:8119/v1/persona/guardar_persona`
payload: 
```json

```
Respuesta:
```json
{
  "Message": "Error service PostGuardarPersona: The request contains an incorrect data type or an invalid parameter",
  "Status": "400",
  "Success": false
}
```
### json Vacío
POST: `localhost:8119/v1/persona/guardar_persona`
payload: 
```json
{}
```
Respuesta:
```json
{
  "Message": "Error service PostGuardarPersona: The request contains an incorrect data type or an invalid parameter",
  "Status": "400",
  "Success": false
}
```
### json sin algunos keys o mal escritos
POST: `localhost:8119/v1/persona/guardar_persona`
payload: 
```json
{
    "PrimerNombre": "Franz",
    "SegundoNombre": "Gregorio",
    "PrimerApellido": "Kafka",
    "SegundoApellido": "Samsa",
    "NumeroIdentificacion": "4546498",
    "VerificarNumeroIdentificacion": 4546498,
    "FechaExpedicion": "1901-07-08 00:00:00 +0000 +0000",
    "FechaNacimiento": "1883-07-03 00:00:00 +0000 +0000",
    "EstadoCivi": {
        "Id": 8,
        "Nombre": "SOLTERO",
        "CodigoAbreviacion": "SOLTERO",
        "Activo": true,
        "TipoDeDato": "",
        "GrupoInfoComplementariaId": {
            "Id": 2,
            "Nombre": "Estado Civil",
            "Descripcion": "Tipos de Estado Civil que puede tener un tercero / persona_natural.",
            "CodigoAbreviacion": "Grupo_2",
            "Activo": true,
            "FechaCreacion": "2019-11-07 20:38:40.825993 +0000 +0000",
            "FechaModificacion": "2019-11-07 20:38:40.825993 +0000 +0000"
        },
        "FechaCreacion": "2019-11-07 20:38:40.857778 +0000 +0000",
        "FechaModificacion": "2019-11-07 20:38:40.857778 +0000 +0000"
    },
    "OrientacionSexual": {
        "Id": 331,
        "Nombre": "No deseo contestar",
        "CodigoAbreviacion": "NO_CONTESTA",
        "Activo": true,
        "TipoDeDato": "",
        "GrupoInfoComplementariaId": {
            "Id": 1636,
            "Nombre": "Orientación Sexual",
            "Descripcion": "Se refiere a los gustos propios de cada persona",
            "CodigoAbreviacion": "ORIENTACION_SEXUAL",
            "Activo": true,
            "FechaCreacion": "2022-10-07 12:04:21.42484 +0000 +0000",
            "FechaModificacion": "2022-10-07 12:04:21.42484 +0000 +0000"
        },
        "FechaCreacion": "2022-10-07 12:05:18.266803 +0000 +0000",
        "FechaModificacion": "2022-10-07 12:05:18.266803 +0000 +0000"
    },
    "CorreoElectronico": "correo@correo.com",
    "User": "correo@correo.com"
}
```
Respuesta:
```json
{
  "Message": "Error service PostGuardarPersona: The request contains an incorrect data type or an invalid parameter",
  "Status": "400",
  "Success": false
}
```

_Se ajustó controlador para verificar que el json no ingrese nulo, vacío o sin alguno de los keys requeridos_

## INSCRIPCIONES/ESTADO_RECIBOS

### sin parámetros de entrada
GET: `localhost:8119/v1/inscripciones/estado_recibos/`
Respuesta:
```json
{
  "Data": null,
  "Message": "Error service SGA_MID: The request contains an incorrect parameter or no record exist",
  "Status": "404",
  "Success": false
}
```

### sin alguno de los parámetros
GET: `localhost:8119/v1/inscripciones/estado_recibos/10140`
Respuesta:
```json
{
  "Data": null,
  "Message": "Error service SGA_MID: The request contains an incorrect parameter or no record exist",
  "Status": "404",
  "Success": false
}
```

_Ya solucionado con el controlador error.go_ :heavy_check_mark:

### parámetros nulos
GET: `localhost:8119/v1/inscripciones/estado_recibos/NaN/NaN`
Respuesta:
```json
{
  "Response": {
    "Type": "error",
    "Code": "400",
    "Body": [
      "Response:",
      "json: cannot unmarshal object into Go value of type []map[string]interface {}"
    ]
  }
}
```
