### ISSUE TITLE
Desarrollar funcionalidad para la definición del select de documentos para diferentes tipos de inscripción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#926]
Se debe desarrollar la funcionalidad para la definición del select de documentos para diferentes tipos de inscripción, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el ajuste del modelo de datos para el api de inscripción para la relación del tipo de inscripción, se debe realizar el migrations , el ajuste del modelo del controlador y la actualización de la imagen en el repositorio con la versión realizada (readme).
- [x] Ajustar el componente de asignación de documentos en el modulo de admisiones con un select del tipo de inscripción, se debe llenar con los datos de la tabla tipo_inscripcion del api de inscripciones_crud, ajustar el post y el get de la tabla con el nuevo requerimiento del tipo de inscripción 
- [x] Ajustar las funciones de consulta para los componentes de documentos  en inscripciones nueva y los tres tipos de inscripción reingreso, transferencia externa e interna, tener presente que la consulta de los documentos deben tener como parametro el proyecto y tipo de inscripcion

**Comment by NeFaWaltPint** [comment]
Se da inicio a la resolución de las tareas.

**Comment by NeFaWaltPint** [comment]
Las tareas desarrolladas cumplen con los requerimientos, por tanto se dan por concluidas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
