### ISSUE TITLE
Levantamiento de requerimientos para información parametrica del sistema SGA en producción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#948]
Se debe realizar el levantamiento de requerimientos para información paramétrica del sistema SGA en producción, para esto se debe realizar un documento  con la información paramétrica, no transaccional de los siguiente módulos:

- [x]  Información paramétrica Modulo Actualización de datos 
- [x] Información paramétrica Modulo Calendario Academico 
- [x] Información paramétrica Modulo Hablitar periodo
- [x] Información paramétrica Modulo Proyecto curricular 
- [x] Información paramétrica Modulo Inscripción 
- [x] Información paramétrica Modulo Admisiones

**Comment by JQuinteroC** [comment]
[documento](https://docs.google.com/document/d/1An7OYCGI2PsSkcweXtdKj924D2zOJT6V/edit?usp=sharing&ouid=106198941788662390373&rtpof=true&sd=true)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
