### ISSUE TITLE
Desarrollo de la funcionalidad de consulta y actualización de  registro de notas rol docente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#949]
Se debe desarrollo de la funcionalidad de consulta y actualización de  registro de notas rol docente, se debe cumplir los siguientes requerimientos:

- [x] Desarrollar la funcionalidad de consulta de notas para un espacio académico en un periodo particular , debe cargar todas las notas y estudiantes registrados hasta el momento.
- [x] Desarrollar la funcionalidad PUT para la actualización del registro de notas de todos los estudiantes registrados en el espacio académico

**Comment by NeFaWaltPint** [comment]
Se da desarrollo y finalización a las actividades pendientes.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
