### ISSUE TITLE
Revisar actualización de documentos al modificar proyecto académico

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_cliente#95]
Revisar el modulo de proyecto academico y verificar por que se presenta un error al tratar de modificar un proyecto academico.
- [x] El sistema permite modificar un proyecto curricular correctamente.

**Comment by JuanPiedrahita** [comment]
Se intenta actualizar el primer proyecto (sin documento) y se observa que se esta consultando uan url erronea

![image](https://user-images.githubusercontent.com/25555966/69756844-6e4b9580-1129-11ea-9b07-c9867a691655.png)

**Comment by JuanPiedrahita** [comment]
Se valida el error y se verifica que este esta en el request manager, se hace el ajuste para que no se envie un undefined pero quedaria pendiente por validar en que otros casos esto fallaria. Se adjuntaa evidencai y se da por temrinada la tarea,

![image](https://user-images.githubusercontent.com/25555966/69760529-c3d87000-1132-11ea-85e6-2e3e6302857d.png)

**Comment by mafeave** [comment]
Se hace merge a dev y test, y se verifica funcionamiento de la actualización de documentos al modificar algún proyecto académico.
Se da por finalizada la tarea.
