### ISSUE TITLE
Desarrollar funcionalidad para generación de PDF (reporte de notas) a partir del componente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#950]
Se debe desarrollar la funcionalidad para generación de PDF (reporte de notas) a partir del componente, la issue debe cumplir con los siguientes requerimientos:

- [x] El pdf se debe generar a partir del componente de registros de notas, similar al comprobante de inscripción actualmente
- [x] El PDF debe contener el componente de registro de notas(información), Porcentaje de notas y las notas 
- [x] Se debe permitir la impresión desde el visualizador del pdf 
- [x] Agregar la fecha y hora de creación del reporte

**Comment by NeFaWaltPint** [comment]
Se da desarrollo y fin a las tareas pendientes para la presente issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
