### ISSUE TITLE
Desarrollar funcionalidad para el componente de Estado registro y la funcionalidad de consulta para un periodo particular 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#970]
Se debe desarrollar funcionalidad para el componente de Estado registro y la funcionalidad de consulta para un periodo particular, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar funcionalidad a nivel de Mid para la consulta de la información de la tabla, para esto se recibe el periodo de consulta, debe devolver todos los docentes que tengan asignado espacios académico, junto al resto de la información, consulta numero de identificación del docente, nombre en terceros y la información de la asignatura y estado del registro de notas
    
![image](https://user-images.githubusercontent.com/43799065/162104280-41e41cd1-7d78-4efb-a32f-4fc5b721f145.png)

**Comment by NeFaWaltPint** [comment]
Se da inicio a las tareas asignadas.

**Comment by NeFaWaltPint** [comment]
La tarea asignada ha sido desarrollada.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
