### ISSUE TITLE
Ajuste de modelo de datos, apis y cliente (módulo de admisión e inscripción de aspirantes porcentaje) para documentos no obligatorio  como la libreta militar

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#974]
Se debe realizar el ajuste de modelo de datos, apis y cliente (módulo de admisión e inscripción de aspirantes porcentaje) para documentos no obligatorio  como la libreta militar, esta issue debe cumplir con los siguientes requerimientos:

- [x] Creación de un campo en la tabla documento_programa en el esquema de inscripcion_crud llamdo obligatorio y de tipo boolean para definir si el documento es obligatorio.
- [x] Actualización de modelo del api, documentación y creación de migrations con el campo creado 
- [x] Actualización del cliente modulo admisiones/ asignación de documentos y descuentos para el registro de nuevo campo (button toggle)  y registro de información.
- [x] Actualización de la consulta de la lista en el modulo de inscripción tag de documentos, se debe ajustar la función del porcentaje, si el documento no es obligatorio no se debe tener en cuenta para el calculo del avance del porcentaje (100%)

**Comment by NeFaWaltPint** [comment]
Se da inicio al desarrollo de las tareas asignadas.

**Comment by NeFaWaltPint** [comment]
Las tareas han sido desarrolladas

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
