### ISSUE TITLE
Ajustes varios para el módulo de registros de notas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#984]
Se debe realizar varios ajustes finales para el modulo del registro de notas, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el ajuste para el campo de observación sea un select con la información correspondiente 
- [x] Realizar el ajuste del cliente y apis para el cierre de la captura de nota de examenes finales y habilitaciones como se realiza en los dos cortes 
- [x] Realizar funcionalidad a nivel mid para  el calculo de la notas ciñéndose al documento establecido para los campos de nota aculado y definitivo  sin el promedio acumulado 
- [x] Revisar la generación del pdf sin captura si no el componente, convertir tabla a pdf

**Comment by NeFaWaltPint** [comment]
Se da inicio y desarrollo a las tareas propuestas.

**Comment by NeFaWaltPint** [comment]
**Revisar la generación del pdf sin captura si no el componente, convertir tabla a pdf**

Alternativa a captura de imagen; se puede transcribir el código html al sistema de etiquetas de **pdfMake** usando la librería _html-to-pdfmake_ 
https://www.itsolutionstuff.com/post/how-to-convert-html-into-pdf-in-angular-11example.html

**Ventajas**
- Se integra bien con pdfMake
- No hay problemas de resolución
- Al ser texto se puede adaptar al formato de papel que se necesite
- Se puede modificar el contenido para en dado caso dar una mejor representación

**Desventajas**
- Hay que aplicar estilos manualmente
- No funciona muy bien cuando hay child components, genera error o quedan zonas vacías _(puede ser un problema en las smart tables que tienen componentes renderizados, la tabla de registro de notas tiene bastante renderizado)_
- Debido a que por defecto no toma el scss, puede quedar muy mal distribuido gráficamente
- Los estilos hay que aplicarlos manualmente

Otra alternativa es partiendo de los datos en las variables (en lado cliente) construir manualmente mediante el sistema de etiquetas de pdfMake el documento pdf. Puede ser una buena alternativa para evitar conflictos en la autogeneración del documento usando html-to-pdfMake, es más largo el proceso, pero se tiene mayor control.
https://pdfmake.github.io/docs/0.1/document-definition-object/tables/

**Comment by NeFaWaltPint** [comment]
Se dan por finalizadas las tareas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
