### ISSUE TITLE
Ajuste de modelo de datos y api(modelos, migrations y documentación)  para la definición de los nuevos requerimientos ( habilitar la edición de fechas entre el rango global, manejo de calendarios paralelo para fechas de extensión o versionamiento) 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#987]
Se debe realizar el Ajuste de modelo de datos y api(modelos, migrations y documentación)  para la definición de los nuevos requerimientos ( habilitar la edición de fechas entre el rango global, manejo de calendarios paralelo para fechas de extensión o versiona miento), la issue debe cumplir con los siguientes requerimientos:

- [x] Analizar y comprender el modelo de datos de eventos (calendario academico)
- [x]  Analizar en su totalidad el [mockup ](https://drive.google.com/file/d/1XN6hxntKoS6IRqi9LlLjhuH9SCMxN8tu/view?usp=sharing)con los nuevos requerimientos del calendario académico  
- [x] Proponer una solución al modelo de datos para el manejo de habilitar la edición de fechas entre el rango global, manejo de calendarios paralelo para fechas de extensión o versiona miento
- [x] Ajustar el modelo de datos (documento y apis) y crear las migraciones para ajustes

**Comment by fabianbarreto02** [comment]
https://drive.google.com/drive/u/0/folders/13LT-frANXRN6VscPavXCv2CsMtjiNgE3

**Comment by NeFaWaltPint** [comment]
Se da inicio a las tareas propuestas.

**Comment by NeFaWaltPint** [comment]
Se dan por finalizadas las tareas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
