### ISSUE TITLE
Desarrollar la funcionalidad para los formulario informacion personal de inscripcion - tipo de inscripción pregrado - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#99]
Se debe realizar la funcionalidad del registro de información personal en el tipo de inscripción pregrado,  se debe tener en cuenta la información establecida en el [documento](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit),  el cliente debe cumplir con los siguientes requerimientos:
 
- [x] El cliente debe tener toda la información definida en los documentos antes mencionados.
- [x] El cliente debe desarrollarse en forma de componente para la integración posterior.
- [x] La funcionalidad debe registrar la informaón basica en el Api de terceros desarrollado por el equipo core.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se da inicio a la tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se despliegan los commits realizados y se verifica funcionalidad de registro de los datos correspondientes a la información personal. Formulario final:
![Captura de pantalla de 2019-12-09 06-30-19](https://user-images.githubusercontent.com/14035745/70433006-92bf4000-1a4e-11ea-86b8-e68af910cea3.png)
