### ISSUE TITLE
Ajustes de los componentes del módulo de calendario académico rol de programa curricular y vicerrectoría, componente  administración de calendario académico por proyecto curricular, edición de fechas a proyectos y extensión de fechas 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#995]
Se debe realizar el Ajuste de los componentes del módulo de calendario académico rol de programa curricular y vicerrectoría, componente  administración de calendario académico por proyecto curricular, edición de fechas a proyectos y extensión de fechas  siguiendo los [mockups ](https://drive.google.com/file/d/1XN6hxntKoS6IRqi9LlLjhuH9SCMxN8tu/view?usp=sharing)definidos, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear el menú de administración calendario y el componente para el rol del programa con las funcionalidades los flujos del mockup
![image](https://user-images.githubusercontent.com/43799065/167058019-455f063b-9ea0-4011-a207-129fc01298fe.png)

- [x]  Desarrollar el componente para el rol de vicerrectoría  para la asignación de edición de fechas y visualización de las fechas definidas por el proyecto.
![image](https://user-images.githubusercontent.com/43799065/167058359-6c55504d-0731-4d66-a3ef-da2fcb6f94b7.png)

![image](https://user-images.githubusercontent.com/43799065/167058392-e42bdce1-3f5e-464f-8af6-f94de97caead.png)

- [x] Desarrollar el componente para el rol de vicerrectoría  para la asignación de extensión de calendario con los flujos del componente 

![image](https://user-images.githubusercontent.com/43799065/167058634-8940189c-f14d-4d38-bb8d-c1c1f77cf509.png)

**Comment by NeFaWaltPint** [comment]
Se da inicio y desarrollo de las actividades propuestas.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
