### ISSUE TITLE
Realizar funcionalidad para la activación de edición de fechas desde el rol de vicerrectoría, funcionalidad de consulta y edición de fechas de actividades   para el rol de programas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_cliente#997]
Se debe realizar funcionalidad para la activación de edición de fechas desde el rol de vicerrectoría, funcionalidad de consulta y edición de fechas de actividades   para el rol de programas, la issue debe cumplir con los siguientes requerimientos: 

- [x] Crear la funcionalidad para la consulta de los programas que ya tienen asignado el calendario para el componente de Selección de edición a proyectos curriculares y la funcionalidad para la activación de edición de fechas a programas particulares  rol vicerrectoría.
- [x]  Crear funcionalidad para consultar con el id de terceros en la tabla vinculación el programa al que pertenece el usuario y cargue la información del calendario en el submenu administración calendario (proceso y actividades) usar usuario maes_ing_civil
- [x] Funcionalidad verificación activación modificación fechas al momento de botón editar 
- [x]  Crear funcionalidad para la definición de fechas particulares a actividades, (clonar y relacionar actividad)
- [x] Función de bloque de fechas hijas con respecto a fechas padres (cliente)
- [x] Ajustar consulta para traer la fechas globales y las fechas especificas a las actividades modificadas

**Comment by NeFaWaltPint** [comment]
Se da desarrollo y finalización a las tareas asignadas.
